--
-- Type: TABLE; Owner: TM_CZ; Name: ANNOTATION_DEAPP
--
 CREATE TABLE "TM_CZ"."ANNOTATION_DEAPP" 
  (	"GPL_ID" VARCHAR2(100 BYTE), 
"PROBE_ID" VARCHAR2(100 BYTE), 
"GENE_SYMBOL" VARCHAR2(100 BYTE), 
"GENE_ID" VARCHAR2(100 BYTE), 
"PROBESET_ID" NUMBER(38,0), 
"ORGANISM" VARCHAR2(200 BYTE)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

