--
-- Type: TABLE; Owner: TM_CZ; Name: BIO_DATA_UID_RELEASE
--
 CREATE TABLE "TM_CZ"."BIO_DATA_UID_RELEASE" 
  (	"BIO_DATA_ID" NUMBER(18,0) NOT NULL ENABLE, 
"UNIQUE_ID" NVARCHAR2(200) NOT NULL ENABLE, 
"BIO_DATA_TYPE" NVARCHAR2(100) NOT NULL ENABLE, 
"RELEASE_STUDY" NVARCHAR2(200) NOT NULL ENABLE
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

