--
-- Type: TABLE; Owner: TM_CZ; Name: CATEGORY_PATH_EXCLUDED_WORDS
--
 CREATE TABLE "TM_CZ"."CATEGORY_PATH_EXCLUDED_WORDS" 
  (	"EXCLUDED_TEXT" VARCHAR2(100 BYTE)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

