--
-- Type: TABLE; Owner: TM_CZ; Name: DE_GPL_INFO_RELEASE
--
 CREATE TABLE "TM_CZ"."DE_GPL_INFO_RELEASE" 
  (	"PLATFORM" VARCHAR2(10 BYTE), 
"TITLE" VARCHAR2(500 BYTE), 
"ORGANISM" VARCHAR2(100 BYTE), 
"ANNOTATION_DATE" TIMESTAMP (6)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

