--
-- Type: TABLE; Owner: TM_CZ; Name: DE_SNP_DATA_BY_PATIENT_RELEASE
--
 CREATE TABLE "TM_CZ"."DE_SNP_DATA_BY_PATIENT_RELEASE" 
  (	"SNP_DATA_BY_PATIENT_ID" NUMBER(22,0), 
"SNP_DATASET_ID" NUMBER(22,0), 
"TRIAL_NAME" VARCHAR2(255 BYTE), 
"PATIENT_NUM" NUMBER, 
"CHROM" VARCHAR2(16 BYTE), 
"DATA_BY_PATIENT_CHR" CLOB, 
"PED_BY_PATIENT_CHR" CLOB, 
"RELEASE_STUDY" VARCHAR2(255 BYTE)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" 
LOB ("DATA_BY_PATIENT_CHR") STORE AS BASICFILE (
 TABLESPACE "TRANSMART" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
 NOCACHE NOLOGGING ) 
LOB ("PED_BY_PATIENT_CHR") STORE AS BASICFILE (
 TABLESPACE "TRANSMART" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
 NOCACHE NOLOGGING ) ;

