--
-- Type: TABLE; Owner: TM_CZ; Name: DE_SNP_PROBE_RELEASE
--
 CREATE TABLE "TM_CZ"."DE_SNP_PROBE_RELEASE" 
  (	"SNP_PROBE_ID" NUMBER(22,0), 
"PROBE_NAME" VARCHAR2(255 BYTE), 
"SNP_ID" NUMBER(22,0), 
"SNP_NAME" VARCHAR2(255 BYTE), 
"VENDOR_NAME" VARCHAR2(255 BYTE)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

