--
-- Type: TABLE; Owner: TM_CZ; Name: DE_SNP_PROBE_SORT_DEF_RELEASE
--
 CREATE TABLE "TM_CZ"."DE_SNP_PROBE_SORT_DEF_RELEASE" 
  (	"SNP_PROBE_SORTED_DEF_ID" NUMBER(22,0), 
"PLATFORM_NAME" VARCHAR2(255 BYTE), 
"NUM_PROBE" NUMBER, 
"CHROM" VARCHAR2(16 BYTE), 
"PROBE_DEF" CLOB, 
"SNP_ID_DEF" CLOB
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" 
LOB ("PROBE_DEF") STORE AS BASICFILE (
 TABLESPACE "TRANSMART" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
 NOCACHE NOLOGGING ) 
LOB ("SNP_ID_DEF") STORE AS BASICFILE (
 TABLESPACE "TRANSMART" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
 NOCACHE NOLOGGING ) ;

