--
-- Type: TABLE; Owner: TM_CZ; Name: DE_SNP_GENE_MAP_RELEASE
--
 CREATE TABLE "TM_CZ"."DE_SNP_GENE_MAP_RELEASE" 
  (	"SNP_ID" NUMBER(22,0), 
"SNP_NAME" VARCHAR2(255 BYTE), 
"ENTREZ_GENE_ID" NUMBER
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

