--
-- Type: TABLE; Owner: TM_CZ; Name: MIRNA_ANNOTATION_DEAPP
--
 CREATE TABLE "TM_CZ"."MIRNA_ANNOTATION_DEAPP" 
  (	"ID_REF" VARCHAR2(100 BYTE), 
"PROBE_ID" VARCHAR2(100 BYTE), 
"MIRNA_SYMBOL" VARCHAR2(100 BYTE), 
"MIRNA_ID" VARCHAR2(100 BYTE), 
"PROBESET_ID" NUMBER(38,0), 
"ORGANISM" VARCHAR2(200 BYTE), 
"GPL_ID" VARCHAR2(20 BYTE)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

