--
-- Type: TABLE; Owner: TM_CZ; Name: PROBESET_DEAPP_20120206
--
 CREATE TABLE "TM_CZ"."PROBESET_DEAPP_20120206" 
  (	"PROBESET_ID" NUMBER NOT NULL ENABLE, 
"PROBESET" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
"PLATFORM" VARCHAR2(100 BYTE) NOT NULL ENABLE
  ) SEGMENT CREATION DEFERRED
 TABLESPACE "TRANSMART" ;

