--
-- Type: TABLE; Owner: TM_CZ; Name: STG_SUBJECT_RBM_DATA
--
 CREATE TABLE "TM_CZ"."STG_SUBJECT_RBM_DATA" 
  (	"TRIAL_NAME" VARCHAR2(100 BYTE), 
"ANTIGEN_NAME" VARCHAR2(100 BYTE), 
"VALUE_TEXT" VARCHAR2(100 BYTE), 
"VALUE_NUMBER" NUMBER, 
"TIMEPOINT" VARCHAR2(100 BYTE), 
"ASSAY_ID" VARCHAR2(100 BYTE), 
"SAMPLE_ID" VARCHAR2(100 BYTE), 
"SUBJECT_ID" VARCHAR2(100 BYTE), 
"SITE_ID" VARCHAR2(100 BYTE)
  ) SEGMENT CREATION IMMEDIATE
NOCOMPRESS LOGGING
 TABLESPACE "TRANSMART" ;
