--
-- Type: TABLE; Owner: TM_CZ; Name: TJEA_JUNK
--
 CREATE TABLE "TM_CZ"."TJEA_JUNK" 
  (	"PROBESET" VARCHAR2(100 BYTE), 
"EXPR_ID" VARCHAR2(100 BYTE), 
"RAW_INTENSITY" VARCHAR2(50 BYTE)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

