--
-- Type: TABLE; Owner: TM_CZ; Name: TMP_TRIAL_DATA
--
 CREATE TABLE "TM_CZ"."TMP_TRIAL_DATA" 
  (	"USUBJID" VARCHAR2(50 BYTE), 
"STUDY_ID" VARCHAR2(25 BYTE), 
"DATA_TYPE" CHAR(1 BYTE), 
"VISIT_NAME" VARCHAR2(100 BYTE), 
"DATA_LABEL" VARCHAR2(500 BYTE), 
"DATA_VALUE" VARCHAR2(500 BYTE), 
"UNIT_CD" VARCHAR2(50 BYTE), 
"CATEGORY_PATH" VARCHAR2(250 BYTE), 
"SUB_CATEGORY_PATH_1" VARCHAR2(250 BYTE), 
"SUB_CATEGORY_PATH_2" VARCHAR2(250 BYTE), 
"PATIENT_NUM" NUMBER(38,0), 
"SOURCESYSTEM_CD" VARCHAR2(50 BYTE), 
"BASE_PATH" VARCHAR2(1250 BYTE)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

