--
-- Type: TABLE; Owner: SEARCHAPP; Name: PLUGIN_MODULE
--
 CREATE TABLE "SEARCHAPP"."PLUGIN_MODULE" 
  (	"MODULE_SEQ" NUMBER NOT NULL ENABLE, 
"PLUGIN_SEQ" NUMBER NOT NULL ENABLE, 
"NAME" VARCHAR2(70 BYTE) NOT NULL ENABLE, 
"PARAMS" CLOB NOT NULL ENABLE, 
"VERSION" VARCHAR2(10 BYTE) DEFAULT 0.1 NOT NULL ENABLE, 
"ACTIVE" CHAR(1 BYTE) DEFAULT 'Y' NOT NULL ENABLE, 
"HAS_FORM" CHAR(1 BYTE) DEFAULT 'N' NOT NULL ENABLE, 
"FORM_LINK" VARCHAR2(90 BYTE), 
"FORM_PAGE" VARCHAR2(90 BYTE), 
"MODULE_NAME" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
"CATEGORY" VARCHAR2(50 BYTE)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "BIOMART" 
LOB ("PARAMS") STORE AS BASICFILE (
 TABLESPACE "BIOMART" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
 NOCACHE LOGGING ) ;
