--
-- Type: TABLE; Owner: SEARCHAPP; Name: REPORT_ITEM
--
 CREATE TABLE "SEARCHAPP"."REPORT_ITEM" 
  (	"REPORT_ITEM_ID" NUMBER(18,0), 
"REPORT_ID" NUMBER(18,0), 
"CODE" VARCHAR2(200 BYTE)
  ) SEGMENT CREATION DEFERRED
 TABLESPACE "TRANSMART" ;

