--
-- Type: TABLE; Owner: SEARCHAPP; Name: SEARCH_USER_FEEDBACK
--
 CREATE TABLE "SEARCHAPP"."SEARCH_USER_FEEDBACK" 
  (	"SEARCH_USER_FEEDBACK_ID" NUMBER(18,0), 
"SEARCH_USER_ID" NUMBER(18,0), 
"CREATE_DATE" DATE, 
"FEEDBACK_TEXT" NVARCHAR2(2000), 
"APP_VERSION" NVARCHAR2(100), 
 CONSTRAINT "RDT_SEARCH_USER_FDBK_PK" PRIMARY KEY ("SEARCH_USER_FEEDBACK_ID")
 USING INDEX
 TABLESPACE "TRANSMART"  ENABLE
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

