--
-- Type: TABLE; Owner: SEARCHAPP; Name: SEARCH_USER_SETTINGS
--
 CREATE TABLE "SEARCHAPP"."SEARCH_USER_SETTINGS" 
  (	"ID" NUMBER, 
"USER_ID" NUMBER, 
"SETTING_NAME" VARCHAR2(255 BYTE), 
"SETTING_VALUE" VARCHAR2(1024 BYTE), 
 UNIQUE ("USER_ID", "SETTING_NAME", "SETTING_VALUE")
 USING INDEX
 TABLESPACE "BIOMART"  ENABLE
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "BIOMART" ;
