--
-- Type: TABLE; Owner: SEARCHAPP; Name: SEARCH_ROLE_AUTH_USER
--
 CREATE TABLE "SEARCHAPP"."SEARCH_ROLE_AUTH_USER" 
  (	"PEOPLE_ID" NUMBER(19,0), 
"AUTHORITIES_ID" NUMBER(19,0)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

--
-- Type: REF_CONSTRAINT; Owner: SEARCHAPP; Name: FKFB14EF798F01F561
--
ALTER TABLE "SEARCHAPP"."SEARCH_ROLE_AUTH_USER" ADD CONSTRAINT "FKFB14EF798F01F561" FOREIGN KEY ("PEOPLE_ID")
 REFERENCES "SEARCHAPP"."SEARCH_ROLE" ("ID") ENABLE;

--
-- Type: REF_CONSTRAINT; Owner: SEARCHAPP; Name: FKFB14EF79287E0CAC
--
ALTER TABLE "SEARCHAPP"."SEARCH_ROLE_AUTH_USER" ADD CONSTRAINT "FKFB14EF79287E0CAC" FOREIGN KEY ("AUTHORITIES_ID")
 REFERENCES "SEARCHAPP"."SEARCH_AUTH_USER" ("ID") ENABLE;

