--
-- Type: TABLE; Owner: SEARCHAPP; Name: SEARCH_BIO_MKR_CORREL_FAST_MV
--
 CREATE TABLE "SEARCHAPP"."SEARCH_BIO_MKR_CORREL_FAST_MV" 
  (	"DOMAIN_OBJECT_ID" NUMBER NOT NULL ENABLE, 
"ASSO_BIO_MARKER_ID" NUMBER, 
"CORREL_TYPE" VARCHAR2(19 BYTE), --oracle was CHARACTER
"VALUE_METRIC" NUMBER, 
"MV_ID" NUMBER
  ) SEGMENT CREATION DEFERRED
NOCOMPRESS NOLOGGING
 TABLESPACE "BIOMART" ;
