--
-- Type: TABLE; Owner: SEARCHAPP; Name: SEARCH_AUTH_PRINCIPAL
--
 CREATE TABLE "SEARCHAPP"."SEARCH_AUTH_PRINCIPAL" 
  (	"ID" NUMBER(19,0) NOT NULL ENABLE, 
"PRINCIPAL_TYPE" VARCHAR2(255 BYTE), 
"DATE_CREATED" DATE NOT NULL ENABLE, 
"DESCRIPTION" VARCHAR2(255 BYTE), 
"LAST_UPDATED" DATE NOT NULL ENABLE, 
"NAME" VARCHAR2(255 BYTE), 
"UNIQUE_ID" VARCHAR2(255 BYTE), 
"ENABLED" NUMBER(1,0), 
 CONSTRAINT "PK_SEARCH_PRINCIPAL" PRIMARY KEY ("ID")
 USING INDEX
 TABLESPACE "TRANSMART"  ENABLE
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ; 

