--
-- Type: TABLE; Owner: TM_WZ; Name: WRK_CLINICAL_DATA
--
 CREATE TABLE "TM_WZ"."WRK_CLINICAL_DATA" 
  (	"STUDY_ID" VARCHAR2(25 BYTE), 
"SITE_ID" VARCHAR2(50 BYTE), 
"SUBJECT_ID" VARCHAR2(30 BYTE), --postgres was 20 in oracle
"VISIT_NAME" VARCHAR2(100 BYTE), 
"DATA_LABEL" VARCHAR2(500 BYTE), 
"DATA_VALUE" VARCHAR2(500 BYTE), 
"MODIFIER_CD" VARCHAR2(100), 
"UNITS_CD" VARCHAR2(50), 
"DATE_TIMESTAMP" DATE,		--postgres
"CATEGORY_CD" VARCHAR2(250 BYTE), 
"ETL_JOB_ID" NUMBER(22,0), 
"ETL_DATE" DATE, 
"USUBJID" VARCHAR2(200 BYTE), 
"CATEGORY_PATH" VARCHAR2(1000 BYTE), 
"DATA_TYPE" VARCHAR2(10 BYTE), 
"CTRL_VOCAB_CODE" VARCHAR2(200 BYTE), 
"VISIT_DATE" VARCHAR2(200 BYTE), 
"SAMPLE_CD" VARCHAR2(200 BYTE)
  ) SEGMENT CREATION IMMEDIATE
NOCOMPRESS LOGGING
 TABLESPACE "TRANSMART" ;
