--
-- Type: TABLE; Owner: TM_WZ; Name: WRK_MRNA_DATA
--
 CREATE TABLE "TM_WZ"."WRK_MRNA_DATA" 
  (	"PROBESET" VARCHAR2(100 BYTE), 
"EXPR_ID" VARCHAR2(100 BYTE), 
"RAW_INTENSITY" VARCHAR2(50 BYTE)
  ) SEGMENT CREATION DEFERRED
 TABLESPACE "TRANSMART" ;

