--
-- Type: TABLE; Owner: TM_WZ; Name: WT_TRIAL_NODES
--
 CREATE TABLE "TM_WZ"."WT_TRIAL_NODES" 
  (	"LEAF_NODE" VARCHAR2(4000 BYTE), 
"CATEGORY_CD" VARCHAR2(200 BYTE), 
"VISIT_NAME" VARCHAR2(100 BYTE), 
"SAMPLE_TYPE" VARCHAR2(100 BYTE), 
"DATA_LABEL" VARCHAR2(500 BYTE), 
"NODE_NAME" VARCHAR2(500 BYTE), 
"DATA_VALUE" VARCHAR2(500 BYTE), 
"DATA_TYPE" VARCHAR2(20 BYTE)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;
