--
-- Type: TABLE; Owner: TM_WZ; Name: WT_TRIAL_NODES
--
 CREATE TABLE "TM_WZ"."WT_TRIAL_NODES" 
  (	"LEAF_NODE" VARCHAR2(4000 BYTE), 
"CATEGORY_CD" VARCHAR2(200 BYTE), 
"VISIT_NAME" VARCHAR2(100 BYTE), 
"SAMPLE_TYPE" VARCHAR2(100 BYTE), 
"DATA_LABEL" VARCHAR2(500 BYTE), 
"NODE_NAME" VARCHAR2(500 BYTE), 
"DATA_VALUE" VARCHAR2(500 BYTE), 
"DATA_TYPE" VARCHAR2(20 BYTE),
"DATA_LABEL_CTRL_VOCAB_CODE" VARCHAR2(500 BYTE),
"DATA_VALUE_CTRL_VOCAB_CODE" VARCHAR2(500 BYTE),
"DATA_LABEL_COMPONENTS" VARCHAR2(1000 BYTE),
"LINK_TYPE" VARCHAR2(50 BYTE),
"OBS_STRING" VARCHAR2(100 BYTE),
"VALUETYPE_CD" VARCHAR2(50 BYTE),
"REC_NUM" NUMBER(18,0)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;
