\i searchapp/prelude.sql
\i searchapp/functions/bio_clinical_trial_uid.sql
\i searchapp/functions/bio_compound_uid.sql
\i searchapp/functions/refresh_search_bio_mkr_correl_fast_mv.sql
\i searchapp/search_auth_principal.sql
\i searchapp/search_auth_user.sql
\i searchapp/search_form_layout.sql
\i searchapp/search_gene_sig_file_schema.sql
\i searchapp/search_gene_signature.sql
\i searchapp/search_gene_signature_item.sql
\i searchapp/search_keyword.sql
\i searchapp/search_required_upload_field.sql
\i searchapp/views/listsig_genes.sql
\i searchapp/plugin.sql
\i searchapp/plugin_module.sql
\i searchapp/plugin_module_backup.sql
\i searchapp/report.sql
\i searchapp/report_item.sql
\i searchapp/saved_faceted_search.sql
\i searchapp/search_app_access_log.sql
\i searchapp/search_auth_group.sql
\i searchapp/search_auth_group_member.sql
\i searchapp/search_sec_access_level.sql
\i searchapp/search_secure_object.sql
\i searchapp/search_auth_sec_object_access.sql
\i searchapp/search_auth_user_sec_access.sql
\i searchapp/views/search_auth_user_sec_access_v.sql
\i searchapp/search_bio_mkr_correl_fast_mv.sql
\i searchapp/views/search_bio_mkr_correl_fast_view.sql
\i searchapp/search_taxonomy.sql
\i searchapp/search_taxonomy_rels.sql
\i searchapp/views/search_categories.sql
\i searchapp/search_custom_filter.sql
\i searchapp/search_custom_filter_item.sql
\i searchapp/search_keyword_term.sql
\i searchapp/search_request_map.sql
\i searchapp/search_role.sql
\i searchapp/search_role_auth_user.sql
\i searchapp/search_secure_object_path.sql
\i searchapp/views/search_taxonomy_level1.sql
\i searchapp/views/search_taxonomy_level2.sql
\i searchapp/views/search_taxonomy_level3.sql
\i searchapp/views/search_taxonomy_level4.sql
\i searchapp/views/search_taxonomy_level5.sql
\i searchapp/views/search_taxonomy_lineage.sql
\i searchapp/views/search_taxonomy_terms_cats.sql
\i searchapp/search_user_feedback.sql
\i searchapp/search_user_settings.sql
\i searchapp/views/solr_keywords_lineage.sql
\i searchapp/subset.sql
\i searchapp/_misc.sql
