\ir prelude.sql
\ir functions/bio_clinical_trial_uid.sql
\ir functions/bio_compound_uid.sql
\ir functions/refresh_search_bio_mkr_correl_fast_mv.sql
\ir search_auth_principal.sql
\ir search_auth_user.sql
\ir search_gene_sig_file_schema.sql
\ir search_gene_signature.sql
\ir search_gene_signature_item.sql
\ir search_keyword.sql
\ir plugin.sql
\ir plugin_module.sql
\ir saved_faceted_search.sql
\ir search_app_access_log.sql
\ir search_auth_group.sql
\ir search_auth_group_member.sql
\ir search_sec_access_level.sql
\ir search_secure_object.sql
\ir search_auth_sec_object_access.sql
\ir search_auth_user_sec_access.sql
\ir search_bio_mkr_correl_fast_mv.sql
\ir search_taxonomy.sql
\ir search_taxonomy_rels.sql
\ir search_custom_filter.sql
\ir search_custom_filter_item.sql
\ir search_keyword_term.sql
\ir search_request_map.sql
\ir search_role.sql
\ir search_role_auth_user.sql
\ir search_secure_object_path.sql
\ir _misc.sql
