--
-- Type: TABLE; Owner: SEARCHAPP; Name: PLUGIN_MODULE_BACKUP
--
 CREATE TABLE "SEARCHAPP"."PLUGIN_MODULE_BACKUP" 
  (	"MODULE_SEQ" NUMBER NOT NULL ENABLE, 
"PLUGIN_SEQ" NUMBER NOT NULL ENABLE, 
"NAME" VARCHAR2(70 BYTE) NOT NULL ENABLE, 
"PARAMS" CLOB NOT NULL ENABLE, 
"VERSION" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
"ACTIVE" CHAR(1 BYTE) NOT NULL ENABLE, 
"HAS_FORM" CHAR(1 BYTE) NOT NULL ENABLE, 
"FORM_LINK" VARCHAR2(90 BYTE), 
"FORM_PAGE" VARCHAR2(90 BYTE), 
"MODULE_NAME" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
"CATEGORY" VARCHAR2(50 BYTE)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" 
LOB ("PARAMS") STORE AS BASICFILE (
 TABLESPACE "TRANSMART" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
 NOCACHE LOGGING ) ;

