--
-- Type: TABLE; Owner: SEARCHAPP; Name: SEARCH_REQUEST_MAP
--
 CREATE TABLE "SEARCHAPP"."SEARCH_REQUEST_MAP" 
  (	"ID" NUMBER(19,0), 
"VERSION" NUMBER(19,0), 
"CONFIG_ATTRIBUTE" VARCHAR2(255 CHAR), 
"URL" VARCHAR2(255 CHAR)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

