--
-- Type: TABLE; Owner: SEARCHAPP; Name: SEARCH_GENE_SIG_FILE_SCHEMA
--
 CREATE TABLE "SEARCHAPP"."SEARCH_GENE_SIG_FILE_SCHEMA" 
  (	"SEARCH_GENE_SIG_FILE_SCHEMA_ID" NUMBER NOT NULL ENABLE, 
"NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
"DESCRIPTION" VARCHAR2(255 BYTE), 
"NUMBER_COLUMNS" NUMBER DEFAULT 2 NOT NULL ENABLE, 
"SUPPORTED" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
 CONSTRAINT "SEARCH_GENE_SIG_FILE_SCHE_PK" PRIMARY KEY ("SEARCH_GENE_SIG_FILE_SCHEMA_ID")
 USING INDEX
 TABLESPACE "TRANSMART"  ENABLE
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

