#!/bin/bash

set -e

function get_branch {
	local branch_name=$(git symbolic-ref -q HEAD)
	branch_name=${branch_name##refs/heads/}
	branch_name=${branch_name:-HEAD}

	env | grep TRAVIS

	#travis works with a detached HEAD, and we have too look at its env vars
	if [[ $TRAVIS = true && $branch_name = 'HEAD' ]]; then
		if [[ -n "$TRAVIS_BRANCH" ]]; then
			branch_name=$(ls .git/refs/heads)
		elif [[ $TRAVIS_PULL_REQUEST != false ]]; then
			# find the remote branch that points to the second parent commit
			local t=$(git ls-remote --heads origin | grep $(git rev-parse HEAD^2))
			if [[ -n $t ]]; then
				branch_name=${t##*/}
			fi
		fi
	fi
	echo $branch_name
}

BRANCH=$(get_branch)

if [[ $BRANCH = master || $BRANCH = HEAD ]]; then
	echo "Not in any branch"
	exit 0
fi

if ! git ls-remote \
		--exit-code git://github.com/thehyve/transmart-core-api.git "$BRANCH" \
		> /dev/null; then
	echo "No branch $BRANCH in thehyve/transmart-core-api"
	exit 0
fi

git clone --depth=50 --branch="$BRANCH" \
		git://github.com/thehyve/transmart-core-api.git core-api

cd core-api
mvn install
