--
-- Type: TABLE; Owner: BIOMART_STAGE; Name: BIO_ASSAY_ANALYSIS_GWAS
--
 CREATE TABLE "BIOMART_STAGE"."BIO_ASSAY_ANALYSIS_GWAS" 
  (	"BIO_ASY_ANALYSIS_GWAS_ID" NUMBER(18,0) NOT NULL ENABLE, 
"BIO_ASSAY_ANALYSIS_ID" NUMBER(18,0) NOT NULL ENABLE, 
"RS_ID" NVARCHAR2(50), 
"P_VALUE_CHAR" VARCHAR2(100 BYTE), 
"ETL_ID" NUMBER(18,0), 
"EXT_DATA" VARCHAR2(4000 BYTE), 
"LOG10_PVAL_CHAR" VARCHAR2(100 BYTE)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

