--
-- Type: TABLE; Owner: BIOMART_STAGE; Name: BIO_ASSAY_ANALYSIS_GWAS
--
 CREATE TABLE "BIOMART_STAGE"."BIO_ASSAY_ANALYSIS_GWAS"
  (	"BIO_ASY_ANALYSIS_GWAS_ID" NUMBER(18,0) NOT NULL ENABLE,
"BIO_ASSAY_ANALYSIS_ID" NUMBER(18,0) NOT NULL ENABLE,
"RS_ID" NVARCHAR2(50),
"P_VALUE_CHAR" VARCHAR2(100 BYTE),
"ETL_ID" NUMBER(18,0),
"EXT_DATA" VARCHAR2(4000 BYTE),
"LOG10_PVAL_CHAR" VARCHAR2(100 BYTE),
"PVALUE_CHAR" VARCHAR2(100 BYTE),
"PVALUE" BINARY_DOUBLE,
"LOG_P_VAL" BINARY_DOUBLE,
"EFFECT_ALLELE" CLOB,
"OTHER_ALLELE" CLOB,
"PASS_FAIL" CHAR(1 BYTE),
"PROBE_NAME" VARCHAR2(100 BYTE),
"BIO_ASY_GENO_PLATFORM_PROBE_ID" NUMBER(22,0),
"BETA" BINARY_DOUBLE,
"STANDARD_ERROR" BINARY_DOUBLE
  ) SEGMENT CREATION IMMEDIATE
NOCOMPRESS LOGGING
 TABLESPACE "TRANSMART"
LOB ("EFFECT_ALLELE") STORE AS SECUREFILE (
 TABLESPACE "TRANSMART" ENABLE STORAGE IN ROW CHUNK 8192
 NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES )
LOB ("OTHER_ALLELE") STORE AS SECUREFILE (
 TABLESPACE "TRANSMART" ENABLE STORAGE IN ROW CHUNK 8192
 NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
