--
-- Type: VIEW; Owner: BIOMART; Name: CTD_BIOMARKER_VIEW
--
  CREATE OR REPLACE FORCE VIEW "BIOMART"."CTD_BIOMARKER_VIEW" ("ID", "REF_ARTICLE_PROTOCOL_ID", "BIOMARKER_NAME", "BIOMARKER_PCT", "BIOMARKER_VALUE") AS 
  select rownum as ID, v."REF_ARTICLE_PROTOCOL_ID",v."BIOMARKER_NAME",v."BIOMARKER_PCT",v."BIOMARKER_VALUE"
from 
(
select distinct REF_ARTICLE_PROTOCOL_ID,
			BIOMARKER_NAME,
			BIOMARKER_PCT,
			BIOMARKER_VALUE
from ctd_full
where BIOMARKER_NAME is not null
order by REF_ARTICLE_PROTOCOL_ID, BIOMARKER_NAME
) v
 
 
 
 
 
;
 
