--
-- Type: TABLE; Owner: DEAPP; Name: DE_METABOLITE_SUB_PWAY_METAB
--
 CREATE TABLE "DEAPP"."DE_METABOLITE_SUB_PWAY_METAB" 
  (	"METABOLITE_ID" NUMBER(*,0) NOT NULL ENABLE, 
"SUB_PATHWAY_ID" NUMBER(*,0) NOT NULL ENABLE
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

--
-- Type: REF_CONSTRAINT; Owner: DEAPP; Name: DE_MET_SUB_PW_MET_MET_ID_FK
--
ALTER TABLE "DEAPP"."DE_METABOLITE_SUB_PWAY_METAB" ADD CONSTRAINT "DE_MET_SUB_PW_MET_MET_ID_FK" FOREIGN KEY ("METABOLITE_ID")
 REFERENCES "DEAPP"."DE_METABOLITE_ANNOTATION" ("ID") ENABLE;

--
-- Type: REF_CONSTRAINT; Owner: DEAPP; Name: DE_MET_SUB_PW_MET_SUB_PW_ID_FK
--
ALTER TABLE "DEAPP"."DE_METABOLITE_SUB_PWAY_METAB" ADD CONSTRAINT "DE_MET_SUB_PW_MET_SUB_PW_ID_FK" FOREIGN KEY ("SUB_PATHWAY_ID")
 REFERENCES "DEAPP"."DE_METABOLITE_SUB_PATHWAYS" ("ID") ENABLE;

