--
-- Type: TABLE; Owner: DEAPP; Name: DE_QPCR_MIRNA_ANNOTATION
--
 CREATE TABLE "DEAPP"."DE_QPCR_MIRNA_ANNOTATION"
  (	"ID_REF" VARCHAR2(100 BYTE),
"PROBE_ID" VARCHAR2(100 BYTE),
"MIRNA_SYMBOL" VARCHAR2(100 BYTE),
"MIRNA_ID" VARCHAR2(100 BYTE),
"PROBESET_ID" NUMBER(38,0),
"ORGANISM" VARCHAR2(200 BYTE),
"GPL_ID" VARCHAR2(20 BYTE),
 PRIMARY KEY ("PROBESET_ID")
 USING INDEX
 TABLESPACE "TRANSMART"  ENABLE
  ) SEGMENT CREATION IMMEDIATE
NOCOMPRESS LOGGING
 TABLESPACE "TRANSMART" ;
