--
-- Type: TABLE; Owner: DEAPP; Name: DE_RBM_DATA_ANNOTATION_JOIN
--
 CREATE TABLE "DEAPP"."DE_RBM_DATA_ANNOTATION_JOIN" 
  (	"DATA_ID" NUMBER(38,0) NOT NULL ENABLE, 
"ANNOTATION_ID" NUMBER(38,0) NOT NULL ENABLE, 
 CONSTRAINT "PK_DE_RBM_DATA_ANNOTATION_JOIN" PRIMARY KEY ("DATA_ID", "ANNOTATION_ID")
 USING INDEX
 TABLESPACE "TRANSMART"  ENABLE
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

--
-- Type: REF_CONSTRAINT; Owner: DEAPP; Name: DE_RBM_DATA_ANN_JN_ANN_ID_FK
--
ALTER TABLE "DEAPP"."DE_RBM_DATA_ANNOTATION_JOIN" ADD CONSTRAINT "DE_RBM_DATA_ANN_JN_ANN_ID_FK" FOREIGN KEY ("ANNOTATION_ID")
 REFERENCES "DEAPP"."DE_RBM_ANNOTATION" ("ID") ON DELETE CASCADE ENABLE;

--
-- Type: REF_CONSTRAINT; Owner: DEAPP; Name: DE_RBM_DATA_ANN_JN_DATA_ID_FK
--
ALTER TABLE "DEAPP"."DE_RBM_DATA_ANNOTATION_JOIN" ADD CONSTRAINT "DE_RBM_DATA_ANN_JN_DATA_ID_FK" FOREIGN KEY ("DATA_ID")
 REFERENCES "DEAPP"."DE_SUBJECT_RBM_DATA" ("ID") ON DELETE CASCADE ENABLE;

