--
-- Type: SEQUENCE; Owner: DEAPP; Name: DE_RC_SNP_INFO_SEQ
--
CREATE SEQUENCE  "DEAPP"."DE_RC_SNP_INFO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOPARTITION ;
--
-- Type: TABLE; Owner: DEAPP; Name: DE_RC_SNP_INFO
--
 CREATE TABLE "DEAPP"."DE_RC_SNP_INFO"
  (	"SNP_INFO_ID" NUMBER NOT NULL ENABLE,
"RS_ID" VARCHAR2(50 BYTE),
"CHROM" VARCHAR2(4 BYTE),
"POS" NUMBER,
"REF" VARCHAR2(1000 BYTE),
"ALT" VARCHAR2(1000 BYTE),
"GENE_INFO" VARCHAR2(1000 BYTE),
"VARIATION_CLASS" VARCHAR2(10 BYTE),
"STRAND" VARCHAR2(1 BYTE),
"CLINSIG" VARCHAR2(100 BYTE),
"DISEASE" VARCHAR2(500 BYTE),
"GMAF" VARCHAR2(10 BYTE),
"GENE_BIOTYPE" VARCHAR2(100 BYTE),
"IMPACT" VARCHAR2(50 BYTE),
"TRANSCRIPT_ID" VARCHAR2(100 BYTE),
"FUNCTIONAL_CLASS" VARCHAR2(100 BYTE),
"EFFECT" VARCHAR2(100 BYTE),
"EXON_ID" VARCHAR2(100 BYTE),
"AMINO_ACID_CHANGE" VARCHAR2(100 BYTE),
"CODON_CHANGE" VARCHAR2(1000 BYTE),
"HG_VERSION" VARCHAR2(10 BYTE),
"GENE_NAME" VARCHAR2(50 BYTE),
"ENTREZ_ID" VARCHAR2(50 BYTE),
"RECOMBINATION_RATE" NUMBER(18,6),
"RECOMBINATION_MAP" NUMBER(18,6),
"REGULOME_SCORE" VARCHAR2(10 BYTE),
"EXON_INTRON" VARCHAR2(10 BYTE)
  ) SEGMENT CREATION IMMEDIATE
NOCOMPRESS LOGGING
 TABLESPACE "TRANSMART" ;
--
-- Type: TRIGGER; Owner: DEAPP; Name: TRG_DE_RC_SNP_INFO_ID
--
  CREATE OR REPLACE TRIGGER "DEAPP"."TRG_DE_RC_SNP_INFO_ID"
before insert on "DEAPP"."DE_RC_SNP_INFO"
for each row begin
       	if inserting then
               	if :NEW."SNP_INFO_ID" is null then
                       	select DE_RC_SNP_INFO_SEQ.nextval into :NEW."SNP_INFO_ID" from dual;
               	end if;
       	end if;
end;
/
ALTER TRIGGER "DEAPP"."TRG_DE_RC_SNP_INFO_ID" ENABLE;
--
-- Type: INDEX; Owner: DEAPP; Name: DE_R_S_I_IND4
--
CREATE INDEX "DEAPP"."DE_R_S_I_IND4" ON "DEAPP"."DE_RC_SNP_INFO" ("SNP_INFO_ID")
TABLESPACE "TRANSMART" ;
--
-- Type: INDEX; Owner: DEAPP; Name: DE_RSNP_CHROM_COMP_IDX
--
CREATE INDEX "DEAPP"."DE_RSNP_CHROM_COMP_IDX" ON "DEAPP"."DE_RC_SNP_INFO" ("CHROM", "HG_VERSION", "POS")
TABLESPACE "TRANSMART" ;
--
-- Type: INDEX; Owner: DEAPP; Name: DE_RSNP_CHROMPOS_IND
--
CREATE INDEX "DEAPP"."DE_RSNP_CHROMPOS_IND" ON "DEAPP"."DE_RC_SNP_INFO" ("CHROM", "POS")
TABLESPACE "TRANSMART" ;
--
-- Type: INDEX; Owner: DEAPP; Name: IND_VCF_RSID
--
CREATE INDEX "DEAPP"."IND_VCF_RSID" ON "DEAPP"."DE_RC_SNP_INFO" ("RS_ID")
TABLESPACE "TRANSMART" ;
--
-- Type: INDEX; Owner: DEAPP; Name: IND_VCF_POS
--
CREATE INDEX "DEAPP"."IND_VCF_POS" ON "DEAPP"."DE_RC_SNP_INFO" ("POS")
TABLESPACE "TRANSMART" ;
--
-- Type: INDEX; Owner: DEAPP; Name: DE_RSNP_HGRS_IND
--
CREATE UNIQUE INDEX DEAPP.DE_RSNP_HGRS_IND ON DEAPP.DE_RC_SNP_INFO
(HG_VERSION, RS_ID)
TABLESPACE "TRANSMART" ;
