--
-- Type: TABLE; Owner: DEAPP; Name: DE_SNP_CALLS_BY_GSM
--
 CREATE TABLE "DEAPP"."DE_SNP_CALLS_BY_GSM" 
  (	"TRIAL_NAME" VARCHAR2(20 BYTE), 
"GSM_NUM" VARCHAR2(100 BYTE), 
"PATIENT_NUM" NUMBER(20,0), 
"SNP_NAME" VARCHAR2(100 BYTE), 
"SNP_CALLS" VARCHAR2(4 BYTE)
  )
 TABLESPACE "TRANSMART" 
 PARTITION BY LIST ("PATIENT_NUM") 
(PARTITION "NULL_PARTITION" VALUES (NULL)
 TABLESPACE "TRANSMART" 
NOCOMPRESS ) ;
--
-- Type: INDEX; Owner: DEAPP; Name: IDX_SNP_CALLS_BY_GSM_PG
--
 CREATE INDEX "DEAPP"."IDX_SNP_CALLS_BY_GSM_PG" ON "DEAPP"."DE_SNP_CALLS_BY_GSM" ("PATIENT_NUM", "GSM_NUM") 
 LOCAL
(PARTITION "SYS_P388" 
 TABLESPACE "TRANSMART" ) ;
