--
-- Type: TABLE; Owner: DEAPP; Name: DE_SUBJECT_MICROARRAY_DATA
--
 CREATE TABLE "DEAPP"."DE_SUBJECT_MICROARRAY_DATA"
  (	"TRIAL_NAME" VARCHAR2(50 BYTE),
"PROBESET_ID" NUMBER(22,0),
"ASSAY_ID" NUMBER(18,0),
"PATIENT_ID" NUMBER(18,0),
"SAMPLE_ID" NUMBER(18,0),
"SUBJECT_ID" VARCHAR2(50 BYTE),
"RAW_INTENSITY" NUMBER(30,4),
"LOG_INTENSITY" NUMBER(18,4),
"ZSCORE" NUMBER(18,4),
"NEW_RAW" NUMBER(18,4),
"NEW_LOG" NUMBER(18,4),
"NEW_ZSCORE" NUMBER(18,4),
"TRIAL_SOURCE" VARCHAR2(200 BYTE),
"PARTITION_ID" NUMBER(18,0),
 CONSTRAINT "DE_SUBJECT_MICROARRAY_DATA_PK" PRIMARY KEY ("ASSAY_ID", "PROBESET_ID")
 USING INDEX
 TABLESPACE "TRANSMART"  ENABLE
  ) SEGMENT CREATION IMMEDIATE
NOCOMPRESS LOGGING
 TABLESPACE "TRANSMART" ;
