--
-- Type: TABLE; Owner: DEAPP; Name: DE_SAMPLE_SNP_DATA
--
 CREATE TABLE "DEAPP"."DE_SAMPLE_SNP_DATA" 
  (	"SAMPLE_ID" VARCHAR2(50 BYTE), 
"SNP_NAME" VARCHAR2(100 BYTE), 
"SNP_CALLS" VARCHAR2(4 BYTE), 
"COPY_NUMBER" NUMBER(10,6)
  ) SEGMENT CREATION DEFERRED
 TABLESPACE "TRANSMART" ;

--
-- Type: INDEX; Owner: DEAPP; Name: IDX_DE_SAMPLE_SNP_DATA_SAMPLE
--
CREATE INDEX "DEAPP"."IDX_DE_SAMPLE_SNP_DATA_SAMPLE" ON "DEAPP"."DE_SAMPLE_SNP_DATA" ("SAMPLE_ID")
TABLESPACE "TRANSMART" ;

--
-- Type: INDEX; Owner: DEAPP; Name: IDX_DE_SAMPLE_SNP_DATA_SNP
--
CREATE INDEX "DEAPP"."IDX_DE_SAMPLE_SNP_DATA_SNP" ON "DEAPP"."DE_SAMPLE_SNP_DATA" ("SNP_NAME")
TABLESPACE "TRANSMART" ;

