--
-- Type: TABLE; Owner: DEAPP; Name: DE_SNP_DATA_BY_PROBE
--
 CREATE TABLE "DEAPP"."DE_SNP_DATA_BY_PROBE"
  (	"SNP_DATA_BY_PROBE_ID" NUMBER(22,0) NOT NULL ENABLE,
"PROBE_ID" NUMBER(22,0),
"PROBE_NAME" VARCHAR2(255 BYTE),
"SNP_ID" NUMBER(22,0),
"SNP_NAME" VARCHAR2(255 BYTE),
"TRIAL_NAME" VARCHAR2(255 BYTE),
"DATA_BY_PROBE" CLOB,
"BIO_ASY_GENO_PLATFORM_PROBE_ID" NUMBER(22,0),
"GENOTYPE_PROBE_ANNOTATION_ID" NUMBER(22,0),
"A1" VARCHAR2(4000 CHAR),
"A2" VARCHAR2(4000 CHAR),
"A1_CLOB" CLOB,
"A2_CLOB" CLOB,
"IMPUTE_QUALITY" NUMBER,
"GPS_BY_PROBE_BLOB" BLOB,
"GTS_BY_PROBE_BLOB" BLOB,
"DOSE_BY_PROBE_BLOB" BLOB,
"GT_PROBABILITY_THRESHOLD" NUMBER,
"MAF" NUMBER,
"MINOR_ALLELE" VARCHAR2(2 BYTE),
"C_A1_A1" NUMBER(10,0),
"C_A1_A2" NUMBER(10,0),
"C_A2_A2" NUMBER(10,0),
"C_NOCALL" NUMBER(10,0),
"CREATED_BY" VARCHAR2(30 BYTE),
"CREATED_DATE" DATE,
"MODIFIED_BY" VARCHAR2(30 BYTE),
"MODIFIED_DATE" DATE,
 PRIMARY KEY ("SNP_DATA_BY_PROBE_ID")
 USING INDEX
 TABLESPACE "TRANSMART"  ENABLE
  ) SEGMENT CREATION IMMEDIATE
NOCOMPRESS LOGGING
 TABLESPACE "TRANSMART"
LOB ("DATA_BY_PROBE") STORE AS BASICFILE (
 TABLESPACE "TRANSMART" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION
 NOCACHE NOLOGGING )
LOB ("A1_CLOB") STORE AS SECUREFILE (
 TABLESPACE "TRANSMART" ENABLE STORAGE IN ROW CHUNK 8192
 NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES )
LOB ("A2_CLOB") STORE AS SECUREFILE (
 TABLESPACE "TRANSMART" ENABLE STORAGE IN ROW CHUNK 8192
 NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES )
LOB ("GPS_BY_PROBE_BLOB") STORE AS SECUREFILE (
 TABLESPACE "TRANSMART" ENABLE STORAGE IN ROW CHUNK 8192
 NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES )
LOB ("GTS_BY_PROBE_BLOB") STORE AS SECUREFILE (
 TABLESPACE "TRANSMART" ENABLE STORAGE IN ROW CHUNK 8192
 NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES )
LOB ("DOSE_BY_PROBE_BLOB") STORE AS SECUREFILE (
 TABLESPACE "TRANSMART" ENABLE STORAGE IN ROW CHUNK 8192
 NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
--
-- Type: INDEX; Owner: DEAPP; Name: IDX_DSDBP1_GP_PROBE_ID
--
CREATE INDEX "DEAPP"."IDX_DSDBP1_GP_PROBE_ID" ON "DEAPP"."DE_SNP_DATA_BY_PROBE" ("BIO_ASY_GENO_PLATFORM_PROBE_ID")
TABLESPACE "TRANSMART" ;
--
-- Type: TRIGGER; Owner: DEAPP; Name: TRG_SNP_DATA_BY_PPROBE_ID
--
  CREATE OR REPLACE TRIGGER "DEAPP"."TRG_SNP_DATA_BY_PPROBE_ID"
   BEFORE INSERT
   ON DEAPP.DE_SNP_DATA_BY_PROBE
   FOR EACH ROW
BEGIN
   IF INSERTING
   THEN
      IF :NEW.SNP_DATA_BY_PROBE_ID IS NULL
      THEN
         SELECT SEQ_DATA_ID.NEXTVAL INTO :NEW.SNP_DATA_BY_PROBE_ID FROM DUAL;
      END IF;
   END IF;
END;
/
ALTER TRIGGER "DEAPP"."TRG_SNP_DATA_BY_PPROBE_ID" ENABLE;
--
-- Type: INDEX; Owner: DEAPP; Name: IDX_DSDBP1_ANNO_ID
--
CREATE INDEX "DEAPP"."IDX_DSDBP1_ANNO_ID" ON "DEAPP"."DE_SNP_DATA_BY_PROBE" ("GENOTYPE_PROBE_ANNOTATION_ID")
TABLESPACE "TRANSMART" ;
--
-- Type: REF_CONSTRAINT; Owner: DEAPP; Name: FK_SNP_BY_PROBE_PROBE_ID
--
ALTER TABLE "DEAPP"."DE_SNP_DATA_BY_PROBE" ADD CONSTRAINT "FK_SNP_BY_PROBE_PROBE_ID" FOREIGN KEY ("PROBE_ID")
 REFERENCES "DEAPP"."DE_SNP_PROBE" ("SNP_PROBE_ID") ENABLE;
--
-- Type: REF_CONSTRAINT; Owner: DEAPP; Name: FK_SNP_BY_PROBE_SNP_ID
--
ALTER TABLE "DEAPP"."DE_SNP_DATA_BY_PROBE" ADD CONSTRAINT "FK_SNP_BY_PROBE_SNP_ID" FOREIGN KEY ("SNP_ID")
 REFERENCES "DEAPP"."DE_SNP_INFO" ("SNP_INFO_ID") ENABLE;
--
-- Type: INDEX; Owner: DEAPP; Name: IDX_DSDBP_TRIAL_NAME
--
CREATE BITMAP INDEX "DEAPP"."IDX_DSDBP_TRIAL_NAME" ON "DEAPP"."DE_SNP_DATA_BY_PROBE" ("TRIAL_NAME")
TABLESPACE "TRANSMART" ;
--
-- Type: TRIGGER; Owner: DEAPP; Name: TRG_SNP_DATA_BY_PROBE_ID
--
  CREATE OR REPLACE TRIGGER "DEAPP"."TRG_SNP_DATA_BY_PROBE_ID"
before insert on DE_SNP_DATA_BY_PROBE
for each row
begin
   if inserting then
      if :NEW.SNP_DATA_BY_PROBE_ID is null then
         select SEQ_DATA_ID.nextval into :NEW.SNP_DATA_BY_PROBE_ID from dual;
      end if;
  end if;
end;

/
ALTER TRIGGER "DEAPP"."TRG_SNP_DATA_BY_PROBE_ID" ENABLE;
