--
-- Type: TABLE; Owner: DEAPP; Name: DEAPP_ANNOTATION
--
 CREATE TABLE "DEAPP"."DEAPP_ANNOTATION" 
  (	"ANNOTATION_TYPE" VARCHAR2(50 BYTE), 
"ANNOTATION_VALUE" VARCHAR2(100 BYTE), 
"GENE_ID" NUMBER, 
"GENE_SYMBOL" VARCHAR2(200 BYTE)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

