--
-- Type: TABLE; Owner: DEAPP; Name: GPL3718_20_MAP
--
 CREATE TABLE "DEAPP"."GPL3718_20_MAP" 
  (	"SNP_ID" VARCHAR2(50 BYTE), 
"ORGANISM" VARCHAR2(20 BYTE), 
"GENE_ID" VARCHAR2(20 BYTE), 
"GENE_NAME" VARCHAR2(100 BYTE), 
"GENE_DESCR" VARCHAR2(500 BYTE)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

