--
-- Type: TABLE; Owner: DEAPP; Name: GPL3718_20
--
 CREATE TABLE "DEAPP"."GPL3718_20" 
  (	"SNP_ID" VARCHAR2(20 BYTE), 
"RS_ID" VARCHAR2(20 BYTE), 
"CHROM" VARCHAR2(2 BYTE), 
"POS" VARCHAR2(9 BYTE)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

