--
-- Type: TABLE; Owner: DEAPP; Name: KEGG_DEF
--
 CREATE TABLE "DEAPP"."KEGG_DEF" 
  (	"PATHWAY" VARCHAR2(100 BYTE), 
"DESCR" VARCHAR2(500 BYTE)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

