--
-- Type: TABLE; Owner: DEAPP; Name: RICERCA
--
 CREATE TABLE "DEAPP"."RICERCA" 
  (	"SUBJECT_ID" VARCHAR2(20 BYTE), 
"SAMPLE_ID" VARCHAR2(100 BYTE)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

