CREATE SEQUENCE BIOMART.SEQ_ANNOTATION_ID;

CREATE SEQUENCE BIOMART.SEQ_BIO_ASY_PPA;

CREATE SEQUENCE BIOMART.SEQ_GENO_PLATFORM_PROBE_ID;

ALTER TABLE BIOMART.BIO_ASY_ANALYSIS_EQTL_TOP50
 ADD (GENE  VARCHAR2(50 BYTE));

ALTER TABLE BIOMART.BIO_ASY_ANALYSIS_EQTL_TOP50
 ADD (PVALUE_CHAR  VARCHAR2(100 BYTE));

ALTER TABLE BIOMART.BIO_ASY_ANALYSIS_EQTL_TOP50
 ADD (STRAND  VARCHAR2(1 BYTE));

ALTER TABLE BIOMART.BIO_ASSAY_PLATFORM
 ADD (PLATFORM_IMPUTED_ALGORITHM  VARCHAR2(500 BYTE));

ALTER TABLE BIOMART.BIO_ASSAY_PLATFORM
 ADD (PLATFORM_IMPUTED_PANEL  VARCHAR2(200 BYTE));

ALTER TABLE BIOMART.BIO_ASSAY_PLATFORM
 ADD (PLATFORM_IMPUTED  CHAR(1 BYTE));

ALTER TABLE BIOMART.BIO_ASSAY_PLATFORM
 ADD (CREATED_BY  VARCHAR2(30 BYTE));

ALTER TABLE BIOMART.BIO_ASSAY_PLATFORM
 ADD (CREATED_DATE  DATE);

ALTER TABLE BIOMART.BIO_ASSAY_PLATFORM
 ADD (MODIFIED_BY  VARCHAR2(30 BYTE));

ALTER TABLE BIOMART.BIO_ASSAY_PLATFORM
 ADD (MODIFIED_DATE  DATE);

CREATE TABLE BIOMART.GENOTYPE_PROBE_ANNOTATION
(
  GENOTYPE_PROBE_ANNOTATION_ID  NUMBER(22)      NOT NULL,
  SNP_NAME                      VARCHAR2(50 BYTE),
  CHROM                         VARCHAR2(4 BYTE),
  POS                           NUMBER,
  REF                           VARCHAR2(4000 BYTE),
  ALT                           VARCHAR2(4000 BYTE),
  GENE_INFO                     VARCHAR2(4000 BYTE),
  VARIATION_CLASS               VARCHAR2(10 BYTE),
  STRAND                        VARCHAR2(1 BYTE),
  EXON_INTRON                   VARCHAR2(30 BYTE),
  GENOME_BUILD                  VARCHAR2(10 BYTE),
  SNP_SOURCE                    VARCHAR2(10 BYTE),
  RECOMBINATION_RATE            NUMBER(18,6),
  RECOMBINATION_MAP             NUMBER(18,6),
  REGULOME_SCORE                VARCHAR2(10 BYTE),
  REF_CLOB                      CLOB,
  ALT_CLOB                      CLOB,
  CREATED_BY                    VARCHAR2(30 BYTE),
  CREATED_DATE                  DATE,
  MODIFIED_BY                   VARCHAR2(30 BYTE),
  MODIFIED_DATE                 DATE
);

CREATE INDEX BIOMART.IDX_PROBE_ANNO_SNP ON BIOMART.GENOTYPE_PROBE_ANNOTATION
(SNP_NAME);

CREATE INDEX BIOMART.IDX_GENO_ANNO_LOC ON BIOMART.GENOTYPE_PROBE_ANNOTATION
(CHROM, POS);

CREATE UNIQUE INDEX BIOMART.PK_GENO_PROBE_ANNOTATION ON BIOMART.GENOTYPE_PROBE_ANNOTATION
(GENOTYPE_PROBE_ANNOTATION_ID);

ALTER TABLE BIOMART.GENOTYPE_PROBE_ANNOTATION
 ADD CONSTRAINT PK_GENO_PROBE_ANNOTATION
  PRIMARY KEY
  (GENOTYPE_PROBE_ANNOTATION_ID)
  USING INDEX BIOMART.PK_GENO_PROBE_ANNOTATION;

CREATE TABLE BIOMART.BIO_ASSAY_GENO_PLATFORM_PROBE
(
  BIO_ASY_GENO_PLATFORM_PROBE_ID  NUMBER(18)    NOT NULL,
  BIO_ASSAY_PLATFORM_ID           NUMBER(18)    NOT NULL,
  ORIG_CHROM                      VARCHAR2(5 BYTE),
  ORIG_POSITION                   NUMBER,
  ORIG_GENOME_BUILD               VARCHAR2(20 BYTE),
  PROBE_NAME                      VARCHAR2(200 BYTE),
  IS_CONTROL                      CHAR(1 BYTE),
  CREATED_BY                      VARCHAR2(30 BYTE),
  CREATED_DATE                    DATE,
  MODIFIED_BY                     VARCHAR2(30 BYTE),
  MODIFIED_DATE                   DATE
);

CREATE INDEX BIOMART.IDX_BIO_ASY_GPP_PROBE_NAME ON BIOMART.BIO_ASSAY_GENO_PLATFORM_PROBE
(PROBE_NAME);

CREATE INDEX BIOMART.IDX_BIO_ASY_GPP_PLATFORM ON BIOMART.BIO_ASSAY_GENO_PLATFORM_PROBE
(BIO_ASSAY_PLATFORM_ID);

CREATE UNIQUE INDEX BIOMART.IDX_BIO_ASSAY_GP_PROBE_PK ON BIOMART.BIO_ASSAY_GENO_PLATFORM_PROBE
(BIO_ASY_GENO_PLATFORM_PROBE_ID);

ALTER TABLE BIOMART.BIO_ASSAY_GENO_PLATFORM_PROBE
 ADD CONSTRAINT PK_BIO_ASY_GP_PROBE
  PRIMARY KEY
  (BIO_ASY_GENO_PLATFORM_PROBE_ID)
  USING INDEX BIOMART.IDX_BIO_ASSAY_GP_PROBE_PK;

CREATE INDEX BIOMART.BIO_MKR_SRC_EXT_ID_IDX ON BIOMART.BIO_MARKER
(PRIMARY_SOURCE_CODE, PRIMARY_EXTERNAL_ID);

CREATE INDEX BIOMART.B_ASY_EQTL_T50_IDX1 ON BIOMART.BIO_ASY_ANALYSIS_EQTL_TOP50
(BIO_ASSAY_ANALYSIS_ID);

CREATE INDEX BIOMART.IDX_BIO_RECOMB_1 ON BIOMART.BIO_RECOMBINATION_RATES
(POSITION, CHROMOSOME);

CREATE UNIQUE INDEX BIOMART.BIO_DATA_PLATFORM_PK ON BIOMART.BIO_DATA_PLATFORM
(BIO_DATA_ID, BIO_ASSAY_PLATFORM_ID);

CREATE UNIQUE INDEX BIOMART.BIO_DATA_OBSERVATION_PK ON BIOMART.BIO_DATA_OBSERVATION
(BIO_DATA_ID, BIO_OBSERVATION_ID);

CREATE UNIQUE INDEX BIOMART.BIO_ASSAY_ANALYSIS_EQTL_PK ON BIOMART.BIO_ASSAY_ANALYSIS_EQTL
(BIO_ASY_ANALYSIS_EQTL_ID);

CREATE UNIQUE INDEX BIOMART.BIO_D_O_M_MARKER2_PK ON BIOMART.BIO_DATA_OMIC_MARKER
(BIO_MARKER_ID, BIO_DATA_ID);

CREATE UNIQUE INDEX BIOMART.BIO_D_FG_M_MARKER2_PK ON BIOMART.BIO_ASSAY_DATA_ANNOTATION
(BIO_MARKER_ID, BIO_ASSAY_FEATURE_GROUP_ID);

CREATE OR REPLACE TRIGGER BIOMART.TRG_ANNOTATION_ID
   BEFORE INSERT
   ON BIOMART.GENOTYPE_PROBE_ANNOTATION
   FOR EACH ROW
BEGIN
   IF INSERTING
   THEN
      IF :NEW.GENOTYPE_PROBE_ANNOTATION_ID IS NULL
      THEN
         SELECT SEQ_ANNOTATION_ID.NEXTVAL
           INTO :NEW.GENOTYPE_PROBE_ANNOTATION_ID
           FROM DUAL;
      END IF;
   END IF;
END;
/

CREATE OR REPLACE TRIGGER BIOMART.TRG_GENO_PLATFORM_PROBE_ID
   BEFORE INSERT
   ON "BIOMART"."BIO_ASSAY_GENO_PLATFORM_PROBE"
   FOR EACH ROW
BEGIN
   IF INSERTING
   THEN
      IF :NEW."BIO_ASY_GENO_PLATFORM_PROBE_ID" IS NULL
      THEN
         SELECT BIOMART.SEQ_GENO_PLATFORM_PROBE_ID.NEXTVAL
           INTO :NEW."BIO_ASY_GENO_PLATFORM_PROBE_ID"
           FROM DUAL;
      END IF;
   END IF;
END;
/

ALTER TABLE BIOMART.BIO_ASSAY_ANALYSIS
 ADD (UPDATE_OF  NUMBER(18));

ALTER TABLE BIOMART.BIO_ASSAY_ANALYSIS
 ADD (CREATED_BY  VARCHAR2(30 BYTE));

ALTER TABLE BIOMART.BIO_ASSAY_ANALYSIS
 ADD (MODIFIED_BY  VARCHAR2(30 BYTE));

CREATE TABLE BIOMART.BIO_ASY_PLATFORM_PROBE_ANNO
(
  BIO_ASY_PLATFORM_PROBE_ANNO_ID  NUMBER(22)    NOT NULL,
  BIO_ASY_GENO_PLATFORM_PROBE_ID  NUMBER(22)    NOT NULL,
  GENOTYPE_PROBE_ANNOTATION_ID    NUMBER(22)    NOT NULL,
  BIO_ASSAY_PLATFORM_ID           NUMBER(18)    NOT NULL,
  GENOME_BUILD                    VARCHAR2(10 BYTE),
  CREATED_BY                      VARCHAR2(30 BYTE),
  CREATED_DATE                    DATE,
  MODIFIED_BY                     VARCHAR2(30 BYTE),
  MODIFIED_DATE                   DATE
);

CREATE UNIQUE INDEX BIOMART.PK_BIO_ASY_PLATFORM_PROBE_ANNO ON BIOMART.BIO_ASY_PLATFORM_PROBE_ANNO
(BIO_ASY_PLATFORM_PROBE_ANNO_ID);

CREATE INDEX BIOMART.IDX_BIO_ASY_PPANNO_PROBE ON BIOMART.BIO_ASY_PLATFORM_PROBE_ANNO
(BIO_ASY_GENO_PLATFORM_PROBE_ID);

CREATE INDEX BIOMART.IDX_BIO_ASY_PPANNO_PLATFORM ON BIOMART.BIO_ASY_PLATFORM_PROBE_ANNO
(BIO_ASSAY_PLATFORM_ID);

CREATE INDEX BIOMART.IDX_BIO_ASY_PPANNO_ANNO ON BIOMART.BIO_ASY_PLATFORM_PROBE_ANNO
(GENOTYPE_PROBE_ANNOTATION_ID);

ALTER TABLE BIOMART.BIO_ASY_PLATFORM_PROBE_ANNO
 ADD CONSTRAINT PK_BIO_ASY_PLATFORM_PROBE_ANNO
  PRIMARY KEY
  (BIO_ASY_PLATFORM_PROBE_ANNO_ID)
  USING INDEX BIOMART.PK_BIO_ASY_PLATFORM_PROBE_ANNO;

ALTER TABLE BIOMART.BIO_ASSAY_ANALYSIS_GWAS
 ADD (GENO_PLATFORM_PROBE_ID  NUMBER(22));

ALTER TABLE BIOMART.BIO_ASSAY_ANALYSIS_GWAS
 ADD (BETA_OLD  NUMBER);

ALTER TABLE BIOMART.BIO_ASSAY_ANALYSIS_GWAS
 ADD (STANDARD_ERROR_OLD  NUMBER);

ALTER TABLE BIOMART.BIO_ASSAY_ANALYSIS_GWAS
 ADD (EFFECT_ALLELE_CLOB  CLOB);

ALTER TABLE BIOMART.BIO_ASSAY_ANALYSIS_GWAS
 ADD (OTHER_ALLELE_CLOB  CLOB);

ALTER TABLE BIOMART.BIO_ASSAY_ANALYSIS_GWAS
 ADD (CREATED_BY  VARCHAR2(30 BYTE));

ALTER TABLE BIOMART.BIO_ASSAY_ANALYSIS_GWAS
 ADD (CREATED_DATE  DATE);

ALTER TABLE BIOMART.BIO_ASSAY_ANALYSIS_GWAS
 ADD (MODIFIED_BY  VARCHAR2(30 BYTE));

ALTER TABLE BIOMART.BIO_ASSAY_ANALYSIS_GWAS
 ADD (MODIFIED_DATE  DATE);

CREATE INDEX BIOMART.IDX_GWAS_GENO_PLTFM_PROBE_ID ON BIOMART.BIO_ASSAY_ANALYSIS_GWAS
(GENO_PLATFORM_PROBE_ID);

CREATE UNIQUE INDEX BIOMART.IDX3_BIO_ASSAY_ANALYSIS_GWAS ON BIOMART.BIO_ASSAY_ANALYSIS_GWAS
(BIO_ASSAY_ANALYSIS_ID, RS_ID);

CREATE INDEX BIOMART.IDX2_BIO_ASSAY_ANALYSIS_GWAS ON BIOMART.BIO_ASSAY_ANALYSIS_GWAS
(RS_ID);

CREATE INDEX BIOMART.BIO_MARKER_CORREL_MV_ABM_IDX ON BIOMART.BIO_MARKER_CORREL_MV
(ASSO_BIO_MARKER_ID);

CREATE OR REPLACE TRIGGER BIOMART.TRG_BIO_ASY_PPA
   BEFORE INSERT
   ON BIOMART.BIO_ASY_PLATFORM_PROBE_ANNO
   FOR EACH ROW
BEGIN
   IF INSERTING
   THEN
      IF :NEW."BIO_ASY_PLATFORM_PROBE_ANNO_ID" IS NULL
      THEN
         SELECT BIOMART.SEQ_BIO_ASY_PPA.NEXTVAL
           INTO :NEW."BIO_ASY_PLATFORM_PROBE_ANNO_ID"
           FROM DUAL;
      END IF;
   END IF;
END;
/

ALTER TABLE BIOMART.BIO_ASSAY_ANALYSIS_EXT
 ADD (PERCENT_MALE  NUMBER);

ALTER TABLE BIOMART.BIO_ASSAY_ANALYSIS_EXT
 ADD (EFFECT_TYPE  VARCHAR2(100 BYTE));

ALTER TABLE BIOMART.BIO_ASSAY_ANALYSIS_EXT
 ADD (EFFECT_UNITS  VARCHAR2(100 BYTE));

ALTER TABLE BIOMART.BIO_ASSAY_ANALYSIS_EXT
 ADD (EFFECT_ERROR1_TYPE  VARCHAR2(100 BYTE));

ALTER TABLE BIOMART.BIO_ASSAY_ANALYSIS_EXT
 ADD (EFFECT_ERROR2_TYPE  VARCHAR2(100 BYTE));

ALTER TABLE BIOMART.BIO_ASSAY_ANALYSIS_EXT
 ADD (EFFECT_ERROR_DESC  VARCHAR2(1000 BYTE));

ALTER TABLE BIOMART.BIO_ASSAY_ANALYSIS_EXT
 ADD (TRAIT  VARCHAR2(255 BYTE));

ALTER TABLE BIOMART.BIO_ASSAY_ANALYSIS_EXT
 ADD (REQUESTOR  VARCHAR2(100 BYTE));

ALTER TABLE BIOMART.BIO_ASSAY_ANALYSIS_EXT
 ADD (DATA_OWNER  VARCHAR2(100 BYTE));

ALTER TABLE BIOMART.BIO_ASSAY_ANALYSIS_EXT
 ADD (SD_TRAIT_POPULATION  NUMBER);

CREATE UNIQUE INDEX BIOMART.PK_BAAD ON BIOMART.BIO_ASSAY_ANALYSIS_DATA
(BIO_ASY_ANALYSIS_DATA_ID);

CREATE INDEX BIOMART.BAADT_IDX17 ON BIOMART.BIO_ASSAY_ANALYSIS_DATA_TEA
(BIO_ASSAY_ANALYSIS_ID, TEA_RANK);

CREATE INDEX BIOMART.IDX2_BIO_ASY_GWAS_TOP50 ON BIOMART.BIO_ASY_ANALYSIS_GWAS_TOP50
(ANALYSIS);

CREATE INDEX BIOMART.IDX1_BIO_ASY_GWAS_T50 ON BIOMART.BIO_ASY_ANALYSIS_GWAS_TOP50
(BIO_ASSAY_ANALYSIS_ID);

ALTER TABLE BIOMART.BIO_ASY_ANALYSIS_DATA_IDX
 ADD CONSTRAINT PK_BIO_ASY_DATA_IDX
  PRIMARY KEY
  (BIO_ASY_ANALYSIS_DATA_IDX_ID);

ALTER TABLE BIOMART.BIO_ASSAY_ANALYSIS_EXT
 ADD CONSTRAINT PK_BIO_ASY_ANALY_EXT
  PRIMARY KEY
  (BIO_ASSAY_ANALYSIS_EXT_ID);

ALTER TABLE BIOMART.BIO_ASSAY_GENO_PLATFORM_PROBE
 ADD CONSTRAINT FK_BIO_ASY_GP_PROBE_ASY_PLF 
  FOREIGN KEY (BIO_ASSAY_PLATFORM_ID) 
  REFERENCES BIOMART.BIO_ASSAY_PLATFORM (BIO_ASSAY_PLATFORM_ID);

ALTER TABLE BIOMART.BIO_ASY_PLATFORM_PROBE_ANNO
 ADD CONSTRAINT FK_BIO_ASY_PPA_PLATFORM 
  FOREIGN KEY (BIO_ASSAY_PLATFORM_ID) 
  REFERENCES BIOMART.BIO_ASSAY_PLATFORM (BIO_ASSAY_PLATFORM_ID);

ALTER TABLE BIOMART.BIO_ASY_PLATFORM_PROBE_ANNO
 ADD CONSTRAINT FK_BIO_ASY_PPA_GP_PROBE 
  FOREIGN KEY (BIO_ASY_GENO_PLATFORM_PROBE_ID) 
  REFERENCES BIOMART.BIO_ASSAY_GENO_PLATFORM_PROBE (BIO_ASY_GENO_PLATFORM_PROBE_ID);

ALTER TABLE BIOMART.BIO_ASY_PLATFORM_PROBE_ANNO
 ADD CONSTRAINT FK_BIO_ASY_PPA_PROBE_ANNO 
  FOREIGN KEY (GENOTYPE_PROBE_ANNOTATION_ID) 
  REFERENCES BIOMART.GENOTYPE_PROBE_ANNOTATION (GENOTYPE_PROBE_ANNOTATION_ID);

ALTER TABLE BIOMART.BIO_ASSAY_ANALYSIS_GWAS
 ADD CONSTRAINT FK_GWAS_BIO_AA 
  FOREIGN KEY (BIO_ASSAY_ANALYSIS_ID) 
  REFERENCES BIOMART.BIO_ASSAY_ANALYSIS (BIO_ASSAY_ANALYSIS_ID);

ALTER TABLE BIOMART.BIO_ASSAY_ANALYSIS_GWAS
 ADD CONSTRAINT FK_GWAS_GENO_PLATFORM_PROBE 
  FOREIGN KEY (GENO_PLATFORM_PROBE_ID) 
  REFERENCES BIOMART.BIO_ASSAY_GENO_PLATFORM_PROBE (BIO_ASY_GENO_PLATFORM_PROBE_ID);

ALTER TABLE BIOMART.BIO_ASY_ANALYSIS_GWAS_TOP50
 ADD CONSTRAINT FK_GWAS_TOP50_ASY_ANAL 
  FOREIGN KEY (BIO_ASSAY_ANALYSIS_ID) 
  REFERENCES BIOMART.BIO_ASSAY_ANALYSIS (BIO_ASSAY_ANALYSIS_ID);

ALTER TABLE BIOMART.BIO_ASSAY_ANALYSIS_EXT
 ADD CONSTRAINT FK_ASY_ANALYSIS_EXT_ANALY 
  FOREIGN KEY (BIO_ASSAY_ANALYSIS_ID) 
  REFERENCES BIOMART.BIO_ASSAY_ANALYSIS (BIO_ASSAY_ANALYSIS_ID);
  
CREATE MATERIALIZED VIEW BIOMART.BIO_MARKER_EXP_ANALYSIS_MV_10 (BIO_MARKER_ID,BIO_EXPERIMENT_ID,BIO_ASSAY_ANALYSIS_ID,"T1.BIO_ASSAY_ANALYSIS_ID*100")
AS SELECT DISTINCT t3.bio_marker_id,
                t1.bio_experiment_id,
                t1.bio_assay_analysis_id,
                t1.bio_assay_analysis_id * 100 + t3.bio_marker_id
  FROM BIO_ASSAY_ANALYSIS_DATA t1,
       BIO_EXPERIMENT t2,
       BIO_MARKER t3,
       BIO_ASSAY_DATA_ANNOTATION t4
 WHERE     t1.bio_experiment_id = t2.bio_experiment_id
       AND t2.bio_experiment_type = 'Experiment'
       AND t3.bio_marker_id = t4.bio_marker_id
       AND t1.bio_assay_feature_group_id = t4.bio_assay_feature_group_id;

CREATE INDEX BIOMART.BIO_MARKER_EXP_AYLS_MV_INDEX1 ON BIOMART.BIO_MARKER_EXP_ANALYSIS_MV_10(BIO_MARKER_ID);