CREATE TABLE "DEAPP"."DE_RNASEQ_TRANSCRIPT_DATA"
  (	"TRANSCRIPT_ID" NUMBER NOT NULL ENABLE,
"ASSAY_ID" NUMBER NOT NULL ENABLE,
"READCOUNT" NUMBER,
"NORMALIZED_READCOUNT" FLOAT(126),
"LOG_NORMALIZED_READCOUNT" FLOAT(126),
"ZSCORE" FLOAT(126),
 CONSTRAINT "DE_RNASEQ_TRANSCRIPT_DATA" PRIMARY KEY ("ASSAY_ID", "TRANSCRIPT_ID")
 USING INDEX
 TABLESPACE "TRANSMART"  ENABLE
  ) SEGMENT CREATION IMMEDIATE
NOCOMPRESS LOGGING
 TABLESPACE "TRANSMART" ;

ALTER TABLE "DEAPP"."DE_RNASEQ_TRANSCRIPT_DATA" ADD CONSTRAINT "DE_RNASEQ_TR_DATA_TR_ID_FKEY" FOREIGN KEY ("TRANSCRIPT_ID")
 REFERENCES "DEAPP"."DE_RNASEQ_TRANSCRIPT_ANNOT" ("ID") ENABLE;

GRANT SELECT ON "DEAPP"."DE_RNASEQ_TRANSCRIPT_DATA" TO "BIOMART_USER";
GRANT ALL ON "DEAPP"."DE_RNASEQ_TRANSCRIPT_DATA" TO "DEAPP";
GRANT ALL ON "DEAPP"."DE_RNASEQ_TRANSCRIPT_DATA" TO "TM_CZ";