ALTER TABLE DEAPP.DE_SNP_SUBJECT_SORTED_DEF
 ADD (BIO_ASSAY_PLATFORM_ID  NUMBER(18));

ALTER TABLE DEAPP.DE_SNP_GENE_MAP
 ADD (GENE_NAME  VARCHAR2(255 BYTE));

ALTER TABLE DEAPP.DE_SNP_DATA_BY_PROBE
 ADD (BIO_ASY_GENO_PLATFORM_PROBE_ID  NUMBER(22));

ALTER TABLE DEAPP.DE_SNP_DATA_BY_PROBE
 ADD (GENOTYPE_PROBE_ANNOTATION_ID  NUMBER(22));

ALTER TABLE DEAPP.DE_SNP_DATA_BY_PROBE
 ADD (A1  VARCHAR2(4000 CHAR));

ALTER TABLE DEAPP.DE_SNP_DATA_BY_PROBE
 ADD (A2  VARCHAR2(4000 CHAR));

ALTER TABLE DEAPP.DE_SNP_DATA_BY_PROBE
 ADD (A1_CLOB  CLOB);

ALTER TABLE DEAPP.DE_SNP_DATA_BY_PROBE
 ADD (A2_CLOB  CLOB);

ALTER TABLE DEAPP.DE_SNP_DATA_BY_PROBE
 ADD (IMPUTE_QUALITY  NUMBER);

ALTER TABLE DEAPP.DE_SNP_DATA_BY_PROBE
 ADD (GPS_BY_PROBE_BLOB  BLOB);

ALTER TABLE DEAPP.DE_SNP_DATA_BY_PROBE
 ADD (GTS_BY_PROBE_BLOB  BLOB);

ALTER TABLE DEAPP.DE_SNP_DATA_BY_PROBE
 ADD (DOSE_BY_PROBE_BLOB  BLOB);

ALTER TABLE DEAPP.DE_SNP_DATA_BY_PROBE
 ADD (GT_PROBABILITY_THRESHOLD  NUMBER);

ALTER TABLE DEAPP.DE_SNP_DATA_BY_PROBE
 ADD (MAF  NUMBER);

ALTER TABLE DEAPP.DE_SNP_DATA_BY_PROBE
 ADD (MINOR_ALLELE  VARCHAR2(2 BYTE));

ALTER TABLE DEAPP.DE_SNP_DATA_BY_PROBE
 ADD (C_A1_A1  NUMBER(10));

ALTER TABLE DEAPP.DE_SNP_DATA_BY_PROBE
 ADD (C_A1_A2  NUMBER(10));

ALTER TABLE DEAPP.DE_SNP_DATA_BY_PROBE
 ADD (C_A2_A2  NUMBER(10));

ALTER TABLE DEAPP.DE_SNP_DATA_BY_PROBE
 ADD (C_NOCALL  NUMBER(10));

ALTER TABLE DEAPP.DE_SNP_DATA_BY_PROBE
 ADD (CREATED_BY  VARCHAR2(30 BYTE));

ALTER TABLE DEAPP.DE_SNP_DATA_BY_PROBE
 ADD (CREATED_DATE  DATE);

ALTER TABLE DEAPP.DE_SNP_DATA_BY_PROBE
 ADD (MODIFIED_BY  VARCHAR2(30 BYTE));

ALTER TABLE DEAPP.DE_SNP_DATA_BY_PROBE
 ADD (MODIFIED_DATE  DATE);

CREATE INDEX DEAPP.SNP_GENE_MAP_IDX ON DEAPP.DE_SNP_GENE_MAP
(ENTREZ_GENE_ID, SNP_NAME);

CREATE INDEX DEAPP.IDX_DE_SNP_GENE_MAP_GENEN ON DEAPP.DE_SNP_GENE_MAP
(GENE_NAME);

CREATE INDEX DEAPP.DE_SNP_CHROMPOS_IND ON DEAPP.DE_SNP_INFO
(CHROM, CHROM_POS);

CREATE UNIQUE INDEX DEAPP.IDX_DSDBP_PROBE_IDNAME ON DEAPP.DE_SNP_DATA_BY_PROBE
(SNP_DATA_BY_PROBE_ID, PROBE_NAME);

CREATE INDEX DEAPP.IDX_DSDBP1_ANNO_ID ON DEAPP.DE_SNP_DATA_BY_PROBE
(GENOTYPE_PROBE_ANNOTATION_ID);

CREATE INDEX DEAPP.IDX_DSDBP1_GP_PROBE_ID ON DEAPP.DE_SNP_DATA_BY_PROBE
(BIO_ASY_GENO_PLATFORM_PROBE_ID);

CREATE BITMAP INDEX DEAPP.IDX_DSDBP_TRIAL_NAME ON DEAPP.DE_SNP_DATA_BY_PROBE
(TRIAL_NAME);

CREATE INDEX DEAPP.IND_VCF_RSID ON DEAPP.DE_RC_SNP_INFO
(RS_ID);

CREATE INDEX DEAPP.IND_VCF_POS ON DEAPP.DE_RC_SNP_INFO
(POS);

CREATE INDEX DEAPP.DE_R_S_I_IND4 ON DEAPP.DE_RC_SNP_INFO
(SNP_INFO_ID);

CREATE UNIQUE INDEX DEAPP.DE_RSNP_HGRS_IND ON DEAPP.DE_RC_SNP_INFO
(HG_VERSION, RS_ID);

CREATE INDEX DEAPP.DE_RSNP_CHROM_COMP_IDX ON DEAPP.DE_RC_SNP_INFO
(CHROM, HG_VERSION, POS);

CREATE INDEX DEAPP.DE_RSNP_CHROMPOS_IND ON DEAPP.DE_RC_SNP_INFO
(CHROM, POS);

CREATE VIEW DEAPP.DE_SNP_INFO_HG19_MV
AS SELECT rs_id,
       chrom,
       pos,
       gene_name AS rsgene,
       exon_intron,
       recombination_rate,
       regulome_score
  FROM deapp.de_rc_snp_info info
 WHERE info.hg_version = 19;

CREATE OR REPLACE TRIGGER DEAPP.TRG_SNP_DATA_BY_PPROBE_ID
   BEFORE INSERT
   ON DEAPP.DE_SNP_DATA_BY_PROBE
   FOR EACH ROW
BEGIN
   IF INSERTING
   THEN
      IF :NEW.SNP_DATA_BY_PROBE_ID IS NULL
      THEN
         SELECT SEQ_DATA_ID.NEXTVAL INTO :NEW.SNP_DATA_BY_PROBE_ID FROM DUAL;
      END IF;
   END IF;
END;
/

ALTER TABLE DEAPP.DE_SUBJECT_MICROARRAY_DATA MODIFY RAW_INTENSITY NUMBER(30,4);