CREATE SEQUENCE  "I2B2METADATA"."SEQ_DIMENSION_DESCRIPTION_ID";

CREATE TABLE "I2B2METADATA"."DIMENSION_DESCRIPTION"
  (	"ID" NUMBER,
"DENSITY" VARCHAR2(255 BYTE),
"MODIFIER_CODE" VARCHAR2(255 BYTE),
"VALUE_TYPE" VARCHAR2(50 BYTE),
"NAME" VARCHAR2(255 BYTE) NOT NULL ENABLE,
"PACKABLE" VARCHAR2(255 BYTE),
"SIZE_CD" VARCHAR2(255 BYTE),
 PRIMARY KEY ("ID")
 USING INDEX
 TABLESPACE "TRANSMART"  ENABLE
  ) SEGMENT CREATION IMMEDIATE
NOCOMPRESS LOGGING
 TABLESPACE "TRANSMART" ;

CREATE OR REPLACE EDITIONABLE TRIGGER "I2B2METADATA"."DIMENSION_DESCRIPTION_ID_TRG"
BEFORE INSERT ON I2B2METADATA.dimension_description
FOR EACH ROW

BEGIN
  if inserting then
    if :NEW."ID" is null then
      SELECT SEQ_DIMENSION_DESCRIPTION_ID.NEXTVAL
      INTO   :new.id
      FROM   dual;
    end if;
  end if;
END;
/
ALTER TRIGGER "I2B2METADATA"."DIMENSION_DESCRIPTION_ID_TRG" ENABLE;

GRANT SELECT ON "I2B2METADATA"."DIMENSION_DESCRIPTION" TO "BIOMART_USER";
GRANT ALL ON "I2B2METADATA"."DIMENSION_DESCRIPTION" TO "I2B2METADATA";
GRANT ALL ON "I2B2METADATA"."DIMENSION_DESCRIPTION" TO "TM_CZ";