CREATE TABLE "I2B2DEMODATA"."LINKED_FILE_COLLECTION"
  (	"ID" NUMBER(*,0) NOT NULL ENABLE,
"NAME" VARCHAR2(900 BYTE),
"STUDY_ID" NUMBER(*,0) NOT NULL ENABLE,
"SOURCE_SYSTEM_ID" NUMBER(*,0) NOT NULL ENABLE,
"UUID" VARCHAR2(50 BYTE),
 CONSTRAINT "LINKED_FILE_COLLECTION_PKEY" PRIMARY KEY ("ID")
 USING INDEX
 TABLESPACE "TRANSMART"  ENABLE
  ) SEGMENT CREATION IMMEDIATE
NOCOMPRESS LOGGING
 TABLESPACE "TRANSMART" ;

ALTER TABLE "I2B2DEMODATA"."LINKED_FILE_COLLECTION" ADD CONSTRAINT "SOURCE_SYSTEM_ID_ID_FK" FOREIGN KEY ("SOURCE_SYSTEM_ID")
 REFERENCES "I2B2DEMODATA"."STORAGE_SYSTEM" ("ID") ENABLE;

ALTER TABLE "I2B2DEMODATA"."LINKED_FILE_COLLECTION" ADD CONSTRAINT "STUDY_ID_FK" FOREIGN KEY ("STUDY_ID")
 REFERENCES "I2B2DEMODATA"."STUDY" ("STUDY_NUM") ENABLE;

GRANT SELECT, INSERT, UPDATE, DELETE ON "I2B2DEMODATA"."LINKED_FILE_COLLECTION" TO "BIOMART_USER";
GRANT ALL ON "I2B2DEMODATA"."LINKED_FILE_COLLECTION" TO "I2B2DEMODATA";
GRANT ALL ON "I2B2DEMODATA"."LINKED_FILE_COLLECTION" TO "TM_CZ";