CREATE TABLE "I2B2DEMODATA"."STORAGE_SYSTEM"
  (	"ID" NUMBER(*,0) NOT NULL ENABLE,
"NAME" VARCHAR2(50 BYTE),
"SYSTEM_TYPE" VARCHAR2(50 BYTE),
"URL" VARCHAR2(900 BYTE),
"SYSTEM_VERSION" VARCHAR2(50 BYTE),
"SINGLE_FILE_COLLECTIONS" CHAR(1 BYTE),
 CONSTRAINT "STORAGE_SYSTEM_PKEY" PRIMARY KEY ("ID")
 USING INDEX
 TABLESPACE "TRANSMART"  ENABLE
  ) SEGMENT CREATION IMMEDIATE
NOCOMPRESS LOGGING
 TABLESPACE "TRANSMART" ;

GRANT SELECT, INSERT, UPDATE, DELETE ON "I2B2DEMODATA"."STORAGE_SYSTEM" TO "BIOMART_USER";
GRANT ALL ON "I2B2DEMODATA"."STORAGE_SYSTEM" TO "I2B2DEMODATA";
GRANT ALL ON "I2B2DEMODATA"."STORAGE_SYSTEM" TO "TM_CZ";