CREATE TABLE "I2B2DEMODATA"."SUPPORTED_WORKFLOW"
  (	"ID" NUMBER(*,0),
"NAME" VARCHAR2(500 BYTE),
"DESCRIPTION" VARCHAR2(1000 BYTE),
"UUID" VARCHAR2(50 BYTE) NOT NULL ENABLE,
"ARVADOS_INSTANCE_URL" VARCHAR2(500 BYTE),
"ARVADOS_VERSION" VARCHAR2(50 BYTE),
"DEFAULT_PARAMS" CLOB
  ) SEGMENT CREATION IMMEDIATE
NOCOMPRESS LOGGING
 TABLESPACE "TRANSMART"
LOB ("DEFAULT_PARAMS") STORE AS SECUREFILE (
 TABLESPACE "TRANSMART" ENABLE STORAGE IN ROW CHUNK 8192
 NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;

CREATE INDEX "I2B2DEMODATA"."SUPPORTED_WORKFLOW_INDEX1" ON "I2B2DEMODATA"."SUPPORTED_WORKFLOW" ("ID")
TABLESPACE "TRANSMART" ;

GRANT SELECT, INSERT, UPDATE, DELETE ON "I2B2DEMODATA"."SUPPORTED_WORKFLOW" TO "BIOMART_USER";
GRANT ALL ON "I2B2DEMODATA"."SUPPORTED_WORKFLOW" TO "I2B2DEMODATA";
GRANT ALL ON "I2B2DEMODATA"."SUPPORTED_WORKFLOW" TO "TM_CZ";