--
-- Type: TABLE; Owner: I2B2METADATA; Name: DIMENSION_DESCRIPTION
--
 CREATE TABLE "I2B2METADATA"."DIMENSION_DESCRIPTION"
  (	"ID" NUMBER,
"DENSITY" VARCHAR2(255 BYTE),
"MODIFIER_CODE" VARCHAR2(255 BYTE),
"VALUE_TYPE" VARCHAR2(50 BYTE),
"NAME" VARCHAR2(255 BYTE) NOT NULL ENABLE,
"PACKABLE" VARCHAR2(255 BYTE),
"SIZE_CD" VARCHAR2(255 BYTE),
 PRIMARY KEY ("ID")
 USING INDEX
 TABLESPACE "TRANSMART"  ENABLE
  ) SEGMENT CREATION DEFERRED
NOCOMPRESS LOGGING
 TABLESPACE "TRANSMART" ;
--
-- Type: SEQUENCE; Owner: I2B2METADATA; Name: DIMENSION_DESCRIPTION_ID_SEQ
--
CREATE SEQUENCE  "I2B2METADATA"."DIMENSION_DESCRIPTION_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--
-- Type: TRIGGER; Owner: I2B2METADATA; Name: DIMENSION_DESCRIPTION_ID_TRG
--
  CREATE OR REPLACE TRIGGER "I2B2METADATA"."DIMENSION_DESCRIPTION_ID_TRG"
BEFORE INSERT ON I2B2METADATA.dimension_description
FOR EACH ROW

BEGIN
  if inserting then
    if :NEW."ID" is null then
      SELECT DIMENSION_DESCRIPTION_ID_SEQ.NEXTVAL
      INTO   :new.id
      FROM   dual;
    end if;
  end if;
END;
/
ALTER TRIGGER "I2B2METADATA"."DIMENSION_DESCRIPTION_ID_TRG" ENABLE;
