--
-- Type: TABLE; Owner: I2B2METADATA; Name: I2B2_TAG_OPTIONS
--
 CREATE TABLE "I2B2METADATA"."I2B2_TAG_OPTIONS"
  (	"TAG_OPTION_ID" NUMBER NOT NULL ENABLE,
"TAG_TYPE_ID" NUMBER(18,0) NOT NULL ENABLE,
"VALUE" VARCHAR2(1000 BYTE),
 CONSTRAINT "I2B2_TAG_OPTIONS_PKEY" PRIMARY KEY ("TAG_OPTION_ID")
 USING INDEX
 TABLESPACE "INDX"  ENABLE
  ) SEGMENT CREATION DEFERRED
NOCOMPRESS LOGGING
 TABLESPACE "TRANSMART" ;
--
-- Type: SEQUENCE; Owner: I2B2METADATA; Name: I2B2_TAG_OPTIONS_ID_SEQ
--
CREATE SEQUENCE  "I2B2METADATA"."I2B2_TAG_OPTIONS_ID_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--
-- Type: TRIGGER; Owner: I2B2METADATA; Name: TRG_I2B2_TAG_OPTIONS_ID
--
  CREATE OR REPLACE EDITIONABLE TRIGGER "I2B2METADATA"."TRG_I2B2_TAG_OPTIONS_ID"
   before insert on "I2B2METADATA"."I2B2_TAG_OPTIONS"
   for each row
begin
   if inserting then
      if :NEW."TAG_OPTION_ID" is null then
         select I2B2_TAG_OPTIONS_ID_SEQ.nextval into :NEW."TAG_OPTION_ID" from dual;
      end if;
   end if;
end;
/
ALTER TRIGGER "I2B2METADATA"."TRG_I2B2_TAG_OPTIONS_ID" ENABLE;
