--
-- Type: TABLE; Owner: I2B2METADATA; Name: QUERY1
--
 CREATE TABLE "I2B2METADATA"."QUERY1" 
  (	"TRIALNUMBER" NVARCHAR2(255), 
"DESCRIPTION" NCLOB
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" 
LOB ("DESCRIPTION") STORE AS BASICFILE "SYS_LOB0000015519C00002$$"(
 TABLESPACE "TRANSMART" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
 NOCACHE LOGGING ) ;

