--
-- Type: TABLE; Owner: I2B2METADATA; Name: STUDY_DIMENSION_DESCRIPTIONS
--
 CREATE TABLE "I2B2METADATA"."STUDY_DIMENSION_DESCRIPTIONS"
  (	"DIMENSION_DESCRIPTION_ID" NUMBER NOT NULL ENABLE,
"STUDY_ID" NUMBER NOT NULL ENABLE,
 PRIMARY KEY ("STUDY_ID", "DIMENSION_DESCRIPTION_ID")
 USING INDEX
 TABLESPACE "TRANSMART"  ENABLE
  ) SEGMENT CREATION IMMEDIATE
NOCOMPRESS LOGGING
 TABLESPACE "TRANSMART" ;
--
-- Type: REF_CONSTRAINT; Owner: I2B2METADATA; Name: FK_9VVV5M5NBXSU2LKBEEFTEVD5J
--
ALTER TABLE "I2B2METADATA"."STUDY_DIMENSION_DESCRIPTIONS" ADD CONSTRAINT "FK_9VVV5M5NBXSU2LKBEEFTEVD5J" FOREIGN KEY ("DIMENSION_DESCRIPTION_ID")
 REFERENCES "I2B2METADATA"."DIMENSION_DESCRIPTION" ("ID") ENABLE;
