--
-- Type: TABLE; Owner: AMAPP; Name: AM_DATA_UID
--
 CREATE TABLE "AMAPP"."AM_DATA_UID" 
  (	"AM_DATA_ID" NUMBER(18,0) NOT NULL ENABLE, 
"UNIQUE_ID" NVARCHAR2(300) NOT NULL ENABLE, 
"AM_DATA_TYPE" NVARCHAR2(100) NOT NULL ENABLE, 
 CONSTRAINT "AM_DATA_UID_PK" PRIMARY KEY ("AM_DATA_ID")
 USING INDEX
 TABLESPACE "INDX"  ENABLE, 
 CONSTRAINT "AM_DATA_UID_UK" UNIQUE ("UNIQUE_ID")
 USING INDEX
 TABLESPACE "INDX"  ENABLE
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

