#!/usr/bin/ruby

if (dir = ARGV.shift)
  Dir.chdir dir
end

STDOUT.reopen(File.open('datasets_index', 'w'))

Dir.glob('**/*.tar.xz').sort.each do |file_name|
  match_data = /^(.+?)_(.+)\.tar\.xz$/.match(File.basename(file_name))
  study, data_type = [match_data[1], match_data[2]]
  puts "#{study} #{data_type} #{file_name}"
end.sort

# vim: set ft=ruby et ts=2 sw=2:
