ifndef KETTLE_JOBS_ORA
  $(error You need to set KETTLE_JOBS_ORA)
endif
KETTLE_JOBS = $(KETTLE_JOBS_ORA)
JDBC_DRIVER = ojdbc6-12.1.0.1.0.jar
JDBC_DL = http://files.thehyve.net
RDBMS = oracle

include ../common/makefile.inc
