--
-- Type: TABLE; Owner: TM_LZ; Name: LT_CHROMOSOMAL_REGION
--
 CREATE TABLE "TM_LZ"."LT_CHROMOSOMAL_REGION" 
  (	"REGION_ID" NUMBER NOT NULL ENABLE, 
"GPL_ID" VARCHAR2(50 BYTE), 
"CHROMOSOME" VARCHAR2(2 BYTE), 
"START_BP" NUMBER, 
"END_BP" NUMBER, 
"NUM_PROBES" NUMBER(*,0), 
"REGION_NAME" VARCHAR2(100 BYTE), 
"CYTOBAND" VARCHAR2(100 BYTE), 
"GENE_SYMBOL" VARCHAR2(100 BYTE), 
"GENE_ID" NUMBER, 
"ORGANISM" VARCHAR2(200 BYTE), 
 CONSTRAINT "LT_CHROMOSOMAL_REGION_PKEY" PRIMARY KEY ("REGION_ID")
 USING INDEX
 TABLESPACE "TRANSMART"  ENABLE
  ) SEGMENT CREATION DEFERRED
 TABLESPACE "TRANSMART" ;

