--
-- Type: TABLE; Owner: TM_LZ; Name: LT_QPCR_MIRNA_ANNOTATION
--
 CREATE TABLE "TM_LZ"."LT_QPCR_MIRNA_ANNOTATION" 
  (	"PLT_ID" VARCHAR2(100 BYTE), 
"MIRNA_ID" VARCHAR2(100 BYTE), 
"SN_ID" VARCHAR2(100 BYTE), 
"PLT_NAME" VARCHAR2(1000 BYTE), 
"ORGANISM" VARCHAR2(1000 BYTE)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

