--
-- Type: TABLE; Owner: TM_LZ; Name: LT_SRC_METABOLOMIC_DATA
--
 CREATE TABLE "TM_LZ"."LT_SRC_METABOLOMIC_DATA" 
  (	"TRIAL_NAME" VARCHAR2(25 BYTE), 
"BIOCHEMICAL" VARCHAR2(200 BYTE), 
"EXPR_ID" VARCHAR2(100 BYTE), 
"INTENSITY_VALUE" VARCHAR2(50 BYTE)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

