--
-- Type: TABLE; Owner: TM_LZ; Name: LT_SRC_PROTEOMICS_DATA
--
 CREATE TABLE "TM_LZ"."LT_SRC_PROTEOMICS_DATA" 
  (	"TRIAL_NAME" VARCHAR2(25 BYTE), 
"PEPTIDE" VARCHAR2(100 BYTE), 
"M_P_ID" VARCHAR2(100 BYTE), 
"INTENSITY_VALUE" VARCHAR2(50 BYTE)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

