--
-- Type: TABLE; Owner: TM_LZ; Name: LT_SRC_PATHWAY
--
 CREATE TABLE "TM_LZ"."LT_SRC_PATHWAY" 
  (	"NAME" VARCHAR2(1000 BYTE), 
"GENE" VARCHAR2(1000 BYTE), 
"ORGANISM" VARCHAR2(200 BYTE)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

