--
-- Type: TABLE; Owner: TM_LZ; Name: LT_SRC_CLINICAL_DATA
--
 CREATE TABLE "TM_LZ"."LT_SRC_CLINICAL_DATA" 
  (	"STUDY_ID" VARCHAR2(25 BYTE), 
"SITE_ID" VARCHAR2(50 BYTE), 
"SUBJECT_ID" VARCHAR2(30 BYTE), --postgres was 20 in oracle
"VISIT_NAME" VARCHAR2(100 BYTE), 
"SAMPLE_TYPE" VARCHAR2(100 BYTE), 
"DATA_LABEL" VARCHAR2(500 BYTE), 
"DATA_VALUE" VARCHAR2(500 BYTE), 
"MODIFIER_CD" VARCHAR2(100 BYTE), --postgres
"UNITS_CD" VARCHAR2(50 BYTE),	  --postgres
"CATEGORY_CD" VARCHAR2(250 BYTE),
"CTRL_VOCAB_CODE" VARCHAR2(200 BYTE),
"DATE_TIMESTAMP" DATE,		 --postgres
"VISIT_DATE" VARCHAR2(200 BYTE), --added to postgres
"SAMPLE_CD" VARCHAR2(200 BYTE)	--added to postgres
  ) SEGMENT CREATION IMMEDIATE
NOCOMPRESS LOGGING
 TABLESPACE "TRANSMART" ;
