--
-- Type: TABLE; Owner: TM_LZ; Name: LT_SRC_RNA_SEQ_DATA
--
 CREATE TABLE "TM_LZ"."LT_SRC_RNA_SEQ_DATA" 
  (	"TRIAL_NAME" VARCHAR2(25 BYTE), 
"PROBESET" VARCHAR2(100 BYTE), 
"EXPR_ID" VARCHAR2(100 BYTE), 
"INTENSITY_VALUE" VARCHAR2(50 BYTE)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

