--
-- Type: TABLE; Owner: TM_LZ; Name: LZ_SRC_MRNA_DATA
--
 CREATE TABLE "TM_LZ"."LZ_SRC_MRNA_DATA" 
  (	"TRIAL_NAME" VARCHAR2(25 BYTE), 
"PROBESET" VARCHAR2(100 BYTE), 
"EXPR_ID" VARCHAR2(100 BYTE), 
"INTENSITY_VALUE" VARCHAR2(50 BYTE), 
"SOURCE_CD" VARCHAR2(200 BYTE)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" 
 PARTITION BY LIST ("TRIAL_NAME") 
(PARTITION "GSE20685"  VALUES ('GSE20685') SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" , 
PARTITION "BSI201_20070102"  VALUES ('BSI201_20070102') SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" , 
PARTITION "GSE4382"  VALUES ('GSE4382') SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" , 
PARTITION "BSI201RICERCA"  VALUES ('BSI201RICERCA') SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" , 
PARTITION "GSE14860"  VALUES ('GSE14860') SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" , 
PARTITION "BSI201PHASE3"  VALUES ('BSI201PHASE3') SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" , 
PARTITION "GSE10846"  VALUES ('GSE10846') SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" , 
PARTITION "GSE19650"  VALUES ('GSE19650') SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" , 
PARTITION "GSE22780"  VALUES ('GSE22780') SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" , 
PARTITION "GSE19976"  VALUES ('GSE19976') SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ) ;
