--
-- Type: TABLE; Owner: TM_LZ; Name: RWG_SAMPLES_EXT
--
 CREATE TABLE "TM_LZ"."RWG_SAMPLES_EXT" 
  (	"STUDY_ID" VARCHAR2(500 BYTE), 
"EXPR_ID" VARCHAR2(500 BYTE), 
"COHORTS" VARCHAR2(500 BYTE)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

