\ir prelude.sql
\ir lz_src_sample_categories.sql
\ir clinical_trial_metadata_ext.sql
\ir lt_chromosomal_region.sql
\ir lt_src_acgh_data.sql
\ir lt_src_clinical_data.sql
\ir lt_src_deapp_annot.sql
\ir lt_src_mrna_data.sql
\ir lt_src_mrna_subj_samp_map.sql
\ir lt_src_sample_categories.sql
\ir lt_src_study_metadata.sql
\ir lz_src_clinical_data.sql
\ir lz_src_mrna_data.sql
\ir lz_src_mrna_subj_samp_map.sql
\ir lz_src_sample_categories_bkup.sql
\ir rwg_analysis.sql
\ir rwg_analysis_data.sql
\ir rwg_analysis_data_ext.sql
\ir rwg_analysis_ext.sql
\ir rwg_cohorts.sql
\ir rwg_cohorts_ext.sql
\ir rwg_samples.sql
\ir rwg_samples_ext.sql
\ir wt_snp_node_values.sql
\ir wt_snp_nodes.sql
\ir _misc.sql
