\i tm_lz/prelude.sql
\i tm_lz/lz_src_sample_categories.sql
\i tm_lz/clinical_trial_metadata_ext.sql
\i tm_lz/lt_chromosomal_region.sql
\i tm_lz/lt_src_acgh_data.sql
\i tm_lz/lt_src_clinical_data.sql
\i tm_lz/lt_src_deapp_annot.sql
\i tm_lz/lt_src_mrna_data.sql
\i tm_lz/lt_src_mrna_subj_samp_map.sql
\i tm_lz/lt_src_sample_categories.sql
\i tm_lz/lt_src_study_metadata.sql
\i tm_lz/lz_src_clinical_data.sql
\i tm_lz/lz_src_mrna_data.sql
\i tm_lz/lz_src_mrna_subj_samp_map.sql
\i tm_lz/lz_src_sample_categories_bkup.sql
\i tm_lz/rwg_analysis.sql
\i tm_lz/rwg_analysis_data.sql
\i tm_lz/rwg_analysis_data_ext.sql
\i tm_lz/rwg_analysis_ext.sql
\i tm_lz/rwg_cohorts.sql
\i tm_lz/rwg_cohorts_ext.sql
\i tm_lz/rwg_samples.sql
\i tm_lz/rwg_samples_ext.sql
\i tm_lz/wt_snp_node_values.sql
\i tm_lz/wt_snp_nodes.sql
\i tm_lz/_misc.sql
