--
-- Name: clinical_trial_metadata_ext; Type: TABLE; Schema: tm_lz; Owner: -
--
CREATE TABLE clinical_trial_metadata_ext (
    trial character varying(4000),
    title character varying(4000),
    description character varying(4000),
    condition character varying(4000),
    disease_subtype character varying(4000),
    drug_cnto character varying(4000),
    drug_name character varying(4000),
    descriptive_trial_name character varying(4000),
    study_owner character varying(4000),
    biomarker_data_owner character varying(4000),
    study_phase character varying(4000),
    blinding_procedure character varying(4000),
    study_type character varying(4000),
    duration_of_study character varying(4000),
    number_of_patients character varying(4000),
    number_of_sites character varying(4000),
    route_of_admin character varying(4000),
    dosing_regimen character varying(4000),
    group_assignment character varying(4000),
    type_of_control character varying(4000),
    study_design character varying(4000),
    completion_date character varying(4000),
    primary_endpoints character varying(4000),
    secondary_endpoints character varying(4000),
    inclusion_criteria character varying(4000),
    exclusion_criteria character varying(4000),
    subjects character varying(4000),
    gender_restriction character varying(4000),
    min_age character varying(4000),
    max_age character varying(4000),
    secondary_ids character varying(4000),
    pi character varying(4000),
    development_partner character varying(4000),
    geo_platform character varying(4000),
    main_findings character varying(4000),
    platform_name character varying(4000),
    study_id character varying(50),
    search_area character varying(100),
    experimental_design character varying(100),
    data_source character varying(100)
);

