--
-- Type: TABLE; Owner: DEAPP; Name: DE_ENCOUNTER_LEVEL
--
 CREATE TABLE "DEAPP"."DE_ENCOUNTER_LEVEL" 
  (	"STUDY_ID" VARCHAR2(50 BYTE), 
"CONCEPT_ID" VARCHAR2(500 BYTE), 
"LINK_TYPE" VARCHAR2(50 BYTE)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

