--
-- Type: TABLE; Owner: DEAPP; Name: DE_METABOLITE_ANNOTATION
--
 CREATE TABLE "DEAPP"."DE_METABOLITE_ANNOTATION" 
  (	"ID" NUMBER(*,0) NOT NULL ENABLE, 
"GPL_ID" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
"BIOCHEMICAL_NAME" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
"BIOMARKER_ID" NVARCHAR2(200), 
"HMDB_ID" VARCHAR2(50 BYTE), 
 CONSTRAINT "DE_METABOLITE_ANNOTATION_PK" PRIMARY KEY ("ID")
 USING INDEX
 TABLESPACE "TRANSMART"  ENABLE
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

