--
-- Type: TABLE; Owner: DEAPP; Name: DE_METABOLITE_SUB_PATHWAYS
--
 CREATE TABLE "DEAPP"."DE_METABOLITE_SUB_PATHWAYS" 
  (	"ID" NUMBER(*,0) NOT NULL ENABLE, 
"GPL_ID" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
"SUB_PATHWAY_NAME" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
"SUPER_PATHWAY_ID" NUMBER(*,0)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "DEAPP" ;
