--
-- Type: TABLE; Owner: DEAPP; Name: DE_METABOLITE_SUB_PWAY_METAB
--
 CREATE TABLE "DEAPP"."DE_METABOLITE_SUB_PWAY_METAB" 
  (	"METABOLITE_ID" NUMBER(*,0) NOT NULL ENABLE, 
"SUB_PATHWAY_ID" NUMBER(*,0) NOT NULL ENABLE
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "DEAPP" ;
