--
-- Type: TABLE; Owner: DEAPP; Name: DE_OBS_ENROLL_DAYS
--
 CREATE TABLE "DEAPP"."DE_OBS_ENROLL_DAYS" 
  (	"ENCOUNTER_NUM" NUMBER(38,0), 
"DAYS_SINCE_ENROLL" NUMBER(18,3), 
"STUDY_ID" VARCHAR2(200 BYTE)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

--
-- Type: INDEX; Owner: DEAPP; Name: DE_OBS_ENROLL_DAYS_IDX2
--
CREATE INDEX "DEAPP"."DE_OBS_ENROLL_DAYS_IDX2" ON "DEAPP"."DE_OBS_ENROLL_DAYS" ("STUDY_ID")
TABLESPACE "INDX" ;

