--
-- Type: TABLE; Owner: DEAPP; Name: DE_PROTEIN_ANNOTATION
--
 CREATE TABLE "DEAPP"."DE_PROTEIN_ANNOTATION" 
  (	"ID" NUMBER(*,0), 
"GPL_ID" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
"PEPTIDE" VARCHAR2(200 CHAR) NOT NULL ENABLE, 
"UNIPROT_ID" VARCHAR2(50 CHAR), 
"BIOMARKER_ID" NVARCHAR2(200), 
"ORGANISM" VARCHAR2(200 CHAR), 
"UNIPROT_NAME" VARCHAR2(200 CHAR), 
 PRIMARY KEY ("ID")
 USING INDEX
 TABLESPACE "DEAPP"  ENABLE
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "DEAPP" ;

