--
-- Type: TABLE; Owner: DEAPP; Name: DE_RBM_ANNOTATION
--
 CREATE TABLE "DEAPP"."DE_RBM_ANNOTATION" 
  (	"ID" NUMBER(*,0), 
"GPL_ID" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
"ANTIGEN_NAME" VARCHAR2(200 CHAR) NOT NULL ENABLE, 
"UNIPROT_ID" VARCHAR2(50 CHAR), 
"GENE_SYMBOL" VARCHAR2(50 CHAR), 
"GENE_ID" NVARCHAR2(200), 
 PRIMARY KEY ("ID")
 USING INDEX
 TABLESPACE "DEAPP"  ENABLE
  ) SEGMENT CREATION DEFERRED
 TABLESPACE "DEAPP" ;

