--
-- Type: TABLE; Owner: DEAPP; Name: DE_RBM_DATA_ANNOTATION_JOIN
--
 CREATE TABLE "DEAPP"."DE_RBM_DATA_ANNOTATION_JOIN" 
  (	"DATA_ID" NUMBER(38,0), 
"ANNOTATION_ID" NUMBER(38,0), 
 CONSTRAINT "PK_DE_RBM_DATA_ANNOTATION_JOIN" PRIMARY KEY ("DATA_ID", "ANNOTATION_ID")
 USING INDEX
 TABLESPACE "DEAPP"  ENABLE
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "DEAPP" ;

--
-- Type: REF_CONSTRAINT; Owner: DEAPP; Name: SYS_C0018584
--
ALTER TABLE "DEAPP"."DE_RBM_DATA_ANNOTATION_JOIN" ADD FOREIGN KEY ("ANNOTATION_ID")
 REFERENCES "DEAPP"."DE_RBM_ANNOTATION" ("ID") ON DELETE CASCADE ENABLE;

--
-- Type: REF_CONSTRAINT; Owner: DEAPP; Name: SYS_C0018583
--
ALTER TABLE "DEAPP"."DE_RBM_DATA_ANNOTATION_JOIN" ADD FOREIGN KEY ("DATA_ID")
 REFERENCES "DEAPP"."DE_SUBJECT_RBM_DATA" ("ID") ON DELETE CASCADE ENABLE;

