--
-- Type: TABLE; Owner: DEAPP; Name: DE_SNP_CALLS_BY_GSM
--
 CREATE TABLE "DEAPP"."DE_SNP_CALLS_BY_GSM" 
  (	"TRIAL_NAME" VARCHAR2(20 BYTE), 
"GSM_NUM" VARCHAR2(100 BYTE), 
"PATIENT_NUM" NUMBER(20,0), 
"SNP_NAME" VARCHAR2(100 BYTE), 
"SNP_CALLS" VARCHAR2(4 BYTE)
  )
 TABLESPACE "DEAPP" 
 PARTITION BY HASH ("PATIENT_NUM") 
(PARTITION "SYS_P81" SEGMENT CREATION IMMEDIATE 
 TABLESPACE "DEAPP" 
NOCOMPRESS , 
PARTITION "SYS_P82" SEGMENT CREATION IMMEDIATE 
 TABLESPACE "DEAPP" 
NOCOMPRESS , 
PARTITION "SYS_P83" SEGMENT CREATION IMMEDIATE 
 TABLESPACE "DEAPP" 
NOCOMPRESS , 
PARTITION "SYS_P84" SEGMENT CREATION IMMEDIATE 
 TABLESPACE "DEAPP" 
NOCOMPRESS , 
PARTITION "SYS_P85" SEGMENT CREATION IMMEDIATE 
 TABLESPACE "DEAPP" 
NOCOMPRESS , 
PARTITION "SYS_P86" SEGMENT CREATION IMMEDIATE 
 TABLESPACE "DEAPP" 
NOCOMPRESS , 
PARTITION "SYS_P87" SEGMENT CREATION IMMEDIATE 
 TABLESPACE "DEAPP" 
NOCOMPRESS , 
PARTITION "SYS_P88" SEGMENT CREATION IMMEDIATE 
 TABLESPACE "DEAPP" 
NOCOMPRESS , 
PARTITION "SYS_P89" SEGMENT CREATION IMMEDIATE 
 TABLESPACE "DEAPP" 
NOCOMPRESS , 
PARTITION "SYS_P90" SEGMENT CREATION IMMEDIATE 
 TABLESPACE "DEAPP" 
NOCOMPRESS ) ;
--
-- Type: INDEX; Owner: DEAPP; Name: IDX_SNP_CALLS_BY_GSM_PG
--
 CREATE BITMAP INDEX "DEAPP"."IDX_SNP_CALLS_BY_GSM_PG" ON "DEAPP"."DE_SNP_CALLS_BY_GSM" ("PATIENT_NUM", "GSM_NUM") 
 LOCAL
(PARTITION "SYS_P101" 
 TABLESPACE "DEAPP" , 
PARTITION "SYS_P102" 
 TABLESPACE "DEAPP" , 
PARTITION "SYS_P103" 
 TABLESPACE "DEAPP" , 
PARTITION "SYS_P104" 
 TABLESPACE "DEAPP" , 
PARTITION "SYS_P105" 
 TABLESPACE "DEAPP" , 
PARTITION "SYS_P106" 
 TABLESPACE "DEAPP" , 
PARTITION "SYS_P107" 
 TABLESPACE "DEAPP" , 
PARTITION "SYS_P108" 
 TABLESPACE "DEAPP" , 
PARTITION "SYS_P109" 
 TABLESPACE "DEAPP" , 
PARTITION "SYS_P110" 
 TABLESPACE "DEAPP" ) ;
