--
-- Type: TABLE; Owner: DEAPP; Name: DE_SUBJECT_PROTEIN_DATA
--
 CREATE TABLE "DEAPP"."DE_SUBJECT_PROTEIN_DATA" 
  (	"TRIAL_NAME" VARCHAR2(50 BYTE), 
"COMPONENT" VARCHAR2(200 BYTE), 
"INTENSITY" NUMBER, 
"PATIENT_ID" NUMBER(38,0), 
"SUBJECT_ID" VARCHAR2(10 BYTE), 
"GENE_SYMBOL" VARCHAR2(100 BYTE), 
"GENE_ID" NUMBER(10,0), 
"ASSAY_ID" NUMBER, 
"TIMEPOINT" VARCHAR2(20 BYTE), 
"N_VALUE" NUMBER, 
"MEAN_INTENSITY" NUMBER, 
"STDDEV_INTENSITY" NUMBER, 
"MEDIAN_INTENSITY" NUMBER, 
"ZSCORE" NUMBER, 
"LOG_INTENSITY" NUMBER, 
"PROTEIN_ANNOTATION_ID" NUMBER(*,0)
  ) SEGMENT CREATION IMMEDIATE
NOCOMPRESS NOLOGGING
 TABLESPACE "DEAPP" ;
--
-- Type: REF_CONSTRAINT; Owner: DEAPP; Name: SYS_C0010753
--
ALTER TABLE "DEAPP"."DE_SUBJECT_PROTEIN_DATA" ADD FOREIGN KEY ("PROTEIN_ANNOTATION_ID")
 REFERENCES "DEAPP"."DE_PROTEIN_ANNOTATION" ("ID") ENABLE;
--
-- Type: INDEX; Owner: DEAPP; Name: DE_SUBJECT_PROTEIN_MCIDX1
--
CREATE BITMAP INDEX "DEAPP"."DE_SUBJECT_PROTEIN_MCIDX1" ON "DEAPP"."DE_SUBJECT_PROTEIN_DATA" ("TRIAL_NAME")
TABLESPACE "DEAPP" ;
--
-- Type: INDEX; Owner: DEAPP; Name: DE_SUBJECT_PROTEIN_MCIDX2
--
CREATE BITMAP INDEX "DEAPP"."DE_SUBJECT_PROTEIN_MCIDX2" ON "DEAPP"."DE_SUBJECT_PROTEIN_DATA" ("COMPONENT")
TABLESPACE "DEAPP" ;
--
-- Type: INDEX; Owner: DEAPP; Name: DE_SUBJECT_PROTEIN_MCIDX3
--
CREATE BITMAP INDEX "DEAPP"."DE_SUBJECT_PROTEIN_MCIDX3" ON "DEAPP"."DE_SUBJECT_PROTEIN_DATA" ("PATIENT_ID")
TABLESPACE "DEAPP" ;
--
-- Type: INDEX; Owner: DEAPP; Name: DE_SUBJECT_PROTEIN_MCIDX4
--
CREATE BITMAP INDEX "DEAPP"."DE_SUBJECT_PROTEIN_MCIDX4" ON "DEAPP"."DE_SUBJECT_PROTEIN_DATA" ("GENE_SYMBOL")
TABLESPACE "DEAPP" ;
