--
-- Type: TABLE; Owner: DEAPP; Name: DE_SUBJECT_MICROARRAY_DATA
--
 CREATE TABLE "DEAPP"."DE_SUBJECT_MICROARRAY_DATA" 
  (	"TRIAL_NAME" VARCHAR2(50 BYTE), 
"PROBESET_ID" NUMBER(22,0), 
"ASSAY_ID" NUMBER(18,0), 
"PATIENT_ID" NUMBER(18,0), 
"SAMPLE_ID" NUMBER(18,0), 
"SUBJECT_ID" VARCHAR2(50 BYTE), 
"RAW_INTENSITY" NUMBER(18,5), 
"LOG_INTENSITY" NUMBER(18,5), 
"ZSCORE" NUMBER(18,5), 
"NEW_RAW" NUMBER(18,4), 
"NEW_LOG" NUMBER(18,4), 
"NEW_ZSCORE" NUMBER(18,4), 
"TRIAL_SOURCE" VARCHAR2(200 BYTE)
  )
COMPRESS BASIC  NOLOGGING 
 TABLESPACE "DEAPP" 
 PARTITION BY LIST ("TRIAL_NAME") 
(PARTITION "GSE19650"  VALUES ('GSE19650') SEGMENT CREATION IMMEDIATE
COMPRESS BASIC NOLOGGING 
 TABLESPACE "DEAPP" , 
PARTITION "GSE9105"  VALUES ('GSE9105') SEGMENT CREATION IMMEDIATE
COMPRESS BASIC NOLOGGING 
 TABLESPACE "DEAPP" , 
PARTITION "GSE20685"  VALUES ('GSE20685') SEGMENT CREATION IMMEDIATE
COMPRESS BASIC NOLOGGING 
 TABLESPACE "DEAPP" , 
PARTITION "BSI201_20070102"  VALUES ('BSI201_20070102') SEGMENT CREATION IMMEDIATE
COMPRESS BASIC NOLOGGING 
 TABLESPACE "DEAPP" , 
PARTITION "GSE4382"  VALUES ('GSE4382') SEGMENT CREATION IMMEDIATE
COMPRESS BASIC NOLOGGING 
 TABLESPACE "DEAPP" , 
PARTITION "BSI201RICERCA"  VALUES ('BSI201RICERCA') SEGMENT CREATION IMMEDIATE
COMPRESS BASIC NOLOGGING 
 TABLESPACE "DEAPP" , 
PARTITION "GSE14860"  VALUES ('GSE14860') SEGMENT CREATION IMMEDIATE
COMPRESS BASIC NOLOGGING 
 TABLESPACE "DEAPP" , 
PARTITION "BSI201PHASE3"  VALUES ('BSI201PHASE3') SEGMENT CREATION IMMEDIATE
COMPRESS BASIC NOLOGGING 
 TABLESPACE "DEAPP" , 
PARTITION "GSE10846"  VALUES ('GSE10846') SEGMENT CREATION IMMEDIATE
COMPRESS BASIC NOLOGGING 
 TABLESPACE "DEAPP" , 
PARTITION "GSE22780"  VALUES ('GSE22780') SEGMENT CREATION IMMEDIATE
COMPRESS BASIC NOLOGGING 
 TABLESPACE "DEAPP" , 
PARTITION "GSE19976"  VALUES ('GSE19976') SEGMENT CREATION IMMEDIATE
COMPRESS BASIC NOLOGGING 
 TABLESPACE "DEAPP" , 
PARTITION "AGLU01602"  VALUES ('AGLU01602') SEGMENT CREATION IMMEDIATE
COMPRESS BASIC NOLOGGING 
 TABLESPACE "DEAPP" , 
PARTITION "AGLU01702"  VALUES ('AGLU01702') SEGMENT CREATION IMMEDIATE
COMPRESS BASIC NOLOGGING 
 TABLESPACE "DEAPP" , 
PARTITION "AGLU01602_PESCATORI"  VALUES ('AGLU01602_PESCATORI') SEGMENT CREATION IMMEDIATE
COMPRESS BASIC NOLOGGING 
 TABLESPACE "DEAPP" , 
PARTITION "C57_GAAKO"  VALUES ('C57_GAAKO') SEGMENT CREATION IMMEDIATE
COMPRESS BASIC NOLOGGING 
 TABLESPACE "DEAPP" , 
PARTITION "GSE23832"  VALUES ('GSE23832') SEGMENT CREATION IMMEDIATE
COMPRESS BASIC NOLOGGING 
 TABLESPACE "DEAPP" , 
PARTITION "CNS_TUMORS_GOLUB"  VALUES ('CNS_TUMORS_GOLUB') SEGMENT CREATION IMMEDIATE
COMPRESS BASIC NOLOGGING 
 TABLESPACE "DEAPP" , 
PARTITION "GSE38642:STD"  VALUES ('GSE38642:STD') SEGMENT CREATION IMMEDIATE
NOCOMPRESS NOLOGGING 
 TABLESPACE "DEAPP" , 
PARTITION "GSE38642"  VALUES ('GSE38642') SEGMENT CREATION IMMEDIATE
COMPRESS BASIC NOLOGGING 
 TABLESPACE "DEAPP" , 
PARTITION "NEURODEGENERATION:STD"  VALUES ('NEURODEGENERATION:STD') SEGMENT CREATION IMMEDIATE
NOCOMPRESS NOLOGGING 
 TABLESPACE "DEAPP" , 
PARTITION "NEURODEGENERATION"  VALUES ('NEURODEGENERATION') SEGMENT CREATION IMMEDIATE
COMPRESS BASIC NOLOGGING 
 TABLESPACE "DEAPP" , 
PARTITION "POMPE_LOTS"  VALUES ('POMPE_LOTS') SEGMENT CREATION IMMEDIATE
COMPRESS BASIC NOLOGGING 
 TABLESPACE "DEAPP" , 
PARTITION "POMPE_LOTS_TEST"  VALUES ('POMPE_LOTS_TEST') SEGMENT CREATION IMMEDIATE
COMPRESS BASIC NOLOGGING 
 TABLESPACE "DEAPP" , 
PARTITION "RICERCA"  VALUES ('RICERCA') SEGMENT CREATION IMMEDIATE
COMPRESS BASIC NOLOGGING 
 TABLESPACE "DEAPP" , 
PARTITION "GSE8581"  VALUES ('GSE8581') SEGMENT CREATION IMMEDIATE
COMPRESS BASIC NOLOGGING 
 TABLESPACE "DEAPP" , 
PARTITION "GSE8581-SAMPLES"  VALUES ('GSE8581-SAMPLES') SEGMENT CREATION IMMEDIATE
COMPRESS BASIC NOLOGGING 
 TABLESPACE "DEAPP" , 
PARTITION "GSE8581SERIES:STD"  VALUES ('GSE8581SERIES:STD') SEGMENT CREATION IMMEDIATE
COMPRESS BASIC NOLOGGING 
 TABLESPACE "DEAPP" ) ;
--
-- Type: INDEX; Owner: DEAPP; Name: DE_MICROARRAY_DATA_IDX1
--
 CREATE INDEX "DEAPP"."DE_MICROARRAY_DATA_IDX1" ON "DEAPP"."DE_SUBJECT_MICROARRAY_DATA" ("TRIAL_NAME", "ASSAY_ID", "PROBESET_ID")
 TABLESPACE "INDX"  LOCAL
(PARTITION "GSE19650"
 TABLESPACE "INDX" , 
PARTITION "GSE9105"
 TABLESPACE "INDX" , 
PARTITION "GSE20685"
 TABLESPACE "INDX" , 
PARTITION "BSI201_20070102"
 TABLESPACE "INDX" , 
PARTITION "GSE4382"
 TABLESPACE "INDX" , 
PARTITION "BSI201RICERCA"
 TABLESPACE "INDX" , 
PARTITION "GSE14860"
 TABLESPACE "INDX" , 
PARTITION "BSI201PHASE3"
 TABLESPACE "INDX" , 
PARTITION "GSE10846"
 TABLESPACE "INDX" , 
PARTITION "GSE22780"
 TABLESPACE "INDX" , 
PARTITION "GSE19976"
 TABLESPACE "INDX" , 
PARTITION "AGLU01602"
 TABLESPACE "INDX" , 
PARTITION "AGLU01702"
 TABLESPACE "INDX" , 
PARTITION "AGLU01602_PESCATORI"
 TABLESPACE "INDX" , 
PARTITION "C57_GAAKO"
 TABLESPACE "INDX" , 
PARTITION "GSE23832"
 TABLESPACE "INDX" , 
PARTITION "CNS_TUMORS_GOLUB"
 TABLESPACE "INDX" , 
PARTITION "GSE38642:STD"
 TABLESPACE "INDX" , 
PARTITION "GSE38642"
 TABLESPACE "INDX" , 
PARTITION "NEURODEGENERATION:STD"
 TABLESPACE "INDX" , 
PARTITION "NEURODEGENERATION"
 TABLESPACE "INDX" , 
PARTITION "POMPE_LOTS"
 TABLESPACE "INDX" , 
PARTITION "POMPE_LOTS_TEST"
 TABLESPACE "INDX" , 
PARTITION "RICERCA"
 TABLESPACE "INDX" , 
PARTITION "GSE8581"
 TABLESPACE "INDX" , 
PARTITION "GSE8581-SAMPLES"
 TABLESPACE "INDX" , 
PARTITION "GSE8581SERIES:STD"
 TABLESPACE "INDX" ) COMPRESS 3 ;
--
-- Type: INDEX; Owner: DEAPP; Name: DE_MICROARRAY_DATA_IDX2
--
 CREATE INDEX "DEAPP"."DE_MICROARRAY_DATA_IDX2" ON "DEAPP"."DE_SUBJECT_MICROARRAY_DATA" ("ASSAY_ID", "PROBESET_ID")
 TABLESPACE "INDX"  LOCAL
(PARTITION "GSE19650"
 TABLESPACE "INDX" , 
PARTITION "GSE9105"
 TABLESPACE "INDX" , 
PARTITION "GSE20685"
 TABLESPACE "INDX" , 
PARTITION "BSI201_20070102"
 TABLESPACE "INDX" , 
PARTITION "GSE4382"
 TABLESPACE "INDX" , 
PARTITION "BSI201RICERCA"
 TABLESPACE "INDX" , 
PARTITION "GSE14860"
 TABLESPACE "INDX" , 
PARTITION "BSI201PHASE3"
 TABLESPACE "INDX" , 
PARTITION "GSE10846"
 TABLESPACE "INDX" , 
PARTITION "GSE22780"
 TABLESPACE "INDX" , 
PARTITION "GSE19976"
 TABLESPACE "INDX" , 
PARTITION "AGLU01602"
 TABLESPACE "INDX" , 
PARTITION "AGLU01702"
 TABLESPACE "INDX" , 
PARTITION "AGLU01602_PESCATORI"
 TABLESPACE "INDX" , 
PARTITION "C57_GAAKO"
 TABLESPACE "INDX" , 
PARTITION "GSE23832"
 TABLESPACE "INDX" , 
PARTITION "CNS_TUMORS_GOLUB"
 TABLESPACE "INDX" , 
PARTITION "GSE38642:STD"
 TABLESPACE "INDX" , 
PARTITION "GSE38642"
 TABLESPACE "INDX" , 
PARTITION "NEURODEGENERATION:STD"
 TABLESPACE "INDX" , 
PARTITION "NEURODEGENERATION"
 TABLESPACE "INDX" , 
PARTITION "POMPE_LOTS"
 TABLESPACE "INDX" , 
PARTITION "POMPE_LOTS_TEST"
 TABLESPACE "INDX" , 
PARTITION "RICERCA"
 TABLESPACE "INDX" , 
PARTITION "GSE8581"
 TABLESPACE "INDX" , 
PARTITION "GSE8581-SAMPLES"
 TABLESPACE "INDX" , 
PARTITION "GSE8581SERIES:STD"
 TABLESPACE "INDX" ) COMPRESS 2 ;
