--
-- Type: TABLE; Owner: DEAPP; Name: DE_SUBJECT_PROTEIN_DATA
--
 CREATE TABLE "DEAPP"."DE_SUBJECT_PROTEIN_DATA" 
  (	"TRIAL_NAME" VARCHAR2(15 BYTE), 
"COMPONENT" VARCHAR2(15 BYTE), 
"INTENSITY" NUMBER, 
"PATIENT_ID" NUMBER(38,0), 
"SUBJECT_ID" VARCHAR2(10 BYTE), 
"GENE_SYMBOL" VARCHAR2(100 BYTE), 
"GENE_ID" NUMBER(10,0), 
"ASSAY_ID" NUMBER, 
"TIMEPOINT" VARCHAR2(20 BYTE), 
"N_VALUE" NUMBER, 
"MEAN_INTENSITY" NUMBER, 
"STDDEV_INTENSITY" NUMBER, 
"MEDIAN_INTENSITY" NUMBER, 
"ZSCORE" NUMBER
  ) SEGMENT CREATION DEFERRED
 TABLESPACE "DEAPP" ;

--
-- Type: INDEX; Owner: DEAPP; Name: DE_SUBJECT_PROTEIN_MCIDX1
--
CREATE BITMAP INDEX "DEAPP"."DE_SUBJECT_PROTEIN_MCIDX1" ON "DEAPP"."DE_SUBJECT_PROTEIN_DATA" ("TRIAL_NAME")
TABLESPACE "DEAPP" ;

--
-- Type: INDEX; Owner: DEAPP; Name: DE_SUBJECT_PROTEIN_MCIDX2
--
CREATE BITMAP INDEX "DEAPP"."DE_SUBJECT_PROTEIN_MCIDX2" ON "DEAPP"."DE_SUBJECT_PROTEIN_DATA" ("COMPONENT")
TABLESPACE "DEAPP" ;

--
-- Type: INDEX; Owner: DEAPP; Name: DE_SUBJECT_PROTEIN_MCIDX3
--
CREATE BITMAP INDEX "DEAPP"."DE_SUBJECT_PROTEIN_MCIDX3" ON "DEAPP"."DE_SUBJECT_PROTEIN_DATA" ("PATIENT_ID")
TABLESPACE "DEAPP" ;

--
-- Type: INDEX; Owner: DEAPP; Name: DE_SUBJECT_PROTEIN_MCIDX4
--
CREATE BITMAP INDEX "DEAPP"."DE_SUBJECT_PROTEIN_MCIDX4" ON "DEAPP"."DE_SUBJECT_PROTEIN_DATA" ("GENE_SYMBOL")
TABLESPACE "DEAPP" ;

