--
-- Type: TABLE; Owner: DEAPP; Name: DE_SAVED_COMPARISON
--
 CREATE TABLE "DEAPP"."DE_SAVED_COMPARISON" 
  (	"COMPARISON_ID" NUMBER NOT NULL ENABLE, 
"QUERY_ID1" NUMBER, 
"QUERY_ID2" NUMBER
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

