--
-- Type: TABLE; Owner: DEAPP; Name: DE_SNP_PROBE_SORTED_DEF_BK
--
 CREATE TABLE "DEAPP"."DE_SNP_PROBE_SORTED_DEF_BK" 
  (	"SNP_PROBE_SORTED_DEF_ID" NUMBER(22,0), 
"PLATFORM_NAME" VARCHAR2(255 BYTE), 
"NUM_PROBE" NUMBER, 
"CHROM" VARCHAR2(16 BYTE), 
"PROBE_DEF" CLOB, 
"SNP_ID_DEF" CLOB
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" 
LOB ("PROBE_DEF") STORE AS BASICFILE (
 TABLESPACE "TRANSMART" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
 NOCACHE LOGGING ) 
LOB ("SNP_ID_DEF") STORE AS BASICFILE (
 TABLESPACE "TRANSMART" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
 NOCACHE LOGGING ) ;

