--
-- Type: TABLE; Owner: DEAPP; Name: DE_SUBJECT_MICROARRAY_DATA_NEW
--
 CREATE TABLE "DEAPP"."DE_SUBJECT_MICROARRAY_DATA_NEW" 
  (	"TRIAL_SOURCE" VARCHAR2(200 BYTE), 
"TRIAL_NAME" VARCHAR2(50 BYTE), 
"PROBESET_ID" NUMBER(22,0), 
"ASSAY_ID" NUMBER(18,0), 
"PATIENT_ID" NUMBER(18,0), 
"RAW_INTENSITY" NUMBER(18,4), 
"LOG_INTENSITY" NUMBER(18,4), 
"ZSCORE" NUMBER(18,4)
  )
COMPRESS BASIC  NOLOGGING 
 TABLESPACE "DEAPP" 
 PARTITION BY LIST ("TRIAL_SOURCE") 
(PARTITION "A:A"  VALUES ('A:A') SEGMENT CREATION IMMEDIATE
NOCOMPRESS NOLOGGING 
 TABLESPACE "DEAPP" , 
PARTITION "AGLU01602:STD"  VALUES ('AGLU01602:STD') SEGMENT CREATION IMMEDIATE
COMPRESS BASIC NOLOGGING 
 TABLESPACE "DEAPP" , 
PARTITION "AGLU01602_PESCATORI:STD"  VALUES ('AGLU01602_PESCATORI:STD') SEGMENT CREATION IMMEDIATE
COMPRESS BASIC NOLOGGING 
 TABLESPACE "DEAPP" , 
PARTITION "AGLU01702:STD"  VALUES ('AGLU01702:STD') SEGMENT CREATION IMMEDIATE
COMPRESS BASIC NOLOGGING 
 TABLESPACE "DEAPP" , 
PARTITION "BSI201PHASE3:STD"  VALUES ('BSI201PHASE3:STD') SEGMENT CREATION IMMEDIATE
COMPRESS BASIC NOLOGGING 
 TABLESPACE "DEAPP" , 
PARTITION "BSI201RICERCA:STD"  VALUES ('BSI201RICERCA:STD') SEGMENT CREATION IMMEDIATE
COMPRESS BASIC NOLOGGING 
 TABLESPACE "DEAPP" ) ;
