--
-- Type: SEQUENCE; Owner: DEAPP; Name: DE_VARIANT_POPULATION_INFO_SEQ
--
CREATE SEQUENCE  "DEAPP"."DE_VARIANT_POPULATION_INFO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;

--
-- Type: TABLE; Owner: DEAPP; Name: DE_VARIANT_POPULATION_INFO
--
 CREATE TABLE "DEAPP"."DE_VARIANT_POPULATION_INFO" 
  (	"VARIANT_POPULATION_INFO_ID" NUMBER NOT NULL ENABLE, 
"DATASET_ID" VARCHAR2(50 BYTE), 
"INFO_NAME" VARCHAR2(100 BYTE), 
"DESCRIPTION" CLOB, 
"TYPE" VARCHAR2(30 BYTE), 
"NUMBER" VARCHAR2(10 BYTE), 
 CONSTRAINT "DE_VAR_POPULAT_INFO_ID_IDX" PRIMARY KEY ("VARIANT_POPULATION_INFO_ID")
 USING INDEX
 TABLESPACE "DEAPP"  ENABLE
  ) SEGMENT CREATION DEFERRED
 TABLESPACE "DEAPP" 
LOB ("DESCRIPTION") STORE AS BASICFILE (
 TABLESPACE "DEAPP" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
 NOCACHE LOGGING ) ;

--
-- Type: INDEX; Owner: DEAPP; Name: VAR_POPULAT_INFO_DATASET_NAME
--
CREATE INDEX "DEAPP"."VAR_POPULAT_INFO_DATASET_NAME" ON "DEAPP"."DE_VARIANT_POPULATION_INFO" ("DATASET_ID", "INFO_NAME")
TABLESPACE "DEAPP" ;

--
-- Type: TRIGGER; Owner: DEAPP; Name: TRG_DE_VP_INFO_ID
--
  CREATE OR REPLACE TRIGGER "DEAPP"."TRG_DE_VP_INFO_ID" 
before insert on deapp.de_variant_population_info
for each row begin
       	if inserting then
               	if :NEW.variant_population_info_id is null then
                       	select de_variant_population_info_seq.nextval into :NEW.variant_population_info_id from dual;
               	end if;
       	end if;
end;
/
ALTER TRIGGER "DEAPP"."TRG_DE_VP_INFO_ID" ENABLE;
 
