--
-- Type: TABLE; Owner: DEAPP; Name: GPL2004_5
--
 CREATE TABLE "DEAPP"."GPL2004_5" 
  (	"SNP_ID" VARCHAR2(50 BYTE), 
"RS_ID" VARCHAR2(50 BYTE), 
"CHROM" VARCHAR2(2 BYTE), 
"POS" NUMBER(20,0)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

