--
-- Type: TABLE; Owner: BIOMART_USER; Name: GENE_ONTOLOGY
--
 CREATE TABLE "BIOMART_USER"."GENE_ONTOLOGY" 
  (	"PATHWAY" VARCHAR2(100 BYTE), 
"DESCR" VARCHAR2(500 BYTE)
  ) SEGMENT CREATION IMMEDIATE
NOCOMPRESS LOGGING
 TABLESPACE "TRANSMART" ;
