--
-- Type: TABLE; Owner: BIOMART_USER; Name: QUERIES
--
CREATE TABLE "BIOMART_USER"."QUERIES"
(
    "ID" NUMBER NOT NULL ENABLE,
    "USERNAME" VARCHAR2(50 BYTE) NOT NULL,
    "PATIENTS_QUERY" CLOB,
    "OBSERVATIONS_QUERY" CLOB,
    "API_VERSION" VARCHAR2(25 BYTE),
    "BOOKMARKED" CHAR(1 BYTE),
    "DELETED" CHAR(1 BYTE),
    "CREATE_DATE" TIMESTAMP (6),
    "UPDATE_DATE" TIMESTAMP (6),
    PRIMARY KEY ("ID")
);

--
-- Type: INDEX; Owner: BIOMART_USER; Name: QUERIES_USER
--
CREATE INDEX "BIOMART_USER"."QUERIES_USER" ON "BIOMART_USER"."QUERIES" ("USERNAME")
TABLESPACE "TRANSMART" ;

--
-- Type: SEQUENCE; Owner: BIOMART_USER; Name: QUERIES_ID
--
CREATE SEQUENCE  "BIOMART_USER"."QUERIES_ID";

--
-- Type: TRIGGER; Owner: BIOMART_USER; Name: TRG_QUERIES_ID
--
  CREATE OR REPLACE TRIGGER "BIOMART_USER"."TRG_QUERIES_ID" 
	 before insert on "QUERIES"
	 for each row begin
	 if inserting then
	 if :NEW."ID" is null then
	 select QUERIES_ID.nextval into :NEW."ID" from dual;
	 end if;
	 end if;
	 end;

/
ALTER TRIGGER "BIOMART_USER"."TRG_QUERIES_ID" ENABLE;
