\i i2b2demodata/prelude.sql
\i i2b2demodata/functions/create_temp_concept_table.sql
\i i2b2demodata/functions/create_temp_eid_table.sql
\i i2b2demodata/functions/create_temp_modifier_table.sql
\i i2b2demodata/functions/create_temp_patient_table.sql
\i i2b2demodata/functions/create_temp_pid_table.sql
\i i2b2demodata/functions/create_temp_provider_table.sql
\i i2b2demodata/functions/create_temp_table.sql
\i i2b2demodata/functions/create_temp_visit_table.sql
\i i2b2demodata/functions/insert_concept_fromtemp.sql
\i i2b2demodata/functions/insert_eid_map_fromtemp.sql
\i i2b2demodata/functions/insert_encountervisit_fromtemp.sql
\i i2b2demodata/functions/insert_modifier_fromtemp.sql
\i i2b2demodata/functions/insert_patient_map_fromtemp.sql
\i i2b2demodata/functions/insert_pid_map_fromtemp.sql
\i i2b2demodata/functions/insert_provider_fromtemp.sql
\i i2b2demodata/functions/remove_temp_table.sql
\i i2b2demodata/functions/sp_xtab.sql
\i i2b2demodata/functions/sync_clear_concept_table.sql
\i i2b2demodata/functions/sync_clear_modifier_table.sql
\i i2b2demodata/functions/sync_clear_provider_table.sql
\i i2b2demodata/functions/update_observation_fact.sql
\i i2b2demodata/archive_observation_fact.sql
\i i2b2demodata/async_job.sql
\i i2b2demodata/cd.sql
\i i2b2demodata/code_lookup.sql
\i i2b2demodata/concept_counts.sql
\i i2b2demodata/concept_dimension.sql
\i i2b2demodata/counter.sql
\i i2b2demodata/crc_db_lookup.sql
\i i2b2demodata/datamart_report.sql
\i i2b2demodata/dimloader.sql
\i i2b2demodata/encounter_mapping.sql
\i i2b2demodata/hilosequences.sql
\i i2b2demodata/jms_messages.sql
\i i2b2demodata/jms_roles.sql
\i i2b2demodata/jms_subscriptions.sql
\i i2b2demodata/jms_transactions.sql
\i i2b2demodata/jms_users.sql
\i i2b2demodata/map.sql
\i i2b2demodata/modifier_dimension.sql
\i i2b2demodata/modifier_metadata.sql
\i i2b2demodata/views/modifier_dimension_view.sql
\i i2b2demodata/news_updates.sql
\i i2b2demodata/observation_fact.sql
\i i2b2demodata/patient_dimension.sql
\i i2b2demodata/patient_mapping.sql
\i i2b2demodata/patient_trial.sql
\i i2b2demodata/provider_dimension.sql
\i i2b2demodata/qt_analysis_plugin.sql
\i i2b2demodata/qt_analysis_plugin_result_type.sql
\i i2b2demodata/qt_breakdown_path.sql
\i i2b2demodata/qt_query_master.sql
\i i2b2demodata/qt_query_status_type.sql
\i i2b2demodata/qt_query_instance.sql
\i i2b2demodata/qt_query_result_type.sql
\i i2b2demodata/qt_query_result_instance.sql
\i i2b2demodata/qt_patient_enc_collection.sql
\i i2b2demodata/qt_patient_sample_collection.sql
\i i2b2demodata/qt_patient_set_collection.sql
\i i2b2demodata/qt_pdo_query_master.sql
\i i2b2demodata/qt_privilege.sql
\i i2b2demodata/qt_xml_result.sql
\i i2b2demodata/ricerca.sql
\i i2b2demodata/sample_categories.sql
\i i2b2demodata/sample_dimension.sql
\i i2b2demodata/set_type.sql
\i i2b2demodata/set_upload_status.sql
\i i2b2demodata/source_master.sql
\i i2b2demodata/timers.sql
\i i2b2demodata/upload_status.sql
\i i2b2demodata/visit_dimension.sql
\i i2b2demodata/_misc.sql
