\ir prelude.sql
\ir functions/create_temp_concept_table.sql
\ir functions/create_temp_eid_table.sql
\ir functions/create_temp_patient_table.sql
\ir functions/create_temp_pid_table.sql
\ir functions/create_temp_provider_table.sql
\ir functions/create_temp_table.sql
\ir functions/create_temp_visit_table.sql
\ir functions/insert_concept_fromtemp.sql
\ir functions/insert_eid_map_fromtemp.sql
\ir functions/insert_encountervisit_fromtemp.sql
\ir functions/insert_modifier_fromtemp.sql
\ir functions/insert_patient_map_fromtemp.sql
\ir functions/insert_pid_map_fromtemp.sql
\ir functions/insert_provider_fromtemp.sql
\ir functions/remove_temp_table.sql
\ir functions/sync_clear_concept_table.sql
\ir functions/sync_clear_provider_table.sql
\ir functions/update_observation_fact.sql
\ir archive_observation_fact.sql
\ir async_job.sql
\ir code_lookup.sql
\ir concept_counts.sql
\ir concept_dimension.sql
\ir datamart_report.sql
\ir encounter_mapping.sql
\ir modifier_dimension.sql
\ir news_updates.sql
\ir observation_fact.sql
\ir patient_dimension.sql
\ir patient_mapping.sql
\ir patient_trial.sql
\ir provider_dimension.sql
\ir qt_analysis_plugin.sql
\ir qt_analysis_plugin_result_type.sql
\ir qt_breakdown_path.sql
\ir qt_query_master.sql
\ir qt_query_status_type.sql
\ir qt_query_instance.sql
\ir qt_query_result_type.sql
\ir qt_query_result_instance.sql
\ir qt_patient_enc_collection.sql
\ir qt_patient_set_collection.sql
\ir qt_pdo_query_master.sql
\ir qt_privilege.sql
\ir qt_xml_result.sql
\ir sample_categories.sql
\ir set_type.sql
\ir set_upload_status.sql
\ir source_master.sql
\ir upload_status.sql
\ir visit_dimension.sql
\ir _misc.sql
