<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="transmart" nsURI="http://www.example.org/transmart" nsPrefix="transmart">
  <eClassifiers xsi:type="ecore:EClass" name="Patient">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subjectIds" upperBound="-1"
        eType="#//PatientMapping"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sex" eType="#//Sex"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Observation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="patient" lowerBound="1"
        eType="#//Patient"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="trialVisit" lowerBound="1"
        eType="#//TrialVisit"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="visit" eType="#//Visit"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="concept" lowerBound="1"
        eType="#//Concept"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valueType" lowerBound="1"
        eType="#//ValueType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="textValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="categoricalValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dateValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startDate" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="metadata" upperBound="-1"
        eType="#//ObservationMetadata" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Concept">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="conceptCode" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" unique="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="conceptPath" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PatientMapping">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="source" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ValueType">
    <eLiterals name="Numerical"/>
    <eLiterals name="Categorical"/>
    <eLiterals name="Text"/>
    <eLiterals name="Date"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Visit">
    <eStructuralFeatures xsi:type="ecore:EReference" name="patient" lowerBound="1"
        eType="#//Patient" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="encounterIds" upperBound="-1"
        eType="#//EncounterMapping"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Sex">
    <eLiterals name="Male" literal="male"/>
    <eLiterals name="Female" literal="female"/>
    <eLiterals name="Unknown" literal="unknown"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObservationMetadata">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modifierCode" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valueType" lowerBound="1"
        eType="#//ValueType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="textValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="categoricalValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dateValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TrialVisit">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="relTimeUnit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="relTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="relTimeLabel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="study" lowerBound="1" eType="#//Study"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Study">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="studyId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TreeNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//TreeNode"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="study" eType="#//Study"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="concept" eType="#//Concept"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visualAttributes" upperBound="3"
        eType="#//VisualAttribute"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="VisualAttribute">
    <eLiterals name="Leaf"/>
    <eLiterals name="Folder"/>
    <eLiterals name="Container"/>
    <eLiterals name="Study"/>
    <eLiterals name="Numerical"/>
    <eLiterals name="Text"/>
    <eLiterals name="Date"/>
    <eLiterals name="Categorical"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EncounterMapping">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="source" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
