--
-- Type: TABLE; Owner: I2B2METADATA; Name: ONT_DB_LOOKUP
--
 CREATE TABLE "I2B2METADATA"."ONT_DB_LOOKUP" 
  (	"C_DOMAIN_ID" VARCHAR2(255 BYTE), 
"C_PROJECT_PATH" VARCHAR2(255 BYTE), 
"C_OWNER_ID" VARCHAR2(255 BYTE), 
"C_DB_FULLSCHEMA" VARCHAR2(255 BYTE), 
"C_DB_DATASOURCE" VARCHAR2(255 BYTE), 
"C_DB_SERVERTYPE" VARCHAR2(255 BYTE), 
"C_DB_NICENAME" VARCHAR2(255 BYTE), 
"C_DB_TOOLTIP" VARCHAR2(255 BYTE), 
"C_COMMENT" CLOB, 
"C_ENTRY_DATE" DATE, 
"C_CHANGE_DATE" DATE, 
"C_STATUS_CD" CHAR(1 BYTE)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" 
LOB ("C_COMMENT") STORE AS BASICFILE (
 TABLESPACE "TRANSMART" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
 NOCACHE LOGGING ) ;

