--
-- Type: TABLE; Owner: I2B2METADATA; Name: SCHEMES
--
 CREATE TABLE "I2B2METADATA"."SCHEMES" 
  (	"C_KEY" VARCHAR2(50 BYTE), 
"C_NAME" VARCHAR2(50 BYTE), 
"C_DESCRIPTION" VARCHAR2(100 BYTE)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "I2B2_DATA" ;
