--
-- Type: TABLE; Owner: I2B2METADATA; Name: TMP_SECURE_TOKEN
--
 CREATE TABLE "I2B2METADATA"."TMP_SECURE_TOKEN" 
  (	"SOURCESYSTEM_CD" VARCHAR2(50 BYTE), 
"SECURE_OBJ_TOKEN" VARCHAR2(50 BYTE)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

