\i fmapp/prelude.sql
\i fmapp/functions/fm_file_uid.sql
\i fmapp/functions/fm_folder_uid.sql
\i fmapp/functions/fm_get_folder_full_name.sql
\i fmapp/functions/fm_update_folder_full_name.sql
\i fmapp/fm_data_uid.sql
\i fmapp/fm_folder.sql
\i fmapp/fm_folder_association.sql
\i fmapp/fm_file.sql
\i fmapp/fm_folder_file_association.sql
