#!/bin/bash

# caller should define the appropriate postgresql env variables
# (PGDATABASE, PGUSER and so on)

function dump_table {
  local readonly table=$1

  psql <<< "\\COPY $1 TO ${1##*.}.tsv WITH (FORMAT csv, DELIMITER E'\t', NULL '', HEADER)"
}

dump_table i2b2demodata.modifier_dimension
dump_table i2b2demodata.modifier_metadata
