\i deapp/prelude.sql
\i deapp/de_gpl_info.sql
\i deapp/de_chromosomal_region.sql
\i deapp/de_mrna_annotation.sql
\i deapp/de_pathway.sql
\i deapp/de_pathway_gene.sql
\i deapp/de_saved_comparison.sql
\i deapp/de_snp_calls_by_gsm.sql
\i deapp/de_snp_copy_number.sql
\i deapp/de_snp_data_by_patient.sql
\i deapp/de_snp_data_by_probe.sql
\i deapp/de_snp_data_dataset_loc.sql
\i deapp/de_snp_gene_map.sql
\i deapp/de_snp_info.sql
\i deapp/de_snp_probe.sql
\i deapp/de_snp_probe_sorted_def.sql
\i deapp/de_snp_subject_sorted_def.sql
\i deapp/de_subject_acgh_data.sql
\i deapp/de_subject_microarray_data.sql
\i deapp/de_subject_microarray_logs.sql
\i deapp/de_subject_microarray_med.sql
\i deapp/de_subject_protein_data.sql
\i deapp/de_subject_rbm_data.sql
\i deapp/de_subject_sample_mapping.sql
\i deapp/de_subject_snp_dataset.sql
\i deapp/de_xtrial_child_map.sql
\i deapp/de_xtrial_parent_names.sql
\i deapp/deapp_annotation.sql
\i deapp/haploview_data.sql
\i deapp/_misc.sql
