\ir prelude.sql
\ir de_gpl_info.sql
\ir de_chromosomal_region.sql
\ir de_mrna_annotation.sql
\ir de_pathway.sql
\ir de_pathway_gene.sql
\ir de_saved_comparison.sql
\ir de_snp_calls_by_gsm.sql
\ir de_snp_copy_number.sql
\ir de_snp_data_by_patient.sql
\ir de_snp_data_by_probe.sql
\ir de_snp_data_dataset_loc.sql
\ir de_snp_gene_map.sql
\ir de_snp_info.sql
\ir de_snp_probe.sql
\ir de_snp_probe_sorted_def.sql
\ir de_snp_subject_sorted_def.sql
\ir de_subject_acgh_data.sql
\ir de_subject_microarray_data.sql
\ir de_subject_microarray_logs.sql
\ir de_subject_microarray_med.sql
\ir de_subject_protein_data.sql
\ir de_subject_rbm_data.sql
\ir de_subject_sample_mapping.sql
\ir de_subject_snp_dataset.sql
\ir de_xtrial_child_map.sql
\ir de_xtrial_parent_names.sql
\ir deapp_annotation.sql
\ir haploview_data.sql
\ir _misc.sql
