--
-- Type: TABLE; Owner: BIOMART; Name: ASSAY_ANALYSIS_DATA
--
 CREATE TABLE "BIOMART"."ASSAY_ANALYSIS_DATA" 
  (	"BIO_ASY_ANALYSIS_DATA_ID" NUMBER(18,0), 
"BIO_EXPERIMENT_ID" NUMBER(18,0), 
"BIO_ASSAY_PLATFORM_ID" NUMBER(18,0), 
"BIO_ASSAY_ANALYSIS_ID" NUMBER(18,0), 
"BIO_ASSAY_FEATURE_GROUP_ID" NUMBER(18,0), 
"FEATURE_GROUP_NAME" VARCHAR2(100 BYTE), 
"TEA_NORMALIZED_PVALUE" NUMBER(18,5), 
"FOLD_CHANGE_RATIO" NUMBER, 
"RAW_PVALUE" NUMBER(18,5), 
"ADJUSTED_PVALUE" NUMBER(18,5), 
"PREFERRED_PVALUE" NUMBER(18,5)
  )
 TABLESPACE "BIOMART" 
 PARTITION BY HASH ("BIO_EXPERIMENT_ID") 
(PARTITION "SYS_P61" 
  TABLESPACE "BIOMART" , 
PARTITION "SYS_P62" 
  TABLESPACE "BIOMART" , 
PARTITION "SYS_P63" 
  TABLESPACE "BIOMART" , 
PARTITION "SYS_P64" 
  TABLESPACE "BIOMART" , 
PARTITION "SYS_P65" 
  TABLESPACE "BIOMART" , 
PARTITION "SYS_P66" 
  TABLESPACE "BIOMART" , 
PARTITION "SYS_P67" 
  TABLESPACE "BIOMART" , 
PARTITION "SYS_P68" 
  TABLESPACE "BIOMART" , 
PARTITION "SYS_P69" 
  TABLESPACE "BIOMART" , 
PARTITION "SYS_P70" 
  TABLESPACE "BIOMART" ) ;

