--
-- Type: TABLE; Owner: BIOMART; Name: BIO_LIT_INT_MODEL_MV
--
 CREATE TABLE "BIOMART"."BIO_LIT_INT_MODEL_MV" 
  (	"BIO_LIT_INT_DATA_ID" NUMBER(18,0), 
"EXPERIMENTAL_MODEL" NVARCHAR2(250)
  ) SEGMENT CREATION DEFERRED
NOCOMPRESS NOLOGGING
 TABLESPACE "BIOMART" ;
