--
-- Type: TABLE; Owner: BIOMART; Name: BIO_ASSAY_ANALYSIS_GWAS
--
 CREATE TABLE "BIOMART"."BIO_ASSAY_ANALYSIS_GWAS" 
  (	"BIO_ASY_ANALYSIS_GWAS_ID" NUMBER(18,0) NOT NULL ENABLE, 
"BIO_ASSAY_ANALYSIS_ID" NUMBER(18,0) NOT NULL ENABLE, 
"RS_ID" NVARCHAR2(50), 
"P_VALUE_CHAR" VARCHAR2(100 BYTE), 
"P_VALUE" BINARY_DOUBLE, 
"LOG_P_VALUE" BINARY_DOUBLE, 
"ETL_ID" NUMBER(18,0), 
"EXT_DATA" VARCHAR2(4000 BYTE)
  )
COMPRESS BASIC  NOLOGGING 
 TABLESPACE "TRANSMART" 
 PARTITION BY LIST ("BIO_ASSAY_ANALYSIS_ID") 
(PARTITION "1"  VALUES (1) SEGMENT CREATION DEFERRED
COMPRESS BASIC NOLOGGING 
 TABLESPACE "TRANSMART" , 
PARTITION "393525752"  VALUES (393525752) SEGMENT CREATION IMMEDIATE
COMPRESS BASIC NOLOGGING 
 TABLESPACE "TRANSMART" , 
PARTITION "393525754"  VALUES (393525754) SEGMENT CREATION IMMEDIATE
COMPRESS BASIC NOLOGGING 
 TABLESPACE "TRANSMART" , 
PARTITION "393525758"  VALUES (393525758) SEGMENT CREATION IMMEDIATE
COMPRESS BASIC NOLOGGING 
 TABLESPACE "TRANSMART" , 
PARTITION "393525756"  VALUES (393525756) SEGMENT CREATION IMMEDIATE
COMPRESS BASIC NOLOGGING 
 TABLESPACE "TRANSMART" , 
PARTITION "393525760"  VALUES (393525760) SEGMENT CREATION IMMEDIATE
COMPRESS BASIC NOLOGGING 
 TABLESPACE "TRANSMART" ) ;
