--
-- Type: TABLE; Owner: BIOMART; Name: BIO_MARKER_CORREL_MV
--
 CREATE TABLE "BIOMART"."BIO_MARKER_CORREL_MV" 
  (	"BIO_MARKER_ID" NUMBER(18,0), 
"ASSO_BIO_MARKER_ID" NUMBER(18,0), 
"CORREL_TYPE" VARCHAR2(18 BYTE), 
"MV_ID" NUMBER
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "BIOMART" ;

