--
-- Type: TABLE; Owner: BIOMART; Name: BIO_ASSAY_ANALYSIS_DATA_TEA
--
 CREATE TABLE "BIOMART"."BIO_ASSAY_ANALYSIS_DATA_TEA" 
  (	"BIO_ASY_ANALYSIS_DATA_ID" NUMBER, 
"FOLD_CHANGE_RATIO" NUMBER, 
"R_VALUE" NUMBER(18,5), 
"RHO_VALUE" NUMBER(18,5), 
"BIO_ASSAY_ANALYSIS_ID" NUMBER(18,0), 
"ADJUSTED_P_VALUE_CODE" NVARCHAR2(100), 
"FEATURE_GROUP_NAME" VARCHAR2(100 BYTE), 
"BIO_EXPERIMENT_ID" NUMBER(18,0), 
"BIO_ASSAY_PLATFORM_ID" NUMBER(18,0), 
"ETL_ID" NVARCHAR2(100), 
"CUT_VALUE" NUMBER(18,5), 
"RESULTS_VALUE" NVARCHAR2(100), 
"NUMERIC_VALUE" NUMBER(18,5), 
"NUMERIC_VALUE_CODE" NVARCHAR2(50), 
"TEA_NORMALIZED_PVALUE" NUMBER(18,5), 
"BIO_EXPERIMENT_TYPE" VARCHAR2(50 BYTE), 
"BIO_ASSAY_FEATURE_GROUP_ID" NUMBER(18,0), 
"TEA_RANK" NUMBER(18,0), 
"RAW_PVALUE" BINARY_DOUBLE, 
"ADJUSTED_PVALUE" BINARY_DOUBLE, 
"PREFERRED_PVALUE" BINARY_DOUBLE
  ) SEGMENT CREATION DEFERRED
 TABLESPACE "BIOMART" ;

--
-- Type: INDEX; Owner: BIOMART; Name: BAAD_IDX_TEA_PROBE_ID
--
CREATE INDEX "BIOMART"."BAAD_IDX_TEA_PROBE_ID" ON "BIOMART"."BIO_ASSAY_ANALYSIS_DATA_TEA" ("BIO_ASSAY_FEATURE_GROUP_ID", "BIO_ASY_ANALYSIS_DATA_ID")
TABLESPACE "BIOMART" ;

--
-- Type: INDEX; Owner: BIOMART; Name: BAAD_IDX_TEA_ANALYSIS
--
CREATE INDEX "BIOMART"."BAAD_IDX_TEA_ANALYSIS" ON "BIOMART"."BIO_ASSAY_ANALYSIS_DATA_TEA" ("BIO_ASSAY_ANALYSIS_ID", "BIO_ASY_ANALYSIS_DATA_ID")
TABLESPACE "BIOMART" ;

--
-- Type: INDEX; Owner: BIOMART; Name: BAAD_IDX_TEA_EXP_ANALYSIS1
--
CREATE INDEX "BIOMART"."BAAD_IDX_TEA_EXP_ANALYSIS1" ON "BIOMART"."BIO_ASSAY_ANALYSIS_DATA_TEA" ("BIO_EXPERIMENT_ID", "BIO_ASSAY_ANALYSIS_ID", "BIO_ASY_ANALYSIS_DATA_ID")
TABLESPACE "BIOMART" ;

--
-- Type: INDEX; Owner: BIOMART; Name: BAAD_IDX_TEA_PROBE_NAME
--
CREATE INDEX "BIOMART"."BAAD_IDX_TEA_PROBE_NAME" ON "BIOMART"."BIO_ASSAY_ANALYSIS_DATA_TEA" ("FEATURE_GROUP_NAME", "BIO_ASY_ANALYSIS_DATA_ID")
TABLESPACE "BIOMART" ;

--
-- Type: INDEX; Owner: BIOMART; Name: BAAD_IDX_TEA_PROBE_ANALYSIS
--
CREATE INDEX "BIOMART"."BAAD_IDX_TEA_PROBE_ANALYSIS" ON "BIOMART"."BIO_ASSAY_ANALYSIS_DATA_TEA" ("BIO_ASSAY_FEATURE_GROUP_ID", "BIO_ASSAY_ANALYSIS_ID")
TABLESPACE "BIOMART" ;

--
-- Type: INDEX; Owner: BIOMART; Name: BAAD_IDX_TEA_EXP_ANALYSIS
--
CREATE INDEX "BIOMART"."BAAD_IDX_TEA_EXP_ANALYSIS" ON "BIOMART"."BIO_ASSAY_ANALYSIS_DATA_TEA" ("BIO_EXPERIMENT_ID", "BIO_ASSAY_ANALYSIS_ID")
TABLESPACE "BIOMART" ;

--
-- Type: INDEX; Owner: BIOMART; Name: BAAD_IDX_TEA_EXPERIMENT_TYPE
--
CREATE INDEX "BIOMART"."BAAD_IDX_TEA_EXPERIMENT_TYPE" ON "BIOMART"."BIO_ASSAY_ANALYSIS_DATA_TEA" ("BIO_EXPERIMENT_TYPE", "BIO_ASY_ANALYSIS_DATA_ID")
TABLESPACE "BIOMART" ;

