--
-- Type: TABLE; Owner: BIOMART; Name: BIO_ASSAY_ANALYSIS_GWAS
--
 CREATE TABLE "BIOMART"."BIO_ASSAY_ANALYSIS_GWAS" 
  (	"BIO_ASY_ANALYSIS_GWAS_ID" NUMBER, 
"BIO_ASSAY_ANALYSIS_ID" NUMBER, 
"RS_ID" VARCHAR2(50 BYTE), 
"P_VALUE_CHAR" VARCHAR2(100 BYTE), 
"ETL_ID" NUMBER, 
"EXT_DATA" VARCHAR2(4000 BYTE), 
"P_VALUE" FLOAT(126), 
"LOG_P_VALUE" FLOAT(126)
  ) SEGMENT CREATION DEFERRED
 TABLESPACE "BIOMART" ;

