--
-- Type: TABLE; Owner: BIOMART; Name: BIO_ASSAY_ANALYSIS_EXT
--
 CREATE TABLE "BIOMART"."BIO_ASSAY_ANALYSIS_EXT" 
  (	"BIO_ASSAY_ANALYSIS_EXT_ID" NUMBER NOT NULL ENABLE, 
"BIO_ASSAY_ANALYSIS_ID" NUMBER NOT NULL ENABLE, 
"VENDOR" VARCHAR2(500 BYTE), 
"VENDOR_TYPE" VARCHAR2(500 BYTE), 
"GENOME_VERSION" VARCHAR2(500 BYTE), 
"TISSUE" VARCHAR2(500 BYTE), 
"CELL_TYPE" VARCHAR2(500 BYTE), 
"POPULATION" VARCHAR2(500 BYTE), 
"RESEARCH_UNIT" VARCHAR2(500 BYTE), 
"SAMPLE_SIZE" VARCHAR2(500 BYTE), 
"MODEL_NAME" VARCHAR2(100 BYTE), 
"MODEL_DESC" VARCHAR2(500 BYTE), 
"SENSITIVE_FLAG" NUMBER(*,0), 
"SENSITIVE_DESC" VARCHAR2(500 BYTE)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

--
-- Type: INDEX; Owner: BIOMART; Name: BIO_ASSAY_ANALYSIS_EXT_IDX1
--
CREATE INDEX "BIOMART"."BIO_ASSAY_ANALYSIS_EXT_IDX1" ON "BIOMART"."BIO_ASSAY_ANALYSIS_EXT" ("BIO_ASSAY_ANALYSIS_ID")
TABLESPACE "INDX" ;

