--
-- Type: TABLE; Owner: BIOMART; Name: BIO_DATA_OBSERVATION
--
 CREATE TABLE "BIOMART"."BIO_DATA_OBSERVATION" 
  (	"BIO_DATA_ID" NUMBER NOT NULL ENABLE, 
"BIO_OBSERVATION_ID" NUMBER NOT NULL ENABLE, 
"ETL_SOURCE" VARCHAR2(100 BYTE)
  ) SEGMENT CREATION DEFERRED
 TABLESPACE "TRANSMART" ;

