--
-- Type: TABLE; Owner: BIOMART; Name: BIO_ASSAY_ANALYSIS_DATA
--
 CREATE TABLE "BIOMART"."BIO_ASSAY_ANALYSIS_DATA" 
  (	"BIO_ASY_ANALYSIS_DATA_ID" NUMBER, 
"FOLD_CHANGE_RATIO" NUMBER, 
"R_VALUE" NUMBER(18,5), 
"RHO_VALUE" NUMBER(18,5), 
"BIO_ASSAY_ANALYSIS_ID" NUMBER(18,0), 
"ADJUSTED_P_VALUE_CODE" NVARCHAR2(100), 
"FEATURE_GROUP_NAME" VARCHAR2(100 BYTE), 
"BIO_EXPERIMENT_ID" NUMBER(18,0), 
"BIO_ASSAY_PLATFORM_ID" NUMBER(18,0), 
"ETL_ID" NVARCHAR2(100), 
"CUT_VALUE" NUMBER(18,5), 
"RESULTS_VALUE" NVARCHAR2(100), 
"NUMERIC_VALUE" NUMBER(18,5), 
"NUMERIC_VALUE_CODE" NVARCHAR2(50), 
"TEA_NORMALIZED_PVALUE" NUMBER(18,5), 
"BIO_ASSAY_FEATURE_GROUP_ID" NUMBER(18,0), 
"RAW_PVALUE" BINARY_DOUBLE, 
"PREFERRED_PVALUE" BINARY_DOUBLE, 
"ADJUSTED_PVALUE" BINARY_DOUBLE, 
"PROBESET_ID" NUMBER(22,0)
  ) SEGMENT CREATION DEFERRED
 TABLESPACE "BIOMART" ;

--
-- Type: TRIGGER; Owner: BIOMART; Name: TRG_BIO_ASY_ANALYSIS_DATA_ID
--
  CREATE OR REPLACE TRIGGER "BIOMART"."TRG_BIO_ASY_ANALYSIS_DATA_ID" 
 before insert on "BIOMART"."BIO_ASSAY_ANALYSIS_DATA"    
 for each row begin     
  if inserting then       
    if :NEW."BIO_ASY_ANALYSIS_DATA_ID" is null then          
      select SEQ_BIO_DATA_ID.nextval into :NEW."BIO_ASY_ANALYSIS_DATA_ID" from dual;       
    end if;    
  end if; 
 end;
/
ALTER TRIGGER "BIOMART"."TRG_BIO_ASY_ANALYSIS_DATA_ID" ENABLE;
 
--
-- Type: INDEX; Owner: BIOMART; Name: BAAD_IDX4
--
CREATE INDEX "BIOMART"."BAAD_IDX4" ON "BIOMART"."BIO_ASSAY_ANALYSIS_DATA" ("BIO_ASSAY_PLATFORM_ID")
TABLESPACE "BIOMART" ;

--
-- Type: INDEX; Owner: BIOMART; Name: BAAD_IDX6
--
CREATE INDEX "BIOMART"."BAAD_IDX6" ON "BIOMART"."BIO_ASSAY_ANALYSIS_DATA" ("BIO_EXPERIMENT_ID", "BIO_ASSAY_ANALYSIS_ID")
TABLESPACE "BIOMART" ;

--
-- Type: INDEX; Owner: BIOMART; Name: BAAD_IDX7
--
CREATE INDEX "BIOMART"."BAAD_IDX7" ON "BIOMART"."BIO_ASSAY_ANALYSIS_DATA" ("BIO_ASSAY_ANALYSIS_ID", "BIO_ASY_ANALYSIS_DATA_ID")
TABLESPACE "BIOMART" ;

--
-- Type: INDEX; Owner: BIOMART; Name: BAAD_IDX1
--
CREATE BITMAP INDEX "BIOMART"."BAAD_IDX1" ON "BIOMART"."BIO_ASSAY_ANALYSIS_DATA" ("BIO_ASSAY_FEATURE_GROUP_ID", "BIO_EXPERIMENT_ID")
TABLESPACE "BIOMART" ;

--
-- Type: INDEX; Owner: BIOMART; Name: BAAD_IDX14
--
CREATE INDEX "BIOMART"."BAAD_IDX14" ON "BIOMART"."BIO_ASSAY_ANALYSIS_DATA" ("BIO_ASSAY_FEATURE_GROUP_ID", "BIO_ASY_ANALYSIS_DATA_ID")
TABLESPACE "BIOMART" ;

--
-- Type: INDEX; Owner: BIOMART; Name: BAAD_IDX12
--
CREATE INDEX "BIOMART"."BAAD_IDX12" ON "BIOMART"."BIO_ASSAY_ANALYSIS_DATA" ("BIO_EXPERIMENT_ID", "BIO_ASSAY_ANALYSIS_ID", "BIO_ASSAY_FEATURE_GROUP_ID")
TABLESPACE "BIOMART" ;

--
-- Type: INDEX; Owner: BIOMART; Name: BAAD_IDX11
--
CREATE INDEX "BIOMART"."BAAD_IDX11" ON "BIOMART"."BIO_ASSAY_ANALYSIS_DATA" ("BIO_EXPERIMENT_ID", "BIO_ASSAY_ANALYSIS_ID", "BIO_ASY_ANALYSIS_DATA_ID")
TABLESPACE "BIOMART" ;

--
-- Type: INDEX; Owner: BIOMART; Name: BAD_IDX13
--
CREATE INDEX "BIOMART"."BAD_IDX13" ON "BIOMART"."BIO_ASSAY_ANALYSIS_DATA" ("BIO_ASSAY_ANALYSIS_ID", "BIO_ASSAY_FEATURE_GROUP_ID")
TABLESPACE "BIOMART" ;

--
-- Type: INDEX; Owner: BIOMART; Name: BAAD_FGN_IDX
--
CREATE INDEX "BIOMART"."BAAD_FGN_IDX" ON "BIOMART"."BIO_ASSAY_ANALYSIS_DATA" ("FEATURE_GROUP_NAME")
TABLESPACE "BIOMART" ;

