--
-- Type: TABLE; Owner: BIOMART; Name: CTD_STUDY
--
 CREATE TABLE "BIOMART"."CTD_STUDY" 
  (	"CTD_STUDY_ID" NUMBER, 
"REF_ARTICLE_PROTOCOL_ID" VARCHAR2(4000 BYTE), 
"REF_ARTICLE_PMID" VARCHAR2(4000 BYTE), 
"REF_PROTOCOL_ID" VARCHAR2(4000 BYTE)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

