--
-- Type: TABLE; Owner: BIOMART; Name: CTD_DRUG_INHIB
--
 CREATE TABLE "BIOMART"."CTD_DRUG_INHIB" 
  (	"CTD_STUDY_ID" NUMBER, 
"DRUG_INHIBITOR_COMMON_NAME" VARCHAR2(4000 BYTE), 
"DRUG_INHIBITOR_STANDARD_NAME" VARCHAR2(4000 BYTE), 
"DRUG_INHIBITOR_CAS_ID" VARCHAR2(4000 BYTE)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

