--
-- Type: TABLE; Owner: BIOMART; Name: GSE_PROBESET
--
 CREATE TABLE "BIOMART"."GSE_PROBESET" 
  (	"NAME" VARCHAR2(100 BYTE), 
"PLATFORM" VARCHAR2(100 BYTE), 
"PROBESET" VARCHAR2(100 BYTE)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" 
 PARALLEL ;

