--
-- Type: TABLE; Owner: BIOMART; Name: MESH_ENTRY
--
 CREATE TABLE "BIOMART"."MESH_ENTRY" 
  (	"MH" VARCHAR2(200 BYTE), 
"ENTRY" VARCHAR2(200 BYTE)
  ) SEGMENT CREATION DEFERRED
NOCOMPRESS LOGGING
 TABLESPACE "BIOMART" ;
