--
-- Type: TABLE; Owner: BIOMART; Name: MIRNA_BIO_ASSAY_DATA_ANNOT
--
 CREATE TABLE "BIOMART"."MIRNA_BIO_ASSAY_DATA_ANNOT" 
  (	"BIO_ASSAY_FEATURE_GROUP_ID" NUMBER(18,0), 
"BIO_MARKER_ID" NUMBER(18,0) NOT NULL ENABLE, 
"DATA_TABLE" CHAR(5 BYTE)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

