--
-- Type: TABLE; Owner: BIOMART; Name: TMP_PROJECT_COMPOUND
--
 CREATE TABLE "BIOMART"."TMP_PROJECT_COMPOUND" 
  (	"FILE_ID" VARCHAR2(100 BYTE), 
"ACCESSION" VARCHAR2(100 BYTE), 
"COMPOUND" VARCHAR2(4000 BYTE)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

