\i i2b2metadata/prelude.sql
\i i2b2metadata/functions/add_ontology_node.sql
\i i2b2metadata/custom_meta.sql
\i i2b2metadata/i2b2.sql
\i i2b2metadata/i2b2_secure.sql
\i i2b2metadata/i2b2_tags.sql
\i i2b2metadata/views/i2b2_trial_nodes.sql
\i i2b2metadata/ont_db_lookup.sql
\i i2b2metadata/ont_process_status.sql
\i i2b2metadata/schemes.sql
\i i2b2metadata/table_access.sql
\i i2b2metadata/tmp_secure_token.sql
\i i2b2metadata/_misc.sql
