INSERT INTO TM_CZ.CZ_FORM_LAYOUT(FORM_KEY, FORM_COLUMN, DISPLAY_NAME, DATA_TYPE, SEQUENCE) VALUES ('file', 'displayName', 'Name', 'string', 1);
INSERT INTO TM_CZ.CZ_FORM_LAYOUT(FORM_KEY, FORM_COLUMN, DISPLAY_NAME, DATA_TYPE, SEQUENCE) VALUES ('file', 'fileType', 'File Type', 'string', 2);
INSERT INTO TM_CZ.CZ_FORM_LAYOUT(FORM_KEY, FORM_COLUMN, DISPLAY_NAME, DATA_TYPE, SEQUENCE) VALUES ('file', 'fileSize', 'Size', 'dataSize', 3);
INSERT INTO TM_CZ.CZ_FORM_LAYOUT(FORM_KEY, FORM_COLUMN, DISPLAY_NAME, DATA_TYPE, SEQUENCE) VALUES ('file', 'createDate', 'Created', 'date', 4);
INSERT INTO TM_CZ.CZ_FORM_LAYOUT(FORM_KEY, FORM_COLUMN, DISPLAY_NAME, DATA_TYPE, SEQUENCE) VALUES ('file', 'updateDate', 'Updated', 'date', 5);
INSERT INTO TM_CZ.CZ_FORM_LAYOUT(FORM_KEY, FORM_COLUMN, DISPLAY_NAME, DATA_TYPE, SEQUENCE) VALUES ('file', 'fileDescription', 'Description', 'prestring', 6);