\ir prelude.sql
\ir bio_assay_analysis_data_new.sql
\ir tmp_assay_analysis_metrics.sql
\ir wrk_clinical_data.sql
\ir wrk_mrna_data.sql
\ir wt_clinical_data_dups.sql
\ir wt_mrna_data.sql
\ir wt_mrna_node_values.sql
\ir wt_mrna_nodes.sql
\ir wt_mrna_subj_sample_map.sql
\ir wt_num_data_types.sql
\ir wt_subject_acgh_region.sql
\ir wt_subject_info.sql
\ir wt_subject_microarray_calcs.sql
\ir wt_subject_microarray_logs.sql
\ir wt_subject_microarray_med.sql
\ir wt_subject_mrna_data.sql
\ir wt_subject_mrna_probeset.sql
\ir wt_trial_nodes.sql
\ir wt_xtrial_nodes.sql
\ir _misc.sql
