\i tm_wz/prelude.sql
\i tm_wz/bio_assay_analysis_data_new.sql
\i tm_wz/tmp_assay_analysis_metrics.sql
\i tm_wz/wrk_clinical_data.sql
\i tm_wz/wrk_mrna_data.sql
\i tm_wz/wt_clinical_data_dups.sql
\i tm_wz/wt_mrna_data.sql
\i tm_wz/wt_mrna_node_values.sql
\i tm_wz/wt_mrna_nodes.sql
\i tm_wz/wt_mrna_subj_sample_map.sql
\i tm_wz/wt_num_data_types.sql
\i tm_wz/wt_subject_acgh_region.sql
\i tm_wz/wt_subject_info.sql
\i tm_wz/wt_subject_microarray_calcs.sql
\i tm_wz/wt_subject_microarray_logs.sql
\i tm_wz/wt_subject_microarray_med.sql
\i tm_wz/wt_subject_mrna_data.sql
\i tm_wz/wt_subject_mrna_probeset.sql
\i tm_wz/wt_subject_rnaseq_region.sql
\i tm_wz/wt_trial_nodes.sql
\i tm_wz/wt_xtrial_nodes.sql
