
INFILE '00-All.vcf.snpEff.de_rc_snp_info'
   INTO TABLE DE_RC_SNP_INFO
   FIELDS TERMINATED BY X'9'
   TRAILING NULLCOLS
   (
    RS_ID,
    CHROM,
    POS,
    REF,
    ALT,
    GENE_INFO,
    VARIATION_CLASS,
    STRAND,
    GMAF,
    GENE_BIOTYPE,
    IMPACT,
    TRANSCRIPT_ID,
    FUNCTIONAL_CLASS,
    EFFECT,
    EXON_ID,
    AMINO_ACID_CHANGE,
    CODON_CHANGE,
    HG_VERSION,
    GENE_NAME,
    ENTREZ_ID,
    RECOMBINATION_RATE,
    REGULOME_SCORE,
    SNP_INFO_ID "DE_RC_SNP_INFO_SEQ.nextval"
    )
