--
-- Type: TABLE; Owner: I2B2DEMODATA; Name: ASYNC_JOB
--
 CREATE TABLE "I2B2DEMODATA"."ASYNC_JOB" 
  (	"ID" NUMBER NOT NULL ENABLE, 
"JOB_NAME" VARCHAR2(200 BYTE), 
"JOB_STATUS" VARCHAR2(200 BYTE), 
"RUN_TIME" VARCHAR2(200 BYTE), 
"LAST_RUN_ON" TIMESTAMP (6), 
"VIEWER_URL" VARCHAR2(4000 BYTE), 
"ALT_VIEWER_URL" VARCHAR2(600 BYTE), 
"JOB_RESULTS" CLOB, 
"JOB_INPUTS_JSON" CLOB,
"JOB_TYPE" VARCHAR2(20 BYTE), 
"JOB_STATUS_TIME" TIMESTAMP (6), 
 PRIMARY KEY ("ID")
 USING INDEX
 TABLESPACE "I2B2_DATA"  ENABLE
  ) SEGMENT CREATION IMMEDIATE
NOCOMPRESS NOLOGGING
 TABLESPACE "I2B2_DATA" 
LOB ("JOB_RESULTS") STORE AS BASICFILE (
 TABLESPACE "I2B2_DATA" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
LOB ("JOB_INPUTS_JSON") STORE AS BASICFILE (
 TABLESPACE "I2B2_DATA" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
 NOCACHE LOGGING ) ;
