--
-- Type: TABLE; Owner: I2B2DEMODATA; Name: CD
--
 CREATE TABLE "I2B2DEMODATA"."CD" 
  (	"CONCEPT_PATH" VARCHAR2(500 BYTE), 
"PARENT_CONCEPT_PATH" VARCHAR2(500 BYTE), 
"PATIENT_COUNT" NUMBER(38,0)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

