--
-- Type: TABLE; Owner: I2B2DEMODATA; Name: COUNTER
--
 CREATE TABLE "I2B2DEMODATA"."COUNTER" 
  (	"CONCEPT_CD" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
"COUNTS" NUMBER
  ) SEGMENT CREATION DEFERRED
 TABLESPACE "I2B2_DATA" ;

