--
-- Type: TABLE; Owner: I2B2DEMODATA; Name: DR$OF_CTX_BLOB$N
--
 CREATE TABLE "I2B2DEMODATA"."DR$OF_CTX_BLOB$N" 
  (	"NLT_DOCID" NUMBER(38,0), 
"NLT_MARK" CHAR(1 BYTE) NOT NULL ENABLE, 
 CONSTRAINT "SYS_IOT_TOP_35083" PRIMARY KEY ("NLT_DOCID") ENABLE
  ) ORGANIZATION INDEX NOCOMPRESS
 TABLESPACE "TRANSMART" 
PCTTHRESHOLD 50;

