--
-- Type: TABLE; Owner: I2B2DEMODATA; Name: DR$OF_CTX_BLOB$K
--
 CREATE TABLE "I2B2DEMODATA"."DR$OF_CTX_BLOB$K" 
  (	"DOCID" NUMBER(38,0), 
"TEXTKEY" ROWID, 
 CONSTRAINT "SYS_IOT_TOP_35078" PRIMARY KEY ("TEXTKEY") ENABLE
  ) ORGANIZATION INDEX NOCOMPRESS
 TABLESPACE "TRANSMART" 
PCTTHRESHOLD 50;

