--
-- Type: TABLE; Owner: I2B2DEMODATA; Name: JMS_SUBSCRIPTIONS
--
 CREATE TABLE "I2B2DEMODATA"."JMS_SUBSCRIPTIONS" 
  (	"CLIENTID" VARCHAR2(128 BYTE) NOT NULL ENABLE, 
"SUBNAME" VARCHAR2(128 BYTE) NOT NULL ENABLE, 
"TOPIC" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
"SELECTOR" VARCHAR2(255 BYTE), 
 PRIMARY KEY ("CLIENTID", "SUBNAME")
 USING INDEX
 TABLESPACE "I2B2_DATA"  ENABLE
  ) SEGMENT CREATION DEFERRED
 TABLESPACE "I2B2_DATA" ;

