--
-- Type: TABLE; Owner: I2B2DEMODATA; Name: MASTER_QUERY_GLOBAL_TEMP
--
 CREATE GLOBAL TEMPORARY TABLE "I2B2DEMODATA"."MASTER_QUERY_GLOBAL_TEMP" 
  (	"ENCOUNTER_NUM" NUMBER(22,0), 
"PATIENT_NUM" NUMBER(22,0), 
"INSTANCE_NUM" NUMBER(18,0), 
"CONCEPT_CD" VARCHAR2(50 BYTE), 
"START_DATE" DATE, 
"PROVIDER_ID" VARCHAR2(50 BYTE), 
"MASTER_ID" VARCHAR2(50 BYTE), 
"LEVEL_NO" NUMBER(5,0)
  ) ON COMMIT PRESERVE ROWS ;

