--
-- Type: TABLE; Owner: I2B2DEMODATA; Name: QT_PDO_QUERY_MASTER
--
 CREATE TABLE "I2B2DEMODATA"."QT_PDO_QUERY_MASTER" 
  (	"QUERY_MASTER_ID" NUMBER(5,0), 
"USER_ID" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
"GROUP_ID" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
"CREATE_DATE" DATE NOT NULL ENABLE, 
"REQUEST_XML" CLOB, 
"I2B2_REQUEST_XML" CLOB, 
 PRIMARY KEY ("QUERY_MASTER_ID")
 USING INDEX
 TABLESPACE "I2B2_DATA"  ENABLE
  ) SEGMENT CREATION DEFERRED
NOCOMPRESS NOLOGGING
 TABLESPACE "I2B2_DATA" 
LOB ("REQUEST_XML") STORE AS BASICFILE (
 TABLESPACE "I2B2_DATA" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
 NOCACHE LOGGING ) 
LOB ("I2B2_REQUEST_XML") STORE AS BASICFILE (
 TABLESPACE "I2B2_DATA" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
 NOCACHE LOGGING ) ;
--
-- Type: INDEX; Owner: I2B2DEMODATA; Name: QT_IDX_PQM_UGID
--
CREATE INDEX "I2B2DEMODATA"."QT_IDX_PQM_UGID" ON "I2B2DEMODATA"."QT_PDO_QUERY_MASTER" ("USER_ID", "GROUP_ID")
TABLESPACE "I2B2_DATA" ;

-- trigger needed to match postgres default values

-- Type: TRIGGER; Owner: I2B2DEMODATA; Name: TRG_QT_QRY_MSTR_ID
--
  CREATE OR REPLACE TRIGGER "I2B2DEMODATA"."TRG_QT_QRY_MST_ID" before insert on "I2B2DEMODATA"."QT_PDO_QUERY_MASTER"    
for each row begin    
if inserting then      
  if :NEW."QUERY_MASTER_ID" is null then          
    select QT_SQ_PQM_QMID.nextval into :NEW."QUERY_MASTER_ID" from dual;       
  end if;    
end if; 
end;
/
ALTER TRIGGER "I2B2DEMODATA"."TRG_QT_QRY_MSTR_ID" ENABLE;
