--
-- Type: TABLE; Owner: I2B2DEMODATA; Name: QT_PDO_QUERY_MASTER
--
 CREATE TABLE "I2B2DEMODATA"."QT_PDO_QUERY_MASTER" 
  (	"QUERY_MASTER_ID" NUMBER(5,0), 
"USER_ID" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
"GROUP_ID" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
"CREATE_DATE" DATE NOT NULL ENABLE, 
"REQUEST_XML" CLOB, 
"I2B2_REQUEST_XML" CLOB, 
 PRIMARY KEY ("QUERY_MASTER_ID")
 USING INDEX
 TABLESPACE "I2B2_DATA"  ENABLE
  ) SEGMENT CREATION DEFERRED
 TABLESPACE "I2B2_DATA" 
LOB ("REQUEST_XML") STORE AS BASICFILE (
 TABLESPACE "I2B2_DATA" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
 NOCACHE LOGGING ) 
LOB ("I2B2_REQUEST_XML") STORE AS BASICFILE (
 TABLESPACE "I2B2_DATA" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
 NOCACHE LOGGING ) ;

--
-- Type: INDEX; Owner: I2B2DEMODATA; Name: QT_IDX_PQM_UGID
--
CREATE INDEX "I2B2DEMODATA"."QT_IDX_PQM_UGID" ON "I2B2DEMODATA"."QT_PDO_QUERY_MASTER" ("USER_ID", "GROUP_ID")
TABLESPACE "I2B2_DATA" ;

