--
-- Type: TABLE; Owner: I2B2DEMODATA; Name: QT_PATIENT_ENC_COLLECTION
--
 CREATE TABLE "I2B2DEMODATA"."QT_PATIENT_ENC_COLLECTION" 
  (	"PATIENT_ENC_COLL_ID" NUMBER(10,0), 
"RESULT_INSTANCE_ID" NUMBER(5,0), 
"SET_INDEX" NUMBER(10,0), 
"PATIENT_NUM" NUMBER(10,0), 
"ENCOUNTER_NUM" NUMBER(10,0),
CONSTRAINT "QT_PATIENT_ENC_COLL_PK" PRIMARY KEY ("PATIENT_ENC_COLL_ID")
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "I2B2_DATA" ;
--
-- Type: REF_CONSTRAINT; Owner: I2B2DEMODATA; Name: QT_FK_PEC_RI
--
ALTER TABLE "I2B2DEMODATA"."QT_PATIENT_ENC_COLLECTION" ADD CONSTRAINT "QT_FK_PEC_RI" FOREIGN KEY ("RESULT_INSTANCE_ID")
 REFERENCES "I2B2DEMODATA"."QT_QUERY_RESULT_INSTANCE" ("RESULT_INSTANCE_ID") ENABLE;
