--
-- Type: TABLE; Owner: I2B2DEMODATA; Name: QT_QUERY_STATUS_TYPE
--
 CREATE TABLE "I2B2DEMODATA"."QT_QUERY_STATUS_TYPE" 
  (	"STATUS_TYPE_ID" NUMBER(3,0), 
"NAME" VARCHAR2(100 BYTE), 
"DESCRIPTION" VARCHAR2(200 BYTE),
CONSTRAINT "QT_QUERY_STATUS_TYPE_PKEY" PRIMARY KEY ("STATUS_TYPE_ID")
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "I2B2_DATA" ;
