--
-- Type: TABLE; Owner: I2B2DEMODATA; Name: RICERCA
--
 CREATE TABLE "I2B2DEMODATA"."RICERCA" 
  (	"CONCEPT_CD" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
"CONCEPT_PATH" VARCHAR2(700 BYTE) NOT NULL ENABLE
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

