--
-- Type: TABLE; Owner: I2B2DEMODATA; Name: SET_TYPE
--
 CREATE TABLE "I2B2DEMODATA"."SET_TYPE" 
  (	"ID" NUMBER(38,0), 
"NAME" VARCHAR2(500 BYTE), 
"CREATE_DATE" DATE,
CONSTRAINT "PK_ST_ID" PRIMARY KEY ("ID")
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "I2B2_DATA" ;
