--
-- Type: TABLE; Owner: I2B2DEMODATA; Name: SOURCE_MASTER
--
 CREATE TABLE "I2B2DEMODATA"."SOURCE_MASTER" 
  (	"SOURCE_CD" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
"DESCRIPTION" VARCHAR2(300 BYTE), 
"CREATE_DATE" DATE, 
 CONSTRAINT "PK_SOURCEMASTER_SOURCECD" PRIMARY KEY ("SOURCE_CD")
 USING INDEX
 TABLESPACE "TRANSMART"  ENABLE
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

