--
-- Type: TABLE; Owner: I2B2DEMODATA; Name: SOURCE_MASTER
--
 CREATE TABLE "I2B2DEMODATA"."SOURCE_MASTER" 
  (	"SOURCE_CD" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
"DESCRIPTION" VARCHAR2(300 BYTE), 
"CREATE_DATE" DATE
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "I2B2_DATA" ;
