--
-- Type: TABLE; Owner: I2B2DEMODATA; Name: UPLOAD_STATUS
--
 CREATE TABLE "I2B2DEMODATA"."UPLOAD_STATUS" 
  (	"UPLOAD_ID" NUMBER(38,0), 
"UPLOAD_LABEL" VARCHAR2(500 BYTE) NOT NULL ENABLE, 
"USER_ID" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
"SOURCE_CD" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
"NO_OF_RECORD" NUMBER, 
"LOADED_RECORD" NUMBER, 
"DELETED_RECORD" NUMBER, 
"LOAD_DATE" DATE NOT NULL ENABLE, 
"END_DATE" DATE, 
"LOAD_STATUS" VARCHAR2(100 BYTE), 
"MESSAGE" CLOB, 
"INPUT_FILE_NAME" CLOB, 
"LOG_FILE_NAME" CLOB, 
"TRANSFORM_NAME" VARCHAR2(500 BYTE)
  ) SEGMENT CREATION DEFERRED
 TABLESPACE "I2B2_DATA" 
LOB ("MESSAGE") STORE AS BASICFILE (
 TABLESPACE "I2B2_DATA" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
 NOCACHE LOGGING ) 
LOB ("INPUT_FILE_NAME") STORE AS BASICFILE (
 TABLESPACE "I2B2_DATA" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
 NOCACHE LOGGING ) 
LOB ("LOG_FILE_NAME") STORE AS BASICFILE (
 TABLESPACE "I2B2_DATA" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
 NOCACHE LOGGING ) ;

