--
-- Type: TABLE; Owner: TM_WZ; Name: BIO_ASSAY_ANALYSIS_DATA_NEW
--
 CREATE TABLE "TM_WZ"."BIO_ASSAY_ANALYSIS_DATA_NEW" 
  (	"BIO_ASY_ANALYSIS_DATA_ID" NUMBER, 
"FOLD_CHANGE_RATIO" NUMBER, 
"RAW_PVALUE" FLOAT(126), 
"ADJUSTED_PVALUE" FLOAT(126), 
"R_VALUE" FLOAT(126), 
"RHO_VALUE" FLOAT(126), 
"BIO_ASSAY_ANALYSIS_ID" NUMBER, 
"ADJUSTED_P_VALUE_CODE" VARCHAR2(100 BYTE), 
"FEATURE_GROUP_NAME" VARCHAR2(100 BYTE), 
"BIO_EXPERIMENT_ID" NUMBER, 
"BIO_ASSAY_PLATFORM_ID" NUMBER, 
"ETL_ID" VARCHAR2(100 BYTE), 
"PREFERRED_PVALUE" FLOAT(126), 
"CUT_VALUE" FLOAT(126), 
"RESULTS_VALUE" VARCHAR2(100 BYTE), 
"NUMERIC_VALUE" FLOAT(126), 
"NUMERIC_VALUE_CODE" VARCHAR2(50 BYTE), 
"TEA_NORMALIZED_PVALUE" FLOAT(126), 
"BIO_ASSAY_FEATURE_GROUP_ID" NUMBER, 
"LSMEAN1" FLOAT(126), 
"LSMEAN2" FLOAT(126)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

