--
-- Type: TABLE; Owner: TM_WZ; Name: WRK_CLINICAL_DATA
--
 CREATE TABLE "TM_WZ"."WRK_CLINICAL_DATA" 
  (	"STUDY_ID" VARCHAR2(25 BYTE), 
"SITE_ID" VARCHAR2(50 BYTE), 
"SUBJECT_ID" VARCHAR2(100 BYTE), 
"VISIT_NAME" VARCHAR2(100 BYTE), 
"DATA_LABEL" VARCHAR2(500 BYTE), 
"DATA_VALUE" VARCHAR2(500 BYTE), 
"CATEGORY_CD" VARCHAR2(250 BYTE), 
"ETL_JOB_ID" NUMBER(22,0), 
"ETL_DATE" DATE, 
"USUBJID" VARCHAR2(200 BYTE), 
"CATEGORY_PATH" VARCHAR2(1000 BYTE), 
"DATA_TYPE" VARCHAR2(10 BYTE), 
"DATA_LABEL_CTRL_VOCAB_CODE" VARCHAR2(200 BYTE), 
"DATA_VALUE_CTRL_VOCAB_CODE" VARCHAR2(500 BYTE), 
"DATA_LABEL_COMPONENTS" VARCHAR2(1000 BYTE), 
"UNITS_CD" VARCHAR2(50 BYTE), 
"NODE_NAME" VARCHAR2(1000 BYTE), 
"LINK_TYPE" VARCHAR2(20 BYTE), 
"LINK_VALUE" VARCHAR2(200 BYTE), 
"END_DATE" VARCHAR2(50 BYTE), 
"VISIT_REFERENCE" VARCHAR2(100 BYTE), 
"DATE_IND" CHAR(1 BYTE), 
"OBS_STRING" VARCHAR2(100 BYTE), 
"REC_NUM" NUMBER(18,0), 
"VALUETYPE_CD" VARCHAR2(50 BYTE), 
"LEAF_NODE" VARCHAR2(2000 BYTE), 
"MODIFIER_CD" VARCHAR2(100 BYTE), 
"CTRL_VOCAB_CODE" VARCHAR2(200 BYTE), 
"VISIT_DATE" VARCHAR2(200 BYTE), 
"DATE_TIMESTAMP" DATE, 
"SAMPLE_CD" VARCHAR2(200 BYTE)
  ) SEGMENT CREATION IMMEDIATE
NOCOMPRESS NOLOGGING
 TABLESPACE "TRANSMART" 
  CACHE ;
--
-- Type: INDEX; Owner: TM_WZ; Name: IDX_WRK_CD
--
CREATE INDEX "TM_WZ"."IDX_WRK_CD" ON "TM_WZ"."WRK_CLINICAL_DATA" ("DATA_TYPE", "DATA_VALUE", "VISIT_NAME", "DATA_LABEL", "CATEGORY_CD", "USUBJID")
TABLESPACE "TRANSMART" ;

