--
-- Type: TABLE; Owner: TM_WZ; Name: WT_CLINICAL_ENCOUNTER
--
 CREATE TABLE "TM_WZ"."WT_CLINICAL_ENCOUNTER" 
  (	"LINK_TYPE" VARCHAR2(20 BYTE), 
"LINK_VALUE" VARCHAR2(500 BYTE), 
"ENCOUNTER_NUM" NUMBER(*,0)
  ) SEGMENT CREATION DEFERRED
 TABLESPACE "TRANSMART" ;

