--
-- Type: TABLE; Owner: TM_WZ; Name: WT_FOLDER_NODES
--
 CREATE TABLE "TM_WZ"."WT_FOLDER_NODES" 
  (	"FOLDER_PATH" VARCHAR2(700 BYTE), 
"FOLDER_NAME" VARCHAR2(2000 BYTE)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

