--
-- Type: TABLE; Owner: TM_WZ; Name: WT_MRNA_DATA
--
 CREATE TABLE "TM_WZ"."WT_MRNA_DATA" 
  (	"PROBESET" VARCHAR2(100 BYTE), 
"EXPR_ID" VARCHAR2(100 BYTE), 
"INTENSITY_VALUE" VARCHAR2(50 BYTE)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

