--
-- Type: TABLE; Owner: TM_WZ; Name: WT_MIXED_TYPES
--
 CREATE TABLE "TM_WZ"."WT_MIXED_TYPES" 
  (	"CATEGORY_CD" VARCHAR2(250 BYTE), 
"DATA_LABEL" VARCHAR2(500 BYTE), 
"VISIT_NAME" VARCHAR2(100 BYTE)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

