--
-- Type: TABLE; Owner: TM_WZ; Name: WT_NUM_DATA_TYPES
--
 CREATE TABLE "TM_WZ"."WT_NUM_DATA_TYPES" 
  (	"CATEGORY_CD" VARCHAR2(200 BYTE), 
"DATA_LABEL" VARCHAR2(500 BYTE), 
"SAMPLE_TYPE" VARCHAR2(100 BYTE), 
"VISIT_NAME" VARCHAR2(100 BYTE)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

