--
-- Type: TABLE; Owner: TM_WZ; Name: WT_QPCR_MIRNA_NODE_VALUES
--
 CREATE TABLE "TM_WZ"."WT_QPCR_MIRNA_NODE_VALUES" 
  (	"CATEGORY_CD" VARCHAR2(2000 BYTE), 
"PLATFORM" VARCHAR2(2000 BYTE), 
"TISSUE_TYPE" VARCHAR2(2000 BYTE), 
"ATTRIBUTE_1" VARCHAR2(2000 BYTE), 
"ATTRIBUTE_2" VARCHAR2(2000 BYTE), 
"TITLE" VARCHAR2(2000 BYTE), 
"TRANSFORM_METHOD" VARCHAR2(2000 BYTE)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

