--
-- Type: TABLE; Owner: TM_WZ; Name: WT_SUBJECT_RNASEQ_REGION
--
 CREATE TABLE "TM_WZ"."WT_SUBJECT_RNASEQ_REGION" 
  (	"REGION_ID" NUMBER, 
"EXPR_ID" VARCHAR2(500 BYTE), 
"READCOUNT" NUMBER, 
"ASSAY_ID" NUMBER, 
"PATIENT_ID" NUMBER, 
"SAMPLE_ID" NUMBER, 
"SUBJECT_ID" VARCHAR2(100 BYTE), 
"TRIAL_NAME" VARCHAR2(200 BYTE), 
"TIMEPOINT" VARCHAR2(200 BYTE), 
"SAMPLE_TYPE" VARCHAR2(200 BYTE), 
"PLATFORM" VARCHAR2(200 BYTE), 
"TISSUE_TYPE" VARCHAR2(200 BYTE)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

