--
-- Type: TABLE; Owner: TM_WZ; Name: WT_XTRIAL_NODES
--
 CREATE TABLE "TM_WZ"."WT_XTRIAL_NODES" 
  (	"XTRIAL_CD" VARCHAR2(200 BYTE), 
"TRIAL_NAME" VARCHAR2(200 BYTE), 
"LEAF_NAME" VARCHAR2(200 BYTE), 
"DATA_TYPE" VARCHAR2(10 BYTE), 
"CONCEPT_CD" VARCHAR2(200 BYTE), 
"LEAF_NODE" VARCHAR2(2000 BYTE)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

