<?php

if (isset($_ENV['ORACLE_TABLESPACES_DIR'])) {
        echo "ALTER SYSTEM SET DB_CREATE_FILE_DEST = '$_ENV[ORACLE_TABLESPACES_DIR]';\n";
}

echo <<<EOD
CREATE TABLESPACE transmart;
CREATE TABLESPACE indx;
EOD;
