<?php

$spec = [
    'BIOMART_USER' => [
        ['BIOMART',      '*TABLE'],
        ['BIOMART',      '*VIEW'],
        ['BIOMART',      '*MATERIALIZED_VIEW'],
        ['BIOMART',      '*SEQUENCE'],
        ['DEAPP',        '*TABLE'],
        ['DEAPP',        '*VIEW'],
        ['DEAPP',        '*SEQUENCE'],
        ['I2B2DEMODATA', '*TABLE'],
        ['I2B2DEMODATA', '*VIEW'],
        ['I2B2DEMODATA', '*SEQUENCE'],
        ['I2B2METADATA', '*TABLE'],
        ['I2B2METADATA', '*VIEW'],
        ['I2B2METADATA', '*SEQUENCE'],
        ['SEARCHAPP',    '*TABLE'],
        ['SEARCHAPP',    '*VIEW'],
        ['SEARCHAPP',    '*SEQUENCE'],
        ['FMAPP',        '*TABLE'],
        ['FMAPP',        '*VIEW'],
        ['FMAPP',        '*SEQUENCE'],
        ['AMAPP',        '*TABLE'],
        ['AMAPP',        '*VIEW'],
        ['AMAPP',        '*SEQUENCE'],
    ],
    'TM_CZ' => [
        ['BIOMART',      '*TABLE'],
        ['BIOMART',      '*VIEW'],
        ['DEAPP',        '*TABLE'],
        ['DEAPP',        '*VIEW'],
        ['I2B2DEMODATA', '*TABLE'],
        ['I2B2DEMODATA', '*SEQUENCE'],
        ['I2B2METADATA', '*TABLE'],
        ['I2B2METADATA', '*SEQUENCE'],
        ['SEARCHAPP',    '*TABLE'],
        ['SEARCHAPP',    '*VIEW'],
        ['TM_LZ',        '*TABLE'],
        ['TM_LZ',        '*VIEW'],
        ['TM_WZ',        '*TABLE'],
        ['TM_WZ',        '*VIEW'],
        ['FMAPP',        '*TABLE'],
        ['FMAPP',        '*VIEW'],
        ['FMAPP',        '*SEQUENCE'],
        ['AMAPP',        '*TABLE'],
        ['AMAPP',        '*VIEW'],
        ['AMAPP',        '*SEQUENCE'],
    ],
];
