--
-- Type: USER; Name: BIOMART_USER
--
CREATE USER "BIOMART_USER" IDENTIFIED BY VALUES 'S:E41F0A3D2D5D75996903101426784BD02076161D3EF296278E0CEB442732;H:A3DDDEB160ABA36F89E31EEB0C046FB5;DBE9DFAEB8C02517'
   DEFAULT TABLESPACE "TRANSMART"
   TEMPORARY TABLESPACE "TEMP";
--
-- Type: ROLE_GRANT; Name: BIOMART_USER
--
GRANT "CONNECT" TO "BIOMART_USER";
--
-- Type: TABLESPACE_QUOTA; Name: BIOMART_USER
--
  DECLARE 
  TEMP_COUNT NUMBER; 
  SQLSTR VARCHAR2(200); 
BEGIN 
  SQLSTR := 'ALTER USER "BIOMART_USER" QUOTA UNLIMITED ON "INDX"';
  EXECUTE IMMEDIATE SQLSTR;
EXCEPTION 
  WHEN OTHERS THEN
    IF SQLCODE = -30041 THEN 
      SQLSTR := 'SELECT COUNT(*) FROM USER_TABLESPACES 
              WHERE TABLESPACE_NAME = ''INDX'' AND CONTENTS = ''TEMPORARY''';
      EXECUTE IMMEDIATE SQLSTR INTO TEMP_COUNT;
      IF TEMP_COUNT = 1 THEN RETURN; 
      ELSE RAISE; 
      END IF;
    ELSE
      RAISE;
    END IF;
END;
/
  DECLARE 
  TEMP_COUNT NUMBER; 
  SQLSTR VARCHAR2(200); 
BEGIN 
  SQLSTR := 'ALTER USER "BIOMART_USER" QUOTA UNLIMITED ON "TRANSMART"';
  EXECUTE IMMEDIATE SQLSTR;
EXCEPTION 
  WHEN OTHERS THEN
    IF SQLCODE = -30041 THEN 
      SQLSTR := 'SELECT COUNT(*) FROM USER_TABLESPACES 
              WHERE TABLESPACE_NAME = ''TRANSMART'' AND CONTENTS = ''TEMPORARY''';
      EXECUTE IMMEDIATE SQLSTR INTO TEMP_COUNT;
      IF TEMP_COUNT = 1 THEN RETURN; 
      ELSE RAISE; 
      END IF;
    ELSE
      RAISE;
    END IF;
END;
/
--
-- Type: SYSTEM_GRANT; Name: BIOMART_USER
--
GRANT FLASHBACK ARCHIVE ADMINISTER TO "BIOMART_USER";
GRANT ADMINISTER SQL MANAGEMENT OBJECT TO "BIOMART_USER";
GRANT UPDATE ANY CUBE DIMENSION TO "BIOMART_USER";
GRANT UPDATE ANY CUBE BUILD PROCESS TO "BIOMART_USER";
GRANT DROP ANY CUBE BUILD PROCESS TO "BIOMART_USER";
GRANT CREATE ANY CUBE BUILD PROCESS TO "BIOMART_USER";
GRANT CREATE CUBE BUILD PROCESS TO "BIOMART_USER";
GRANT INSERT ANY MEASURE FOLDER TO "BIOMART_USER";
GRANT DROP ANY MEASURE FOLDER TO "BIOMART_USER";
GRANT DELETE ANY MEASURE FOLDER TO "BIOMART_USER";
GRANT CREATE ANY MEASURE FOLDER TO "BIOMART_USER";
GRANT CREATE MEASURE FOLDER TO "BIOMART_USER";
GRANT UPDATE ANY CUBE TO "BIOMART_USER";
GRANT SELECT ANY CUBE TO "BIOMART_USER";
GRANT DROP ANY CUBE TO "BIOMART_USER";
GRANT CREATE ANY CUBE TO "BIOMART_USER";
GRANT ALTER ANY CUBE TO "BIOMART_USER";
GRANT CREATE CUBE TO "BIOMART_USER";
GRANT SELECT ANY CUBE DIMENSION TO "BIOMART_USER";
GRANT INSERT ANY CUBE DIMENSION TO "BIOMART_USER";
GRANT DROP ANY CUBE DIMENSION TO "BIOMART_USER";
GRANT DELETE ANY CUBE DIMENSION TO "BIOMART_USER";
GRANT CREATE ANY CUBE DIMENSION TO "BIOMART_USER";
GRANT ALTER ANY CUBE DIMENSION TO "BIOMART_USER";
GRANT CREATE CUBE DIMENSION TO "BIOMART_USER";
GRANT COMMENT ANY MINING MODEL TO "BIOMART_USER";
GRANT ALTER ANY MINING MODEL TO "BIOMART_USER";
GRANT SELECT ANY MINING MODEL TO "BIOMART_USER";
GRANT DROP ANY MINING MODEL TO "BIOMART_USER";
GRANT CREATE ANY MINING MODEL TO "BIOMART_USER";
GRANT CREATE MINING MODEL TO "BIOMART_USER";
GRANT EXECUTE ASSEMBLY TO "BIOMART_USER";
GRANT EXECUTE ANY ASSEMBLY TO "BIOMART_USER";
GRANT DROP ANY ASSEMBLY TO "BIOMART_USER";
GRANT ALTER ANY ASSEMBLY TO "BIOMART_USER";
GRANT CREATE ANY ASSEMBLY TO "BIOMART_USER";
GRANT CREATE ASSEMBLY TO "BIOMART_USER";
GRANT ALTER ANY EDITION TO "BIOMART_USER";
GRANT DROP ANY EDITION TO "BIOMART_USER";
GRANT CREATE ANY EDITION TO "BIOMART_USER";
GRANT CREATE EXTERNAL JOB TO "BIOMART_USER";
GRANT CHANGE NOTIFICATION TO "BIOMART_USER";
GRANT CREATE ANY SQL PROFILE TO "BIOMART_USER";
GRANT ADMINISTER ANY SQL TUNING SET TO "BIOMART_USER";
GRANT ADMINISTER SQL TUNING SET TO "BIOMART_USER";
GRANT ALTER ANY SQL PROFILE TO "BIOMART_USER";
GRANT DROP ANY SQL PROFILE TO "BIOMART_USER";
GRANT SELECT ANY TRANSACTION TO "BIOMART_USER";
GRANT MANAGE SCHEDULER TO "BIOMART_USER";
GRANT EXECUTE ANY CLASS TO "BIOMART_USER";
GRANT EXECUTE ANY PROGRAM TO "BIOMART_USER";
GRANT CREATE ANY JOB TO "BIOMART_USER";
GRANT CREATE JOB TO "BIOMART_USER";
GRANT ADVISOR TO "BIOMART_USER";
GRANT IMPORT FULL DATABASE TO "BIOMART_USER";
GRANT EXPORT FULL DATABASE TO "BIOMART_USER";
GRANT GRANT ANY OBJECT PRIVILEGE TO "BIOMART_USER";
GRANT FLASHBACK ANY TABLE TO "BIOMART_USER";
GRANT DEBUG ANY PROCEDURE TO "BIOMART_USER";
GRANT DEBUG CONNECT SESSION TO "BIOMART_USER";
GRANT RESUMABLE TO "BIOMART_USER";
GRANT ON COMMIT REFRESH TO "BIOMART_USER";
GRANT MERGE ANY VIEW TO "BIOMART_USER";
GRANT ADMINISTER DATABASE TRIGGER TO "BIOMART_USER";
GRANT DROP ANY OUTLINE TO "BIOMART_USER";
GRANT ALTER ANY OUTLINE TO "BIOMART_USER";
GRANT CREATE ANY OUTLINE TO "BIOMART_USER";
GRANT DROP ANY CONTEXT TO "BIOMART_USER";
GRANT CREATE ANY CONTEXT TO "BIOMART_USER";
GRANT DROP ANY DIMENSION TO "BIOMART_USER";
GRANT ALTER ANY DIMENSION TO "BIOMART_USER";
GRANT CREATE ANY DIMENSION TO "BIOMART_USER";
GRANT CREATE DIMENSION TO "BIOMART_USER";
GRANT UNDER ANY TABLE TO "BIOMART_USER";
GRANT EXECUTE ANY INDEXTYPE TO "BIOMART_USER";
GRANT GLOBAL QUERY REWRITE TO "BIOMART_USER";
GRANT QUERY REWRITE TO "BIOMART_USER";
GRANT UNDER ANY VIEW TO "BIOMART_USER";
GRANT DROP ANY INDEXTYPE TO "BIOMART_USER";
GRANT ALTER ANY INDEXTYPE TO "BIOMART_USER";
GRANT CREATE ANY INDEXTYPE TO "BIOMART_USER";
GRANT CREATE INDEXTYPE TO "BIOMART_USER";
GRANT EXECUTE ANY OPERATOR TO "BIOMART_USER";
GRANT DROP ANY OPERATOR TO "BIOMART_USER";
GRANT ALTER ANY OPERATOR TO "BIOMART_USER";
GRANT CREATE ANY OPERATOR TO "BIOMART_USER";
GRANT CREATE OPERATOR TO "BIOMART_USER";
GRANT EXECUTE ANY LIBRARY TO "BIOMART_USER";
GRANT DROP ANY LIBRARY TO "BIOMART_USER";
GRANT ALTER ANY LIBRARY TO "BIOMART_USER";
GRANT CREATE ANY LIBRARY TO "BIOMART_USER";
GRANT CREATE LIBRARY TO "BIOMART_USER";
GRANT UNDER ANY TYPE TO "BIOMART_USER";
GRANT EXECUTE ANY TYPE TO "BIOMART_USER";
GRANT DROP ANY TYPE TO "BIOMART_USER";
GRANT ALTER ANY TYPE TO "BIOMART_USER";
GRANT CREATE ANY TYPE TO "BIOMART_USER";
GRANT CREATE TYPE TO "BIOMART_USER";
GRANT DROP ANY DIRECTORY TO "BIOMART_USER";
GRANT CREATE ANY DIRECTORY TO "BIOMART_USER";
GRANT DROP ANY MATERIALIZED VIEW TO "BIOMART_USER";
GRANT ALTER ANY MATERIALIZED VIEW TO "BIOMART_USER";
GRANT CREATE ANY MATERIALIZED VIEW TO "BIOMART_USER";
GRANT CREATE MATERIALIZED VIEW TO "BIOMART_USER";
GRANT GRANT ANY PRIVILEGE TO "BIOMART_USER";
GRANT ANALYZE ANY TO "BIOMART_USER";
GRANT ALTER RESOURCE COST TO "BIOMART_USER";
GRANT DROP PROFILE TO "BIOMART_USER";
GRANT ALTER PROFILE TO "BIOMART_USER";
GRANT CREATE PROFILE TO "BIOMART_USER";
GRANT DROP ANY TRIGGER TO "BIOMART_USER";
GRANT ALTER ANY TRIGGER TO "BIOMART_USER";
GRANT CREATE ANY TRIGGER TO "BIOMART_USER";
GRANT CREATE TRIGGER TO "BIOMART_USER";
GRANT EXECUTE ANY PROCEDURE TO "BIOMART_USER";
GRANT DROP ANY PROCEDURE TO "BIOMART_USER";
GRANT ALTER ANY PROCEDURE TO "BIOMART_USER";
GRANT CREATE ANY PROCEDURE TO "BIOMART_USER";
GRANT CREATE PROCEDURE TO "BIOMART_USER";
GRANT FORCE ANY TRANSACTION TO "BIOMART_USER";
GRANT FORCE TRANSACTION TO "BIOMART_USER";
GRANT ALTER DATABASE TO "BIOMART_USER";
GRANT AUDIT ANY TO "BIOMART_USER";
GRANT ALTER ANY ROLE TO "BIOMART_USER";
GRANT GRANT ANY ROLE TO "BIOMART_USER";
GRANT DROP ANY ROLE TO "BIOMART_USER";
GRANT CREATE ROLE TO "BIOMART_USER";
GRANT DROP PUBLIC DATABASE LINK TO "BIOMART_USER";
GRANT CREATE PUBLIC DATABASE LINK TO "BIOMART_USER";
GRANT CREATE DATABASE LINK TO "BIOMART_USER";
GRANT SELECT ANY SEQUENCE TO "BIOMART_USER";
GRANT DROP ANY SEQUENCE TO "BIOMART_USER";
GRANT ALTER ANY SEQUENCE TO "BIOMART_USER";
GRANT CREATE ANY SEQUENCE TO "BIOMART_USER";
GRANT CREATE SEQUENCE TO "BIOMART_USER";
GRANT DROP ANY VIEW TO "BIOMART_USER";
GRANT CREATE ANY VIEW TO "BIOMART_USER";
GRANT CREATE VIEW TO "BIOMART_USER";
GRANT DROP PUBLIC SYNONYM TO "BIOMART_USER";
GRANT CREATE PUBLIC SYNONYM TO "BIOMART_USER";
GRANT DROP ANY SYNONYM TO "BIOMART_USER";
GRANT CREATE ANY SYNONYM TO "BIOMART_USER";
GRANT CREATE SYNONYM TO "BIOMART_USER";
GRANT DROP ANY INDEX TO "BIOMART_USER";
GRANT ALTER ANY INDEX TO "BIOMART_USER";
GRANT CREATE ANY INDEX TO "BIOMART_USER";
GRANT DROP ANY CLUSTER TO "BIOMART_USER";
GRANT ALTER ANY CLUSTER TO "BIOMART_USER";
GRANT CREATE ANY CLUSTER TO "BIOMART_USER";
GRANT CREATE CLUSTER TO "BIOMART_USER";
GRANT DELETE ANY TABLE TO "BIOMART_USER";
GRANT UPDATE ANY TABLE TO "BIOMART_USER";
GRANT INSERT ANY TABLE TO "BIOMART_USER";
GRANT SELECT ANY TABLE TO "BIOMART_USER";
GRANT COMMENT ANY TABLE TO "BIOMART_USER";
GRANT LOCK ANY TABLE TO "BIOMART_USER";
GRANT DROP ANY TABLE TO "BIOMART_USER";
GRANT BACKUP ANY TABLE TO "BIOMART_USER";
GRANT ALTER ANY TABLE TO "BIOMART_USER";
GRANT CREATE ANY TABLE TO "BIOMART_USER";
GRANT CREATE TABLE TO "BIOMART_USER";
GRANT DROP ROLLBACK SEGMENT TO "BIOMART_USER";
GRANT ALTER ROLLBACK SEGMENT TO "BIOMART_USER";
GRANT CREATE ROLLBACK SEGMENT TO "BIOMART_USER";
GRANT DROP USER TO "BIOMART_USER";
GRANT ALTER USER TO "BIOMART_USER";
GRANT BECOME USER TO "BIOMART_USER";
GRANT CREATE USER TO "BIOMART_USER";
GRANT UNLIMITED TABLESPACE TO "BIOMART_USER";
GRANT DROP TABLESPACE TO "BIOMART_USER";
GRANT MANAGE TABLESPACE TO "BIOMART_USER";
GRANT ALTER TABLESPACE TO "BIOMART_USER";
GRANT CREATE TABLESPACE TO "BIOMART_USER";
GRANT RESTRICTED SESSION TO "BIOMART_USER";
GRANT ALTER SESSION TO "BIOMART_USER";
GRANT CREATE SESSION TO "BIOMART_USER";
GRANT AUDIT SYSTEM TO "BIOMART_USER";
GRANT ALTER SYSTEM TO "BIOMART_USER";
