--
-- Type: USER; Name: BIOMART_USER
--
CREATE USER "BIOMART_USER" IDENTIFIED BY VALUES 'S:93EE28544E6FC7E300217E2518289DBC8CFF729B685C2F62662B88C8D437;DBE9DFAEB8C02517'
   DEFAULT TABLESPACE "BIOMART"
   TEMPORARY TABLESPACE "TEMP";
--
-- Type: ROLE_GRANT; Name: BIOMART_USER
--
GRANT "CONNECT" TO "BIOMART_USER";
GRANT "RESOURCE" TO "BIOMART_USER";
GRANT "DBA" TO "BIOMART_USER";
--
-- Type: TABLESPACE_QUOTA; Name: BIOMART_USER
--
--
-- Type: SYSTEM_GRANT; Name: BIOMART_USER
--
GRANT UNLIMITED TABLESPACE TO "BIOMART_USER";
