--
-- Type: USER; Name: DEAPP
--
CREATE USER "DEAPP" IDENTIFIED BY VALUES 'S:6EAF5D82F8CCF2ED887A9EADCC8FFB0D8407BDB5A770F5B8442AE6586E05;2903F1A341F05B59'
   DEFAULT TABLESPACE "DEAPP"
   TEMPORARY TABLESPACE "TEMP";
--
-- Type: ROLE_GRANT; Name: DEAPP
--
GRANT "CONNECT" TO "DEAPP";
GRANT "RESOURCE" TO "DEAPP";
--
-- Type: SYSTEM_GRANT; Name: DEAPP
--
--
-- Type: TABLESPACE_QUOTA; Name: DEAPP
--
  DECLARE 
  TEMP_COUNT NUMBER; 
  SQLSTR VARCHAR2(200); 
BEGIN 
  SQLSTR := 'ALTER USER "DEAPP" QUOTA UNLIMITED ON "DEAPP"';
  EXECUTE IMMEDIATE SQLSTR;
EXCEPTION 
  WHEN OTHERS THEN
    IF SQLCODE = -30041 THEN 
      SQLSTR := 'SELECT COUNT(*) FROM USER_TABLESPACES 
              WHERE TABLESPACE_NAME = ''DEAPP'' AND CONTENTS = ''TEMPORARY''';
      EXECUTE IMMEDIATE SQLSTR INTO TEMP_COUNT;
      IF TEMP_COUNT = 1 THEN RETURN; 
      ELSE RAISE; 
      END IF;
    ELSE
      RAISE;
    END IF;
END;
/
