--
-- Type: USER; Name: FMAPP
--
CREATE USER "FMAPP" IDENTIFIED BY VALUES 'S:2AFD1E3EB1A960DE3051FCAEEF5E3AEB06302157ADD0D3240063327453F3;D684DB54467F1F56'
   DEFAULT TABLESPACE "TRANSMART"
   TEMPORARY TABLESPACE "TEMP";
--
-- Type: ROLE_GRANT; Name: FMAPP
--
--
-- Type: SYSTEM_GRANT; Name: FMAPP
--
GRANT CREATE TRIGGER TO "FMAPP";
GRANT CREATE PROCEDURE TO "FMAPP";
GRANT CREATE TABLE TO "FMAPP";
GRANT UNLIMITED TABLESPACE TO "FMAPP";
GRANT CREATE SESSION TO "FMAPP";
--
-- Type: TABLESPACE_QUOTA; Name: FMAPP
--
