--
-- Type: USER; Name: SEARCHAPP
--
CREATE USER "SEARCHAPP" IDENTIFIED BY VALUES 'S:57DA75ABEE52612397723961292319196AC869D3533AD0AEADAA85356BC3;ABAF57E22E1ABA89'
   DEFAULT TABLESPACE "TRANSMART"
   TEMPORARY TABLESPACE "TEMP";

--
-- Type: SYSTEM_GRANT; Name: SEARCHAPP
--
GRANT ON COMMIT REFRESH TO "SEARCHAPP";

GRANT CREATE MATERIALIZED VIEW TO "SEARCHAPP";
 

GRANT CREATE TABLE TO "SEARCHAPP";
GRANT UNLIMITED TABLESPACE TO "SEARCHAPP";
--
-- Type: ROLE_GRANT; Name: SEARCHAPP
--
GRANT "CONNECT" TO "SEARCHAPP";

GRANT "RESOURCE" TO "SEARCHAPP";

GRANT "DBA" TO "SEARCHAPP";
--
-- Type: TABLESPACE_QUOTA; Name: SEARCHAPP
--
