--
-- Type: USER; Name: SEARCHAPP
--
CREATE USER "SEARCHAPP" IDENTIFIED BY VALUES 'S:07917069594DA7D4E4D97B20A0DADE182065FFEEAAE89B601B4515537563;45E004F8677CE86F'
   DEFAULT TABLESPACE "BIOMART"
   TEMPORARY TABLESPACE "TEMP";
--
-- Type: SYSTEM_GRANT; Name: SEARCHAPP
--
GRANT ON COMMIT REFRESH TO "SEARCHAPP";
GRANT CREATE TABLE TO "SEARCHAPP";
--
-- Type: ROLE_GRANT; Name: SEARCHAPP
--
GRANT "CONNECT" TO "SEARCHAPP";
GRANT "RESOURCE" TO "SEARCHAPP";
--
-- Type: TABLESPACE_QUOTA; Name: SEARCHAPP
--
  DECLARE 
  TEMP_COUNT NUMBER; 
  SQLSTR VARCHAR2(200); 
BEGIN 
  SQLSTR := 'ALTER USER "SEARCHAPP" QUOTA UNLIMITED ON "BIOMART"';
  EXECUTE IMMEDIATE SQLSTR;
EXCEPTION 
  WHEN OTHERS THEN
    IF SQLCODE = -30041 THEN 
      SQLSTR := 'SELECT COUNT(*) FROM USER_TABLESPACES 
              WHERE TABLESPACE_NAME = ''BIOMART'' AND CONTENTS = ''TEMPORARY''';
      EXECUTE IMMEDIATE SQLSTR INTO TEMP_COUNT;
      IF TEMP_COUNT = 1 THEN RETURN; 
      ELSE RAISE; 
      END IF;
    ELSE
      RAISE;
    END IF;
END;
/
