--
-- Type: USER; Name: SEARCHAPP
--
CREATE USER "SEARCHAPP" IDENTIFIED BY VALUES 'S:07917069594DA7D4E4D97B20A0DADE182065FFEEAAE89B601B4515537563;45E004F8677CE86F'
   DEFAULT TABLESPACE "BIOMART"
   TEMPORARY TABLESPACE "TEMP";
--
-- Type: SYSTEM_GRANT; Name: SEARCHAPP
--
GRANT ON COMMIT REFRESH TO "SEARCHAPP";
GRANT UNLIMITED TABLESPACE TO "SEARCHAPP";
--
-- Type: ROLE_GRANT; Name: SEARCHAPP
--
GRANT "CONNECT" TO "SEARCHAPP";
GRANT "RESOURCE" TO "SEARCHAPP";
GRANT "DBA" TO "SEARCHAPP";
--
-- Type: TABLESPACE_QUOTA; Name: SEARCHAPP
--
