--
-- Type: USER; Name: TM_LZ
--
CREATE USER "TM_LZ" IDENTIFIED BY VALUES 'S:1530CD643380D7DF1FA75FFE22FD1EC4C38A926C18EBBE3BEAC72F035892;25AB313CFDB51ABC'
   DEFAULT TABLESPACE "TRANSMART"
   TEMPORARY TABLESPACE "TEMP";
--
-- Type: SYSTEM_GRANT; Name: TM_LZ
--
GRANT UNLIMITED TABLESPACE TO "TM_LZ";
--
-- Type: TABLESPACE_QUOTA; Name: TM_LZ
--
--
-- Type: ROLE_GRANT; Name: TM_LZ
--
GRANT "CONNECT" TO "TM_LZ";
GRANT "RESOURCE" TO "TM_LZ";
GRANT "DBA" TO "TM_LZ";
