--
-- Type: USER; Name: TM_WZ
--
CREATE USER "TM_WZ" IDENTIFIED BY VALUES 'S:5C075D654B4CA2B2A871DE1C8388A17D9F0CD0F954856D38CE5FEFF482AB;1A80C32171BA20A4'
   DEFAULT TABLESPACE "TRANSMART"
   TEMPORARY TABLESPACE "TEMP";
--
-- Type: SYSTEM_GRANT; Name: TM_WZ
--
GRANT UNLIMITED TABLESPACE TO "TM_WZ";
--
-- Type: TABLESPACE_QUOTA; Name: TM_WZ
--
--
-- Type: ROLE_GRANT; Name: TM_WZ
--
GRANT "CONNECT" TO "TM_WZ";
GRANT "RESOURCE" TO "TM_WZ";
GRANT "DBA" TO "TM_WZ";
