GRANT SELECT, INSERT, UPDATE, DELETE ON TS_BATCH.BATCH_JOB_INSTANCE TO TM_CZ;
GRANT SELECT, INSERT, UPDATE, DELETE ON TS_BATCH.BATCH_JOB_EXECUTION TO TM_CZ;
GRANT SELECT, INSERT, UPDATE, DELETE ON TS_BATCH.BATCH_JOB_EXECUTION_PARAMS TO TM_CZ;
GRANT SELECT, INSERT, UPDATE, DELETE ON TS_BATCH.BATCH_STEP_EXECUTION TO TM_CZ;
GRANT SELECT, INSERT, UPDATE, DELETE ON TS_BATCH.BATCH_STEP_EXECUTION_CONTEXT TO TM_CZ;
GRANT SELECT, INSERT, UPDATE, DELETE ON TS_BATCH.BATCH_JOB_EXECUTION_CONTEXT TO TM_CZ;
GRANT SELECT ON TS_BATCH.BATCH_STEP_EXECUTION_SEQ TO TM_CZ;
GRANT SELECT ON TS_BATCH.BATCH_JOB_EXECUTION_SEQ TO TM_CZ;
GRANT SELECT ON TS_BATCH.BATCH_JOB_SEQ TO TM_CZ;

CREATE OR REPLACE SYNONYM TM_CZ.BATCH_JOB_INSTANCE FOR TS_BATCH.BATCH_JOB_INSTANCE;
CREATE OR REPLACE SYNONYM TM_CZ.BATCH_JOB_EXECUTION FOR TS_BATCH.BATCH_JOB_EXECUTION;
CREATE OR REPLACE SYNONYM TM_CZ.BATCH_JOB_EXECUTION_PARAMS FOR TS_BATCH.BATCH_JOB_EXECUTION_PARAMS;
CREATE OR REPLACE SYNONYM TM_CZ.BATCH_STEP_EXECUTION FOR TS_BATCH.BATCH_STEP_EXECUTION;
CREATE OR REPLACE SYNONYM TM_CZ.BATCH_STEP_EXECUTION_CONTEXT FOR TS_BATCH.BATCH_STEP_EXECUTION_CONTEXT;
CREATE OR REPLACE SYNONYM TM_CZ.BATCH_JOB_EXECUTION_CONTEXT FOR TS_BATCH.BATCH_JOB_EXECUTION_CONTEXT;
CREATE OR REPLACE SYNONYM TM_CZ.BATCH_STEP_EXECUTION_SEQ FOR TS_BATCH.BATCH_STEP_EXECUTION_SEQ;
CREATE OR REPLACE SYNONYM TM_CZ.BATCH_JOB_EXECUTION_SEQ FOR TS_BATCH.BATCH_JOB_EXECUTION_SEQ;
CREATE OR REPLACE SYNONYM TM_CZ.BATCH_JOB_SEQ FOR TS_BATCH.BATCH_JOB_SEQ;

-- we shouldn't be creating objects in SYSTEM, but we use this for the travis tests
CREATE OR REPLACE SYNONYM SYSTEM.BATCH_JOB_INSTANCE FOR TS_BATCH.BATCH_JOB_INSTANCE;
CREATE OR REPLACE SYNONYM SYSTEM.BATCH_JOB_EXECUTION FOR TS_BATCH.BATCH_JOB_EXECUTION;
CREATE OR REPLACE SYNONYM SYSTEM.BATCH_JOB_EXECUTION_PARAMS FOR TS_BATCH.BATCH_JOB_EXECUTION_PARAMS;
CREATE OR REPLACE SYNONYM SYSTEM.BATCH_STEP_EXECUTION FOR TS_BATCH.BATCH_STEP_EXECUTION;
CREATE OR REPLACE SYNONYM SYSTEM.BATCH_STEP_EXECUTION_CONTEXT FOR TS_BATCH.BATCH_STEP_EXECUTION_CONTEXT;
CREATE OR REPLACE SYNONYM SYSTEM.BATCH_JOB_EXECUTION_CONTEXT FOR TS_BATCH.BATCH_JOB_EXECUTION_CONTEXT;
CREATE OR REPLACE SYNONYM SYSTEM.BATCH_STEP_EXECUTION_SEQ FOR TS_BATCH.BATCH_STEP_EXECUTION_SEQ;
CREATE OR REPLACE SYNONYM SYSTEM.BATCH_JOB_EXECUTION_SEQ FOR TS_BATCH.BATCH_JOB_EXECUTION_SEQ;
CREATE OR REPLACE SYNONYM SYSTEM.BATCH_JOB_SEQ FOR TS_BATCH.BATCH_JOB_SEQ;

ALTER TABLE TS_BATCH.BATCH_JOB_INSTANCE MOVE TABLESPACE TRANSMART;
ALTER TABLE TS_BATCH.BATCH_JOB_EXECUTION MOVE TABLESPACE TRANSMART;
ALTER TABLE TS_BATCH.BATCH_JOB_EXECUTION_PARAMS MOVE TABLESPACE TRANSMART;
ALTER TABLE TS_BATCH.BATCH_STEP_EXECUTION MOVE TABLESPACE TRANSMART;
ALTER TABLE TS_BATCH.BATCH_STEP_EXECUTION_CONTEXT MOVE TABLESPACE TRANSMART;
ALTER TABLE TS_BATCH.BATCH_JOB_EXECUTION_CONTEXT MOVE TABLESPACE TRANSMART;

