--
-- Type: TABLE; Owner: BIOMART; Name: BIO_ASSAY_ANALYSIS_EXT
--
 CREATE TABLE "BIOMART"."BIO_ASSAY_ANALYSIS_EXT"
  (	"BIO_ASSAY_ANALYSIS_EXT_ID" NUMBER NOT NULL ENABLE,
"BIO_ASSAY_ANALYSIS_ID" NUMBER NOT NULL ENABLE,
"VENDOR" VARCHAR2(500 BYTE),
"VENDOR_TYPE" VARCHAR2(500 BYTE),
"GENOME_VERSION" VARCHAR2(500 BYTE),
"TISSUE" VARCHAR2(500 BYTE),
"CELL_TYPE" VARCHAR2(500 BYTE),
"POPULATION" VARCHAR2(500 BYTE),
"RESEARCH_UNIT" VARCHAR2(500 BYTE),
"SAMPLE_SIZE" VARCHAR2(500 BYTE),
"MODEL_NAME" VARCHAR2(100 BYTE),
"MODEL_DESC" VARCHAR2(500 BYTE),
"SENSITIVE_FLAG" NUMBER(*,0),
"SENSITIVE_DESC" VARCHAR2(500 BYTE),
"PERCENT_MALE" NUMBER,
"EFFECT_TYPE" VARCHAR2(100 BYTE),
"EFFECT_UNITS" VARCHAR2(100 BYTE),
"EFFECT_ERROR1_TYPE" VARCHAR2(100 BYTE),
"EFFECT_ERROR2_TYPE" VARCHAR2(100 BYTE),
"EFFECT_ERROR_DESC" VARCHAR2(1000 BYTE),
"TRAIT" VARCHAR2(255 BYTE),
"REQUESTOR" VARCHAR2(100 BYTE),
"DATA_OWNER" VARCHAR2(100 BYTE),
"SD_TRAIT_POPULATION" NUMBER,
 CONSTRAINT "PK_BIO_ASY_ANALY_EXT" PRIMARY KEY ("BIO_ASSAY_ANALYSIS_EXT_ID")
 USING INDEX
 TABLESPACE "TRANSMART"  ENABLE
  ) SEGMENT CREATION IMMEDIATE
NOCOMPRESS LOGGING
 TABLESPACE "TRANSMART" ;
--
-- Type: INDEX; Owner: BIOMART; Name: BIO_ASSAY_ANALYSIS_EXT_IDX1
--
CREATE INDEX "BIOMART"."BIO_ASSAY_ANALYSIS_EXT_IDX1" ON "BIOMART"."BIO_ASSAY_ANALYSIS_EXT" ("BIO_ASSAY_ANALYSIS_ID")
TABLESPACE "INDX" ;
--
-- Type: REF_CONSTRAINT; Owner: BIOMART; Name: FK_ASY_ANALYSIS_EXT_ANALY
--
ALTER TABLE "BIOMART"."BIO_ASSAY_ANALYSIS_EXT" ADD CONSTRAINT "FK_ASY_ANALYSIS_EXT_ANALY" FOREIGN KEY ("BIO_ASSAY_ANALYSIS_ID")
 REFERENCES "BIOMART"."BIO_ASSAY_ANALYSIS" ("BIO_ASSAY_ANALYSIS_ID") ENABLE;
