--
-- Type: TABLE; Owner: BIOMART; Name: BIO_RECOMBINATION_RATES
--
 CREATE TABLE "BIOMART"."BIO_RECOMBINATION_RATES"
  (	"CHROMOSOME" VARCHAR2(20 BYTE),
"POSITION" NUMBER(18,0),
"RATE" NUMBER(18,6),
"MAP" NUMBER(18,6)
  ) SEGMENT CREATION IMMEDIATE
NOCOMPRESS LOGGING
 TABLESPACE "TRANSMART" ;
--
-- Type: INDEX; Owner: BIOMART; Name: IDX_BIO_RECOMB_1
--
CREATE INDEX "BIOMART"."IDX_BIO_RECOMB_1" ON "BIOMART"."BIO_RECOMBINATION_RATES" ("POSITION", "CHROMOSOME")
TABLESPACE "TRANSMART" ;
