--
-- BIO_ASY_PLATFORM_PROBE_ANNO  (Table) 
--
CREATE TABLE BIOMART.BIO_ASY_PLATFORM_PROBE_ANNO
(
  BIO_ASY_PLATFORM_PROBE_ANNO_ID  NUMBER(22)    NOT NULL,
  BIO_ASY_GENO_PLATFORM_PROBE_ID  NUMBER(22)    NOT NULL,
  GENOTYPE_PROBE_ANNOTATION_ID    NUMBER(22)    NOT NULL,
  BIO_ASSAY_PLATFORM_ID           NUMBER(18)    NOT NULL,
  GENOME_BUILD                    VARCHAR2(10 BYTE),
  CREATED_BY                      VARCHAR2(30 BYTE),
  CREATED_DATE                    DATE,
  MODIFIED_BY                     VARCHAR2(30 BYTE),
  MODIFIED_DATE                   DATE
) SEGMENT CREATION IMMEDIATE
TABLESPACE TRANSMART;

--
-- IDX_BIO_ASY_PPANNO_ANNO  (Index) 
--
CREATE INDEX BIOMART.IDX_BIO_ASY_PPANNO_ANNO ON BIOMART.BIO_ASY_PLATFORM_PROBE_ANNO
(GENOTYPE_PROBE_ANNOTATION_ID)
NOLOGGING
TABLESPACE INDX;

--
-- IDX_BIO_ASY_PPANNO_PLATFORM  (Index) 
--
CREATE INDEX BIOMART.IDX_BIO_ASY_PPANNO_PLATFORM ON BIOMART.BIO_ASY_PLATFORM_PROBE_ANNO
(BIO_ASSAY_PLATFORM_ID)
NOLOGGING
TABLESPACE INDX;


--
-- IDX_BIO_ASY_PPANNO_PROBE  (Index) 
--
CREATE INDEX BIOMART.IDX_BIO_ASY_PPANNO_PROBE ON BIOMART.BIO_ASY_PLATFORM_PROBE_ANNO
(BIO_ASY_GENO_PLATFORM_PROBE_ID)
NOLOGGING
TABLESPACE INDX;


--
-- PK_BIO_ASY_PLATFORM_PROBE_ANNO  (Index) 
--
CREATE UNIQUE INDEX BIOMART.PK_BIO_ASY_PLATFORM_PROBE_ANNO ON BIOMART.BIO_ASY_PLATFORM_PROBE_ANNO
(BIO_ASY_PLATFORM_PROBE_ANNO_ID)
NOLOGGING
TABLESPACE INDX;

--
-- TRG_BIO_ASY_PPA  (Trigger) 
--
/* Formatted on 10/13/2016 2:54:22 PM (QP5 v5.215.12089.38647) */
CREATE OR REPLACE TRIGGER BIOMART.TRG_BIO_ASY_PPA
   BEFORE INSERT
   ON BIOMART.BIO_ASY_PLATFORM_PROBE_ANNO
   FOR EACH ROW
BEGIN
   IF INSERTING
   THEN
      IF :NEW."BIO_ASY_PLATFORM_PROBE_ANNO_ID" IS NULL
      THEN
         SELECT BIOMART.SEQ_BIO_ASY_PPA.NEXTVAL
           INTO :NEW."BIO_ASY_PLATFORM_PROBE_ANNO_ID"
           FROM DUAL;
      END IF;
   END IF;
END;
/

-- 
-- Non Foreign Key Constraints for Table BIO_ASY_PLATFORM_PROBE_ANNO 
-- 
ALTER TABLE BIOMART.BIO_ASY_PLATFORM_PROBE_ANNO ADD (
  CONSTRAINT PK_BIO_ASY_PLATFORM_PROBE_ANNO
  PRIMARY KEY
  (BIO_ASY_PLATFORM_PROBE_ANNO_ID)
  USING INDEX BIOMART.PK_BIO_ASY_PLATFORM_PROBE_ANNO
  ENABLE VALIDATE);
  
-- 
-- Foreign Key Constraints for Table BIO_ASY_PLATFORM_PROBE_ANNO 
-- 
ALTER TABLE BIOMART.BIO_ASY_PLATFORM_PROBE_ANNO ADD (
  CONSTRAINT FK_BIO_ASY_PPA_GP_PROBE 
  FOREIGN KEY (BIO_ASY_GENO_PLATFORM_PROBE_ID) 
  REFERENCES BIOMART.BIO_ASSAY_GENO_PLATFORM_PROBE (BIO_ASY_GENO_PLATFORM_PROBE_ID)
  ENABLE VALIDATE,
  CONSTRAINT FK_BIO_ASY_PPA_PLATFORM 
  FOREIGN KEY (BIO_ASSAY_PLATFORM_ID) 
  REFERENCES BIOMART.BIO_ASSAY_PLATFORM (BIO_ASSAY_PLATFORM_ID)
  ENABLE VALIDATE,
  CONSTRAINT FK_BIO_ASY_PPA_PROBE_ANNO 
  FOREIGN KEY (GENOTYPE_PROBE_ANNOTATION_ID) 
  REFERENCES BIOMART.GENOTYPE_PROBE_ANNOTATION (GENOTYPE_PROBE_ANNOTATION_ID)
  ENABLE VALIDATE);