--
-- Type: INDEX; Owner: BIOMART; Name: BIO_MARKER_CORREL_MV_ABM_IDX
--
CREATE INDEX "BIOMART"."BIO_MARKER_CORREL_MV_ABM_IDX" ON "BIOMART"."BIO_MARKER_CORREL_MV" ("ASSO_BIO_MARKER_ID")
TABLESPACE "TRANSMART" ;
