--
-- Type: TABLE; Owner: BIOMART; Name: BIO_COHORT_EXP_XREF
--
 CREATE TABLE "BIOMART"."BIO_COHORT_EXP_XREF" 
  (	"STUDY_ID" VARCHAR2(255 BYTE), 
"COHORT_ID" VARCHAR2(255 BYTE), 
"EXP_ID" VARCHAR2(255 BYTE)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

