--
-- Type: INDEX; Owner: BIOMART; Name: BIO_MARKER_EXP_AYLS_MV_INDEX1
--
CREATE INDEX "BIOMART"."BIO_MARKER_EXP_AYLS_MV_INDEX1" ON "BIOMART"."BIO_MARKER_EXP_ANALYSIS_MV_10" ("BIO_MARKER_ID")
TABLESPACE "TRANSMART" ;
