--
-- Type: TABLE; Owner: BIOMART; Name: BIO_SPECIES_ORGANISM
--
 CREATE TABLE "BIOMART"."BIO_SPECIES_ORGANISM" 
  (	"ID" NUMBER, 
"SPECIES" VARCHAR2(200 BYTE), 
"ORGANISM" VARCHAR2(200 BYTE)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

