--
-- Type: TABLE; Owner: BIOMART; Name: BIO_ASSAY_ANALYSIS_GWAS
--
 CREATE TABLE "BIOMART"."BIO_ASSAY_ANALYSIS_GWAS"
  (	"BIO_ASY_ANALYSIS_GWAS_ID" NUMBER(18,0) NOT NULL ENABLE,
"BIO_ASSAY_ANALYSIS_ID" NUMBER(18,0) NOT NULL ENABLE,
"RS_ID" NVARCHAR2(50),
"P_VALUE_CHAR" VARCHAR2(100 BYTE),
"P_VALUE" BINARY_DOUBLE,
"LOG_P_VALUE" BINARY_DOUBLE,
"ETL_ID" NUMBER(18,0),
"EXT_DATA" VARCHAR2(4000 BYTE),
"EFFECT_ALLELE" VARCHAR2(30 BYTE),
"OTHER_ALLELE" VARCHAR2(30 BYTE),
"PASS_FAIL" CHAR(1 BYTE),
"PROBE_NAME" VARCHAR2(100 BYTE),
"BIO_ASY_GENO_PLATFORM_PROBE_ID" NUMBER(22,0),
"BETA" BINARY_DOUBLE,
"STANDARD_ERROR" BINARY_DOUBLE,
"GENO_PLATFORM_PROBE_ID" NUMBER(22,0),
"BETA_OLD" NUMBER,
"STANDARD_ERROR_OLD" NUMBER,
"EFFECT_ALLELE_CLOB" CLOB,
"OTHER_ALLELE_CLOB" CLOB,
"CREATED_BY" VARCHAR2(30 BYTE),
"CREATED_DATE" DATE,
"MODIFIED_BY" VARCHAR2(30 BYTE),
"MODIFIED_DATE" DATE,
 CONSTRAINT "BIO_ASY_ANALYSIS_GWAS_ID_PK" PRIMARY KEY ("BIO_ASY_ANALYSIS_GWAS_ID")
 USING INDEX
 TABLESPACE "INDX"  ENABLE
  )
COMPRESS BASIC  NOLOGGING
 TABLESPACE "TRANSMART"
LOB ("EFFECT_ALLELE_CLOB") STORE AS BASICFILE (
 ENABLE STORAGE IN ROW CHUNK 8192 RETENTION
 NOCACHE LOGGING )
LOB ("OTHER_ALLELE_CLOB") STORE AS BASICFILE (
 ENABLE STORAGE IN ROW CHUNK 8192 RETENTION
 NOCACHE LOGGING )
 PARTITION BY LIST ("BIO_ASSAY_ANALYSIS_ID")
(PARTITION "NULL_PARTITION"  VALUES (NULL) SEGMENT CREATION IMMEDIATE
COMPRESS BASIC NOLOGGING
 TABLESPACE "TRANSMART"
LOB ("EFFECT_ALLELE_CLOB") STORE AS SECUREFILE (
 TABLESPACE "TRANSMART" ENABLE STORAGE IN ROW CHUNK 8192
 NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES )
LOB ("OTHER_ALLELE_CLOB") STORE AS SECUREFILE (
 TABLESPACE "TRANSMART" ENABLE STORAGE IN ROW CHUNK 8192
 NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ) ;
--
-- Type: INDEX; Owner: BIOMART; Name: IDX2_BIO_ASSAY_ANALYSIS_GWAS
--
CREATE INDEX "BIOMART"."IDX2_BIO_ASSAY_ANALYSIS_GWAS" ON "BIOMART"."BIO_ASSAY_ANALYSIS_GWAS" ("RS_ID")
TABLESPACE "TRANSMART" ;
--
-- Type: REF_CONSTRAINT; Owner: BIOMART; Name: FK_GWAS_GENO_PLATFORM_PROBE
--
ALTER TABLE "BIOMART"."BIO_ASSAY_ANALYSIS_GWAS" ADD CONSTRAINT "FK_GWAS_GENO_PLATFORM_PROBE" FOREIGN KEY ("GENO_PLATFORM_PROBE_ID")
 REFERENCES "BIOMART"."BIO_ASSAY_GENO_PLATFORM_PROBE" ("BIO_ASY_GENO_PLATFORM_PROBE_ID") ENABLE;
--
-- Type: REF_CONSTRAINT; Owner: BIOMART; Name: FK_GWAS_BIO_AA
--
ALTER TABLE "BIOMART"."BIO_ASSAY_ANALYSIS_GWAS" ADD CONSTRAINT "FK_GWAS_BIO_AA" FOREIGN KEY ("BIO_ASSAY_ANALYSIS_ID")
 REFERENCES "BIOMART"."BIO_ASSAY_ANALYSIS" ("BIO_ASSAY_ANALYSIS_ID") ENABLE;
--
-- Type: INDEX; Owner: BIOMART; Name: IDX_GWAS_GENO_PLTFM_PROBE_ID
--
CREATE INDEX "BIOMART"."IDX_GWAS_GENO_PLTFM_PROBE_ID" ON "BIOMART"."BIO_ASSAY_ANALYSIS_GWAS" ("GENO_PLATFORM_PROBE_ID")
TABLESPACE "TRANSMART" ;
