--
-- Type: TABLE; Owner: BIOMART; Name: BIO_ASSAY_GENO_PLATFORM_PROBE
--
 CREATE TABLE "BIOMART"."BIO_ASSAY_GENO_PLATFORM_PROBE"
  (	"BIO_ASY_GENO_PLATFORM_PROBE_ID" NUMBER(18,0) NOT NULL ENABLE,
"BIO_ASSAY_PLATFORM_ID" NUMBER(18,0) NOT NULL ENABLE,
"ORIG_CHROM" VARCHAR2(5 BYTE),
"ORIG_POSITION" NUMBER,
"ORIG_GENOME_BUILD" VARCHAR2(20 BYTE),
"PROBE_NAME" VARCHAR2(200 BYTE),
"IS_CONTROL" CHAR(1 BYTE),
"CREATED_BY" VARCHAR2(30 BYTE),
"CREATED_DATE" DATE,
"MODIFIED_BY" VARCHAR2(30 BYTE),
"MODIFIED_DATE" DATE,
 CONSTRAINT "PK_BIO_ASY_GP_PROBE" PRIMARY KEY ("BIO_ASY_GENO_PLATFORM_PROBE_ID")
 USING INDEX (CREATE UNIQUE INDEX "BIOMART"."IDX_BIO_ASSAY_GP_PROBE_PK" ON "BIOMART"."BIO_ASSAY_GENO_PLATFORM_PROBE" ("BIO_ASY_GENO_PLATFORM_PROBE_ID")
 TABLESPACE "TRANSMART" )  ENABLE
  ) SEGMENT CREATION DEFERRED
NOCOMPRESS LOGGING
 TABLESPACE "TRANSMART" ;
--
-- Type: SEQUENCE; Owner: BIOMART; Name: SEQ_GENO_PLATFORM_PROBE_ID
--
CREATE SEQUENCE  "BIOMART"."SEQ_GENO_PLATFORM_PROBE_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 165651293 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--
-- Type: INDEX; Owner: BIOMART; Name: IDX_BIO_ASY_GPP_PROBE_NAME
--
CREATE INDEX "BIOMART"."IDX_BIO_ASY_GPP_PROBE_NAME" ON "BIOMART"."BIO_ASSAY_GENO_PLATFORM_PROBE" ("PROBE_NAME")
TABLESPACE "TRANSMART" ;
--
-- Type: INDEX; Owner: BIOMART; Name: IDX_BIO_ASY_GPP_PLATFORM
--
CREATE INDEX "BIOMART"."IDX_BIO_ASY_GPP_PLATFORM" ON "BIOMART"."BIO_ASSAY_GENO_PLATFORM_PROBE" ("BIO_ASSAY_PLATFORM_ID")
TABLESPACE "TRANSMART" ;
--
-- Type: REF_CONSTRAINT; Owner: BIOMART; Name: FK_BIO_ASY_GP_PROBE_ASY_PLF
--
ALTER TABLE "BIOMART"."BIO_ASSAY_GENO_PLATFORM_PROBE" ADD CONSTRAINT "FK_BIO_ASY_GP_PROBE_ASY_PLF" FOREIGN KEY ("BIO_ASSAY_PLATFORM_ID")
 REFERENCES "BIOMART"."BIO_ASSAY_PLATFORM" ("BIO_ASSAY_PLATFORM_ID") ENABLE;
--
-- Type: TRIGGER; Owner: BIOMART; Name: TRG_GENO_PLATFORM_PROBE_ID
--
  CREATE OR REPLACE TRIGGER "BIOMART"."TRG_GENO_PLATFORM_PROBE_ID"
   BEFORE INSERT
   ON "BIOMART"."BIO_ASSAY_GENO_PLATFORM_PROBE"
   FOR EACH ROW
BEGIN
   IF INSERTING
   THEN
      IF :NEW."BIO_ASY_GENO_PLATFORM_PROBE_ID" IS NULL
      THEN
         SELECT BIOMART.SEQ_GENO_PLATFORM_PROBE_ID.NEXTVAL
           INTO :NEW."BIO_ASY_GENO_PLATFORM_PROBE_ID"
           FROM DUAL;
      END IF;
   END IF;
END;
/
ALTER TRIGGER "BIOMART"."TRG_GENO_PLATFORM_PROBE_ID" ENABLE;
