CREATE TABLE BIOMART.BIO_ASSAY_GENO_PLATFORM_PROBE
(
  BIO_ASY_GENO_PLATFORM_PROBE_ID  NUMBER(18)    NOT NULL,
  BIO_ASSAY_PLATFORM_ID           NUMBER(18)    NOT NULL,
  ORIG_CHROM                      VARCHAR2(5 BYTE),
  ORIG_POSITION                   NUMBER,
  ORIG_GENOME_BUILD               VARCHAR2(20 BYTE),
  PROBE_NAME                      VARCHAR2(200 BYTE),
  IS_CONTROL                      CHAR(1 BYTE),
  CREATED_BY                      VARCHAR2(30 BYTE),
  CREATED_DATE                    DATE,
  MODIFIED_BY                     VARCHAR2(30 BYTE),
  MODIFIED_DATE                   DATE
) SEGMENT CREATION IMMEDIATE
TABLESPACE TRANSMART;

CREATE UNIQUE INDEX BIOMART.IDX_BIO_ASSAY_GP_PROBE_PK ON BIOMART.BIO_ASSAY_GENO_PLATFORM_PROBE
(BIO_ASY_GENO_PLATFORM_PROBE_ID)
TABLESPACE INDX;


CREATE INDEX BIOMART.IDX_BIO_ASY_GPP_PLATFORM ON BIOMART.BIO_ASSAY_GENO_PLATFORM_PROBE
(BIO_ASSAY_PLATFORM_ID)
TABLESPACE INDX;
  
CREATE INDEX BIOMART.IDX_BIO_ASY_GPP_PROBE_NAME ON BIOMART.BIO_ASSAY_GENO_PLATFORM_PROBE
(PROBE_NAME)
TABLESPACE INDX;

--
-- TRG_GENO_PLATFORM_PROBE_ID  (Trigger) 
--
CREATE OR REPLACE TRIGGER BIOMART.TRG_GENO_PLATFORM_PROBE_ID
   BEFORE INSERT
   ON "BIOMART"."BIO_ASSAY_GENO_PLATFORM_PROBE"
   FOR EACH ROW
BEGIN
   IF INSERTING
   THEN
      IF :NEW."BIO_ASY_GENO_PLATFORM_PROBE_ID" IS NULL
      THEN
         SELECT BIOMART.SEQ_GENO_PLATFORM_PROBE_ID.NEXTVAL
           INTO :NEW."BIO_ASY_GENO_PLATFORM_PROBE_ID"
           FROM DUAL;
      END IF;
   END IF;
END;
/

-- 
-- Non Foreign Key Constraints for Table BIO_ASSAY_GENO_PLATFORM_PROBE 
-- 
ALTER TABLE BIOMART.BIO_ASSAY_GENO_PLATFORM_PROBE ADD (
  CONSTRAINT PK_BIO_ASY_GP_PROBE
  PRIMARY KEY
  (BIO_ASY_GENO_PLATFORM_PROBE_ID)
  USING INDEX BIOMART.IDX_BIO_ASSAY_GP_PROBE_PK
  ENABLE VALIDATE);

-- 
-- Foreign Key Constraints for Table BIO_ASSAY_GENO_PLATFORM_PROBE 
-- 
ALTER TABLE BIOMART.BIO_ASSAY_GENO_PLATFORM_PROBE ADD (
  CONSTRAINT FK_BIO_ASY_GP_PROBE_ASY_PLF 
  FOREIGN KEY (BIO_ASSAY_PLATFORM_ID) 
  REFERENCES BIOMART.BIO_ASSAY_PLATFORM (BIO_ASSAY_PLATFORM_ID)
  ENABLE VALIDATE);