--
-- Type: TABLE; Owner: BIOMART; Name: BIO_ASY_ANALYSIS_GWAS_TOP50
--
 CREATE TABLE "BIOMART"."BIO_ASY_ANALYSIS_GWAS_TOP50"
  (	"BIO_ASSAY_ANALYSIS_ID" NUMBER,
"CHROM" VARCHAR2(4 BYTE),
"POS" NUMBER(10,0),
"RSGENE" VARCHAR2(200 BYTE),
"PVALUE" BINARY_DOUBLE,
"LOGPVALUE" BINARY_DOUBLE,
"EXTDATA" VARCHAR2(4000 BYTE),
"RNUM" NUMBER,
"INTRONEXON" VARCHAR2(30 BYTE),
"RECOMBINATIONRATE" NUMBER(18,6),
"REGULOME" VARCHAR2(10 BYTE),
"ANALYSIS" VARCHAR2(500 BYTE),
"RSID" VARCHAR2(50 BYTE),
"EFFECT_ALLELE" VARCHAR2(30 BYTE),
"OTHER_ALLELE" VARCHAR2(30 BYTE),
"PROBE_NAME" VARCHAR2(50 BYTE),
"CREATED_BY" VARCHAR2(30 BYTE),
"CREATED_DATE" DATE,
"MODIFIED_BY" VARCHAR2(30 BYTE),
"MODIFIED_DATE" DATE,
"BETA" BINARY_DOUBLE,
"STANDARD_ERROR" BINARY_DOUBLE,
"PVALUE_CHAR" VARCHAR2(100 BYTE),
"STRAND" VARCHAR2(1 BYTE)
  ) SEGMENT CREATION IMMEDIATE
NOCOMPRESS LOGGING
 TABLESPACE "TRANSMART" ;
--
-- Type: INDEX; Owner: BIOMART; Name: IDX1_BIO_ASY_GWAS_T50
--
CREATE INDEX "BIOMART"."IDX1_BIO_ASY_GWAS_T50" ON "BIOMART"."BIO_ASY_ANALYSIS_GWAS_TOP50" ("BIO_ASSAY_ANALYSIS_ID")
TABLESPACE "TRANSMART" ;
--
-- Type: REF_CONSTRAINT; Owner: BIOMART; Name: FK_GWAS_TOP50_ASY_ANAL
--
ALTER TABLE "BIOMART"."BIO_ASY_ANALYSIS_GWAS_TOP50" ADD CONSTRAINT "FK_GWAS_TOP50_ASY_ANAL" FOREIGN KEY ("BIO_ASSAY_ANALYSIS_ID")
 REFERENCES "BIOMART"."BIO_ASSAY_ANALYSIS" ("BIO_ASSAY_ANALYSIS_ID") ENABLE;
--
-- Type: INDEX; Owner: BIOMART; Name: IDX2_BIO_ASY_GWAS_TOP50
--
CREATE INDEX "BIOMART"."IDX2_BIO_ASY_GWAS_TOP50" ON "BIOMART"."BIO_ASY_ANALYSIS_GWAS_TOP50" ("ANALYSIS")
TABLESPACE "TRANSMART" ;
