--
-- Type: TABLE; Owner: BIOMART; Name: BIOBANK_SAMPLE
--
 CREATE TABLE "BIOMART"."BIOBANK_SAMPLE" 
  (	"SAMPLE_TUBE_ID" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
"ACCESSION_NUMBER" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
"CLIENT_SAMPLE_TUBE_ID" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
"CONTAINER_ID" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
"IMPORT_DATE" TIMESTAMP (6), 
"SOURCE_TYPE" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
 CONSTRAINT "BIOBANK_SAMPLE_PKEY" PRIMARY KEY ("SAMPLE_TUBE_ID")
 USING INDEX
 TABLESPACE "TRANSMART"  ENABLE
  ) SEGMENT CREATION DEFERRED
 TABLESPACE "TRANSMART" ;

