--
-- Type: TABLE; Owner: BIOMART; Name: CTD_BIOMARKER
--
 CREATE TABLE "BIOMART"."CTD_BIOMARKER" 
  (	"CTD_STUDY_ID" NUMBER, 
"BIOMARKER_NAME" VARCHAR2(4000 BYTE), 
"BIOMARKER_PCT" VARCHAR2(4000 BYTE), 
"BIOMARKER_VALUE" VARCHAR2(4000 BYTE)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

