--
-- Type: TABLE; Owner: BIOMART; Name: CTD_SEC_ENDPTS
--
 CREATE TABLE "BIOMART"."CTD_SEC_ENDPTS" 
  (	"CTD_STUDY_ID" NUMBER, 
"SECONDARY_TYPE" VARCHAR2(4000 BYTE), 
"SECONDARY_TYPE_DEFINITION" VARCHAR2(4000 BYTE), 
"SECONDARY_TYPE_TIME_PERIOD" VARCHAR2(4000 BYTE), 
"SECONDARY_TYPE_CHANGE" VARCHAR2(4000 BYTE), 
"SECONDARY_TYPE_P_VALUE" VARCHAR2(4000 BYTE), 
"ID" NUMBER(18,0)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

