--
-- Type: TABLE; Owner: BIOMART; Name: CTD_ALLOWED_MEDS_TREATMENT
--
 CREATE TABLE "BIOMART"."CTD_ALLOWED_MEDS_TREATMENT" 
  (	"CTD_STUDY_ID" NUMBER, 
"TRTMT_OCS" VARCHAR2(4000 BYTE), 
"TRTMT_ICS" VARCHAR2(4000 BYTE), 
"TRTMT_LABA" VARCHAR2(4000 BYTE), 
"TRTMT_LTRA" VARCHAR2(4000 BYTE), 
"TRTMT_CORTICOSTEROIDS" VARCHAR2(4000 BYTE), 
"TRTMT_ANTI_FIBROTICS" VARCHAR2(4000 BYTE), 
"TRTMT_IMMUNOSUPPRESSIVE" VARCHAR2(4000 BYTE), 
"TRTMT_CYTOTOXIC" VARCHAR2(4000 BYTE)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

