--
-- GENOTYPE_PROBE_ANNOTATION  (Table) 
--
CREATE TABLE BIOMART.GENOTYPE_PROBE_ANNOTATION
(
  GENOTYPE_PROBE_ANNOTATION_ID  NUMBER(22)      NOT NULL,
  SNP_NAME                      VARCHAR2(50 BYTE),
  CHROM                         VARCHAR2(4 BYTE),
  POS                           NUMBER,
  REF                           VARCHAR2(4000 BYTE),
  ALT                           VARCHAR2(4000 BYTE),
  GENE_INFO                     VARCHAR2(4000 BYTE),
  VARIATION_CLASS               VARCHAR2(10 BYTE),
  STRAND                        VARCHAR2(1 BYTE),
  EXON_INTRON                   VARCHAR2(30 BYTE),
  GENOME_BUILD                  VARCHAR2(10 BYTE),
  SNP_SOURCE                    VARCHAR2(10 BYTE),
  RECOMBINATION_RATE            NUMBER(18,6),
  RECOMBINATION_MAP             NUMBER(18,6),
  REGULOME_SCORE                VARCHAR2(10 BYTE),
  REF_CLOB                      CLOB,
  ALT_CLOB                      CLOB,
  CREATED_BY                    VARCHAR2(30 BYTE),
  CREATED_DATE                  DATE,
  MODIFIED_BY                   VARCHAR2(30 BYTE),
  MODIFIED_DATE                 DATE
) SEGMENT CREATION IMMEDIATE
TABLESPACE TRANSMART;

--
-- IDX_GENO_ANNO_LOC  (Index) 
--
CREATE INDEX BIOMART.IDX_GENO_ANNO_LOC ON BIOMART.GENOTYPE_PROBE_ANNOTATION
(CHROM, POS)
TABLESPACE INDX;

--
-- IDX_PROBE_ANNO_SNP  (Index) 
--
CREATE INDEX BIOMART.IDX_PROBE_ANNO_SNP ON BIOMART.GENOTYPE_PROBE_ANNOTATION
(SNP_NAME)
  TABLESPACE INDX;
  
--
-- PK_GENO_PROBE_ANNOTATION  (Index) 
--
CREATE UNIQUE INDEX BIOMART.PK_GENO_PROBE_ANNOTATION ON BIOMART.GENOTYPE_PROBE_ANNOTATION
(GENOTYPE_PROBE_ANNOTATION_ID)
TABLESPACE INDX;
--
-- TRG_ANNOTATION_ID  (Trigger) 
--
/* Formatted on 10/13/2016 2:54:47 PM (QP5 v5.215.12089.38647) */
CREATE OR REPLACE TRIGGER BIOMART.TRG_ANNOTATION_ID
   BEFORE INSERT
   ON BIOMART.GENOTYPE_PROBE_ANNOTATION
   FOR EACH ROW
BEGIN
   IF INSERTING
   THEN
      IF :NEW.GENOTYPE_PROBE_ANNOTATION_ID IS NULL
      THEN
         SELECT SEQ_ANNOTATION_ID.NEXTVAL
           INTO :NEW.GENOTYPE_PROBE_ANNOTATION_ID
           FROM DUAL;
      END IF;
   END IF;
END;
/


-- 
-- Non Foreign Key Constraints for Table GENOTYPE_PROBE_ANNOTATION 
-- 
ALTER TABLE BIOMART.GENOTYPE_PROBE_ANNOTATION ADD (
  CONSTRAINT PK_GENO_PROBE_ANNOTATION
  PRIMARY KEY
  (GENOTYPE_PROBE_ANNOTATION_ID)
  USING INDEX BIOMART.PK_GENO_PROBE_ANNOTATION
  ENABLE VALIDATE);