--
-- Type: TABLE; Owner: BIOMART; Name: GENOTYPE_PROBE_ANNOTATION
--
 CREATE TABLE "BIOMART"."GENOTYPE_PROBE_ANNOTATION"
  (	"GENOTYPE_PROBE_ANNOTATION_ID" NUMBER(22,0) NOT NULL ENABLE,
"SNP_NAME" VARCHAR2(50 BYTE),
"CHROM" VARCHAR2(4 BYTE),
"POS" NUMBER,
"REF" VARCHAR2(4000 BYTE),
"ALT" VARCHAR2(4000 BYTE),
"GENE_INFO" VARCHAR2(4000 BYTE),
"VARIATION_CLASS" VARCHAR2(10 BYTE),
"STRAND" VARCHAR2(1 BYTE),
"EXON_INTRON" VARCHAR2(30 BYTE),
"GENOME_BUILD" VARCHAR2(10 BYTE),
"SNP_SOURCE" VARCHAR2(10 BYTE),
"RECOMBINATION_RATE" NUMBER(18,6),
"RECOMBINATION_MAP" NUMBER(18,6),
"REGULOME_SCORE" VARCHAR2(10 BYTE),
"REF_CLOB" CLOB,
"ALT_CLOB" CLOB,
"CREATED_BY" VARCHAR2(30 BYTE),
"CREATED_DATE" DATE,
"MODIFIED_BY" VARCHAR2(30 BYTE),
"MODIFIED_DATE" DATE,
 CONSTRAINT "PK_GENO_PROBE_ANNOTATION" PRIMARY KEY ("GENOTYPE_PROBE_ANNOTATION_ID")
 USING INDEX
 TABLESPACE "TRANSMART"  ENABLE
  ) SEGMENT CREATION IMMEDIATE
NOCOMPRESS LOGGING
 TABLESPACE "TRANSMART"
LOB ("REF_CLOB") STORE AS SECUREFILE (
 TABLESPACE "TRANSMART" ENABLE STORAGE IN ROW CHUNK 8192
 NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES )
LOB ("ALT_CLOB") STORE AS SECUREFILE (
 TABLESPACE "TRANSMART" ENABLE STORAGE IN ROW CHUNK 8192
 NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
--
-- Type: SEQUENCE; Owner: BIOMART; Name: SEQ_ANNOTATION_ID
--
CREATE SEQUENCE  "BIOMART"."SEQ_ANNOTATION_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 149419095 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--
-- Type: INDEX; Owner: BIOMART; Name: IDX_GENO_ANNO_LOC
--
CREATE INDEX "BIOMART"."IDX_GENO_ANNO_LOC" ON "BIOMART"."GENOTYPE_PROBE_ANNOTATION" ("CHROM", "POS")
TABLESPACE "TRANSMART" ;
--
-- Type: INDEX; Owner: BIOMART; Name: IDX_PROBE_ANNO_SNP
--
CREATE INDEX "BIOMART"."IDX_PROBE_ANNO_SNP" ON "BIOMART"."GENOTYPE_PROBE_ANNOTATION" ("SNP_NAME")
TABLESPACE "TRANSMART" ;
--
-- Type: TRIGGER; Owner: BIOMART; Name: TRG_ANNOTATION_ID
--
  CREATE OR REPLACE TRIGGER "BIOMART"."TRG_ANNOTATION_ID"
   BEFORE INSERT
   ON BIOMART.GENOTYPE_PROBE_ANNOTATION
   FOR EACH ROW
BEGIN
   IF INSERTING
   THEN
      IF :NEW.GENOTYPE_PROBE_ANNOTATION_ID IS NULL
      THEN
         SELECT SEQ_ANNOTATION_ID.NEXTVAL
           INTO :NEW.GENOTYPE_PROBE_ANNOTATION_ID
           FROM DUAL;
      END IF;
   END IF;
END;
/
ALTER TRIGGER "BIOMART"."TRG_ANNOTATION_ID" ENABLE;
