--
-- Type: TABLE; Owner: BIOMART; Name: MESH_DESCRIPTOR
--
 CREATE TABLE "BIOMART"."MESH_DESCRIPTOR" 
  (	"MESH_DESCRIPTOR_ID" VARCHAR2(15 BYTE) NOT NULL ENABLE, 
"MESH_HEADING" VARCHAR2(256 BYTE), 
"MESH_ANNOTATION" VARCHAR2(2000 BYTE)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

