--
-- Type: TABLE; Owner: BIOMART; Name: MESH_ALL
--
 CREATE TABLE "BIOMART"."MESH_ALL" 
  (	"UI" VARCHAR2(20 BYTE), 
"MH" VARCHAR2(200 BYTE), 
 PRIMARY KEY ("UI")
 USING INDEX
 TABLESPACE "TRANSMART"  ENABLE
  ) SEGMENT CREATION IMMEDIATE
NOCOMPRESS NOLOGGING
 TABLESPACE "TRANSMART" ;
