--
-- Type: TABLE; Owner: BIOMART; Name: MESH_TEMP
--
 CREATE TABLE "BIOMART"."MESH_TEMP" 
  (	"UI" VARCHAR2(20 BYTE), 
"MH" VARCHAR2(200 BYTE), 
"MN" VARCHAR2(200 BYTE)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

