--
-- Type: TABLE; Owner: BIOMART; Name: TMP_OMICSOFT_COMPOUND
--
 CREATE TABLE "BIOMART"."TMP_OMICSOFT_COMPOUND" 
  (	"ACCESSION" VARCHAR2(100 BYTE), 
"BIO_COMPOUND_ID" NUMBER(18,0) NOT NULL ENABLE, 
"CAS_REGISTRY" NVARCHAR2(400), 
"COMPOUND" VARCHAR2(4000 BYTE), 
"BIO_EXPERIMENT_ID" NUMBER(18,0)
  ) SEGMENT CREATION DEFERRED
 TABLESPACE "TRANSMART" ;

