--
-- Type: TABLE; Owner: BIOMART; Name: TMP_PROJECT_CATEGORY
--
 CREATE TABLE "BIOMART"."TMP_PROJECT_CATEGORY" 
  (	"FILE_ID" VARCHAR2(100 BYTE), 
"ACCESSION" VARCHAR2(100 BYTE), 
"CATEGORY" VARCHAR2(4000 BYTE)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

