--
-- Type: TABLE; Owner: BIOMART; Name: TMP_PROJECT_DISEASE
--
 CREATE TABLE "BIOMART"."TMP_PROJECT_DISEASE" 
  (	"FILE_ID" VARCHAR2(100 BYTE), 
"ACCESSION" VARCHAR2(100 BYTE), 
"DISEASE" VARCHAR2(4000 BYTE)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

