--
-- Type: TABLE; Owner: BIOMART; Name: TMP_BIO_MARKER
--
 CREATE TABLE "BIOMART"."TMP_BIO_MARKER" 
  (	"ID" NUMBER, 
"GENE_ID" VARCHAR2(50 BYTE), 
"ORGANISM" VARCHAR2(200 BYTE)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

