--
-- Type: TABLE; Owner: TM_LZ; Name: LT_METABOLOMIC_DISPLAY_MAPPING
--
 CREATE TABLE "TM_LZ"."LT_METABOLOMIC_DISPLAY_MAPPING" 
  (	"CATEGORY_CD" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
"DISPLAY_VALUE" VARCHAR2(100 BYTE), 
"DISPLAY_LABEL" VARCHAR2(200 BYTE), 
"DISPLAY_UNIT" VARCHAR2(20 BYTE)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

