--
-- Type: TABLE; Owner: TM_LZ; Name: LT_RNASEQ_ANNOTATION
--
 CREATE TABLE "TM_LZ"."LT_RNASEQ_ANNOTATION" 
  (	"TRANSCRIPT_ID" VARCHAR2(50 BYTE), 
"GENE_SYMBOL" VARCHAR2(50 BYTE), 
"ORGANISM" VARCHAR2(30 BYTE)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

