--
-- Type: TABLE; Owner: TM_LZ; Name: LT_SNP_CALLS_BY_GSM
--
 CREATE TABLE "TM_LZ"."LT_SNP_CALLS_BY_GSM" 
  (	"GSM_NUM" VARCHAR2(10 BYTE), 
"SNP_NAME" VARCHAR2(100 BYTE), 
"SNP_CALLS" VARCHAR2(4 BYTE)
  ) SEGMENT CREATION IMMEDIATE
NOCOMPRESS LOGGING
 TABLESPACE "TRANSMART" ;
