--
-- Type: TABLE; Owner: TM_LZ; Name: LT_SRC_RBM_DATA
--
 CREATE TABLE "TM_LZ"."LT_SRC_RBM_DATA" 
  (	"SAMPLE_ID" VARCHAR2(200 BYTE), 
"ANALYTE" VARCHAR2(200 BYTE), 
"AVALUE" VARCHAR2(200 BYTE), 
"TRIAL_ID" VARCHAR2(20 BYTE)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

