--
-- Type: TABLE; Owner: TM_LZ; Name: LT_SRC_NEXTBIO
--
 CREATE TABLE "TM_LZ"."LT_SRC_NEXTBIO" 
  (	"BIO_CONCEPT_CODE" VARCHAR2(1000 BYTE), 
"CODE_NAME" VARCHAR2(1000 BYTE), 
"CODE_DESCRIPTION" VARCHAR2(1000 BYTE), 
"CODE_TYPE_NAME" VARCHAR2(1000 BYTE)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

