--
-- Type: TABLE; Owner: TM_LZ; Name: LT_SNP_COPY_NUMBER
--
 CREATE TABLE "TM_LZ"."LT_SNP_COPY_NUMBER" 
  (	"SNP_NAME" VARCHAR2(50 BYTE), 
"CHROM" VARCHAR2(2 BYTE), 
"CHROM_POS" NUMBER(20,0), 
"COPY_NUMBER" FLOAT(53), 
"GSM_NUM" VARCHAR2(10 BYTE)
  ) SEGMENT CREATION DEFERRED
NOCOMPRESS LOGGING
 TABLESPACE "TRANSMART" ;
