--
-- Type: TABLE; Owner: TM_LZ; Name: LT_SRC_MIRNA_DEAPP_ANNOT
--
 CREATE TABLE "TM_LZ"."LT_SRC_MIRNA_DEAPP_ANNOT" 
  (	"ID_REF" VARCHAR2(100 BYTE), 
"PROBE_ID" VARCHAR2(100 BYTE), 
"MIRNA_SYMBOL" VARCHAR2(100 BYTE), 
"MIRNA_ID" VARCHAR2(250 BYTE), 
"ORGANISM" VARCHAR2(200 BYTE)
  ) SEGMENT CREATION DEFERRED
 TABLESPACE "TRANSMART" ;

