--
-- Type: TABLE; Owner: TM_LZ; Name: LT_SRC_RBM_ANNOTATION
--
 CREATE TABLE "TM_LZ"."LT_SRC_RBM_ANNOTATION" 
  (	"GPL_ID" VARCHAR2(50 BYTE), 
"ANTIGEN_NAME" VARCHAR2(200 BYTE), 
"UNIPROTID" VARCHAR2(50 BYTE), 
"GENE_SYMBOL" VARCHAR2(200 BYTE), 
"GENE_ID" VARCHAR2(50 BYTE)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

