--
-- Type: TABLE; Owner: TM_LZ; Name: LT_SRC_SEARCH_KEYWORD
--
 CREATE TABLE "TM_LZ"."LT_SRC_SEARCH_KEYWORD" 
  (	"KEYWORD" NVARCHAR2(300), 
"DISPLAY_CATEGORY" NVARCHAR2(300), 
"DATA_CATEGORY" NVARCHAR2(200), 
"SOURCE_CD" NVARCHAR2(200), 
"UID_PREFIX" NVARCHAR2(20), 
"UNIQUE_ID" NVARCHAR2(300), 
"PARENT_TERM" NVARCHAR2(300), 
"BIO_DATA_ID" NVARCHAR2(300)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

