--
-- Type: TABLE; Owner: TM_LZ; Name: LT_SRC_RNASEQ_DATA
--
 CREATE TABLE "TM_LZ"."LT_SRC_RNASEQ_DATA" 
  (	"TRIAL_NAME" VARCHAR2(25 BYTE), 
"REGION_NAME" VARCHAR2(100 BYTE), 
"EXPR_ID" VARCHAR2(100 BYTE), 
"READCOUNT" VARCHAR2(50 BYTE)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

