--
-- Type: TABLE; Owner: TM_LZ; Name: LT_SNP_GENE_MAP
--
 CREATE TABLE "TM_LZ"."LT_SNP_GENE_MAP" 
  (	"SNP_NAME" VARCHAR2(256 BYTE), 
"ENTREZ_GENE_ID" NUMBER
  ) SEGMENT CREATION DEFERRED
NOCOMPRESS LOGGING
 TABLESPACE "TRANSMART" ;
