--
-- Type: TABLE; Owner: TM_LZ; Name: LZ_SRC_SUBJ_ENROLL_DATE
--
 CREATE TABLE "TM_LZ"."LZ_SRC_SUBJ_ENROLL_DATE" 
  (	"STUDY_ID" VARCHAR2(25 BYTE), 
"SITE_ID" VARCHAR2(50 BYTE), 
"SUBJECT_ID" VARCHAR2(20 BYTE), 
"ENROLL_DATE" VARCHAR2(25 BYTE)
  ) SEGMENT CREATION DEFERRED
 TABLESPACE "TRANSMART" ;

