--
-- Type: TABLE; Owner: TM_LZ; Name: RWG_SAMPLES
--
 CREATE TABLE "TM_LZ"."RWG_SAMPLES" 
  (	"STUDY_ID" VARCHAR2(500 BYTE), 
"EXPR_ID" VARCHAR2(500 BYTE), 
"COHORTS" VARCHAR2(500 BYTE), 
"IMPORT_DATE" TIMESTAMP (6) DEFAULT sysdate NOT NULL ENABLE
  ) SEGMENT CREATION DEFERRED
 TABLESPACE "TRANSMART" ;

