--
-- Type: TABLE; Owner: TM_LZ; Name: WT_SNP_NODE_VALUES
--
 CREATE TABLE "TM_LZ"."WT_SNP_NODE_VALUES" 
  (	"CATEGORY_CD" VARCHAR2(500 BYTE), 
"SAMPLE_TYPE" VARCHAR2(200 BYTE), 
"TIMEPOINT" VARCHAR2(200 BYTE), 
"TITLE" VARCHAR2(500 BYTE)
  ) SEGMENT CREATION DEFERRED
 TABLESPACE "TRANSMART" ;

