--
-- Type: TABLE; Owner: I2B2DEMODATA; Name: CONCEPT_COUNTS_BK
--
 CREATE TABLE "I2B2DEMODATA"."CONCEPT_COUNTS_BK" 
  (	"CONCEPT_PATH" VARCHAR2(500 BYTE), 
"PARENT_CONCEPT_PATH" VARCHAR2(500 BYTE), 
"PATIENT_COUNT" NUMBER(38,0)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

