--
-- Type: TABLE; Owner: I2B2DEMODATA; Name: DATAMART_REPORT
--
 CREATE TABLE "I2B2DEMODATA"."DATAMART_REPORT" 
  (	"TOTAL_PATIENT" NUMBER(38,0), 
"TOTAL_OBSERVATIONFACT" NUMBER(38,0), 
"TOTAL_EVENT" NUMBER(38,0), 
"REPORT_DATE" DATE
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

