--
-- Type: TABLE; Owner: I2B2DEMODATA; Name: DR$OF_CTX_BLOB$I
--
 CREATE TABLE "I2B2DEMODATA"."DR$OF_CTX_BLOB$I" 
  (	"TOKEN_TEXT" VARCHAR2(64 BYTE) NOT NULL ENABLE, 
"TOKEN_TYPE" NUMBER(10,0) NOT NULL ENABLE, 
"TOKEN_FIRST" NUMBER(10,0) NOT NULL ENABLE, 
"TOKEN_LAST" NUMBER(10,0) NOT NULL ENABLE, 
"TOKEN_COUNT" NUMBER(10,0) NOT NULL ENABLE, 
"TOKEN_INFO" BLOB
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" 
LOB ("TOKEN_INFO") STORE AS BASICFILE (
 TABLESPACE "TRANSMART" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
 NOCACHE LOGGING ) ;

--
-- Type: INDEX; Owner: I2B2DEMODATA; Name: DR$OF_CTX_BLOB$X
--
CREATE INDEX "I2B2DEMODATA"."DR$OF_CTX_BLOB$X" ON "I2B2DEMODATA"."DR$OF_CTX_BLOB$I" ("TOKEN_TEXT", "TOKEN_TYPE", "TOKEN_FIRST", "TOKEN_LAST", "TOKEN_COUNT")
TABLESPACE "TRANSMART" ;

