--
-- Type: TABLE; Owner: I2B2DEMODATA; Name: GLOBAL_TEMP_PARAM_TABLE
--
 CREATE GLOBAL TEMPORARY TABLE "I2B2DEMODATA"."GLOBAL_TEMP_PARAM_TABLE" 
  (	"SET_INDEX" NUMBER(*,0), 
"CHAR_PARAM1" VARCHAR2(500 BYTE), 
"CHAR_PARAM2" VARCHAR2(500 BYTE), 
"NUM_PARAM1" NUMBER(*,0), 
"NUM_PARAM2" NUMBER(*,0)
  ) ON COMMIT PRESERVE ROWS ;

