--
-- Type: TABLE; Owner: I2B2DEMODATA; Name: HILOSEQUENCES
--
 CREATE TABLE "I2B2DEMODATA"."HILOSEQUENCES" 
  (	"SEQUENCENAME" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
"HIGHVALUES" NUMBER(*,0) NOT NULL ENABLE
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

