--
-- Type: TABLE; Owner: I2B2DEMODATA; Name: MAP
--
 CREATE TABLE "I2B2DEMODATA"."MAP" 
  (	"SUBJECT_ID" VARCHAR2(100 BYTE), 
"SMAPLE_ID" VARCHAR2(100 BYTE)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

