--
-- Type: TABLE; Owner: I2B2DEMODATA; Name: MODIFIER_METADATA
--
 CREATE TABLE "I2B2DEMODATA"."MODIFIER_METADATA" 
  (	"MODIFIER_CD" VARCHAR2(50 BYTE), 
"VALTYPE_CD" VARCHAR2(10 BYTE), 
"STD_UNITS" VARCHAR2(50 BYTE), 
"VISIT_IND" CHAR(1 BYTE)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

