--
-- Type: TABLE; Owner: I2B2DEMODATA; Name: QT_PRIVILEGE
--
 CREATE TABLE "I2B2DEMODATA"."QT_PRIVILEGE" 
  (	"PROTECTION_LABEL_CD" VARCHAR2(1500 BYTE), 
"DATAPROT_CD" VARCHAR2(1000 BYTE), 
"HIVEMGMT_CD" VARCHAR2(1000 BYTE), 
"PLUGIN_ID" NUMBER(10,0)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

