--
-- Type: TABLE; Owner: I2B2DEMODATA; Name: STORAGE_SYSTEM
--
 CREATE TABLE "I2B2DEMODATA"."STORAGE_SYSTEM"
  (	"ID" NUMBER(*,0) NOT NULL ENABLE,
"NAME" VARCHAR2(50 BYTE),
"SYSTEMTYPE" VARCHAR2(50 BYTE),
"URL" VARCHAR2(900 BYTE),
"SYSTEM_VERSION" VARCHAR2(50 BYTE),
"SINGLE_FILE_COLLECTIONS" CHAR(1 BYTE),
 CONSTRAINT "STORAGE_SYSTEM_PKEY" PRIMARY KEY ("ID")
 USING INDEX
 TABLESPACE "TRANSMART"  ENABLE
  ) SEGMENT CREATION IMMEDIATE
NOCOMPRESS LOGGING
 TABLESPACE "TRANSMART" ;
