--
-- Type: SEQUENCE; Owner: I2B2DEMODATA; Name: STUDY_NUM_SEQ;
--
CREATE SEQUENCE "I2B2DEMODATA"."STUDY_NUM_SEQ"
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 999999999999999999999999999
CACHE 20
NOORDER
NOCYCLE;

--
-- Type: TABLE; Owner: I2B2DEMODATA; Name: STUDY
--
 CREATE TABLE "I2B2DEMODATA"."STUDY"
  (	"STUDY_NUM" NUMBER(38,0) DEFAULT "I2B2DEMODATA"."STUDY_NUM_SEQ"."NEXTVAL",
"BIO_EXPERIMENT_ID" NUMBER(18,0),
"STUDY_ID" VARCHAR2(100 BYTE) NOT NULL ENABLE,
"SECURE_OBJ_TOKEN" NVARCHAR2(200) NOT NULL ENABLE,
"STUDY_BLOB" CLOB,
 CONSTRAINT "STUDY_PK" PRIMARY KEY ("STUDY_NUM")
 USING INDEX
 TABLESPACE "TRANSMART"  ENABLE
  ) SEGMENT CREATION DEFERRED
NOCOMPRESS LOGGING
 TABLESPACE "TRANSMART" ;

--
-- Type: TRIGGER; Owner: I2B2DEMODATA; Name: TRG_STUDY_NUM
--
CREATE OR REPLACE EDITIONABLE TRIGGER "I2B2DEMODATA"."TRG_STUDY_NUM"
before insert on "I2B2DEMODATA"."STUDY"
for each row
begin
 if inserting then
  if :NEW."STUDY_NUM" is null then
   select STUDY_NUM_SEQ.nextval into :NEW."STUDY_NUM" from dual;
  end if;
 end if;
end;

/
ALTER TRIGGER "I2B2DEMODATA"."TRG_STUDY_NUM" ENABLE;

--
-- Type: INDEX; Owner: I2B2DEMODATA; Name: IDX_STUDY_SECURE_OBJ_TOKEN
--
CREATE INDEX "I2B2DEMODATA"."IDX_STUDY_SECURE_OBJ_TOKEN" ON "I2B2DEMODATA"."STUDY" ("SECURE_OBJ_TOKEN")
TABLESPACE "INDX" ;

--
-- add documentation
--
COMMENT ON TABLE i2b2demodata.study IS 'Table holds studies and their access tokens';

COMMENT ON COLUMN study.study_num IS 'Primary key.';
COMMENT ON COLUMN study.bio_experiment_id IS 'Foreign key: bio_experiment_id in bio_experiment.';
COMMENT ON COLUMN study.study_id IS 'E.g., GSE8581.';
COMMENT ON COLUMN study.secure_obj_token IS 'Token needed for access to the study. E.g., ‘PUBLIC’ or ‘EXP:GSE8581’.';
COMMENT ON COLUMN study.study_blob IS 'Stores arbitrary information about the study';