--
-- Type: TABLE; Owner: I2B2DEMODATA; Name: TIMERS
--
 CREATE TABLE "I2B2DEMODATA"."TIMERS" 
  (	"TIMERID" VARCHAR2(80 BYTE) NOT NULL ENABLE, 
"TARGETID" VARCHAR2(250 BYTE) NOT NULL ENABLE, 
"INITIALDATE" TIMESTAMP (9) NOT NULL ENABLE, 
"TIMERINTERVAL" NUMBER(19,0), 
"INSTANCEPK" BLOB, 
"INFO" BLOB, 
 CONSTRAINT "TIMERS_PK" PRIMARY KEY ("TIMERID", "TARGETID")
 USING INDEX
 TABLESPACE "TRANSMART"  ENABLE
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" 
LOB ("INSTANCEPK") STORE AS BASICFILE (
 TABLESPACE "TRANSMART" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
 NOCACHE LOGGING ) 
LOB ("INFO") STORE AS BASICFILE (
 TABLESPACE "TRANSMART" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
 NOCACHE LOGGING ) ;

