--
-- Type: SEQUENCE; Owner: I2B2DEMODATA; Name: TRIAL_VISIT_NUM_SEQ;
--
CREATE SEQUENCE "I2B2DEMODATA"."TRIAL_VISIT_NUM_SEQ"
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 999999999999999999999999999
CACHE 20
NOORDER
NOCYCLE;

--
-- Type: TABLE; Owner: I2B2DEMODATA; Name: TRIAL_VISIT_DIMENSION
--
 CREATE TABLE "I2B2DEMODATA"."TRIAL_VISIT_DIMENSION"
  (	"TRIAL_VISIT_NUM" NUMBER(38,0) DEFAULT "I2B2DEMODATA"."TRIAL_VISIT_NUM_SEQ"."NEXTVAL",
"STUDY_NUM" NUMBER(38,0) NOT NULL ENABLE,
"REL_TIME_UNIT_CD" VARCHAR2(50 BYTE),
"REL_TIME_NUM" NUMBER(38,0),
"REL_TIME_LABEL" VARCHAR2(900 BYTE),
 CONSTRAINT "TRIAL_VISIT_DIMENSION_PK" PRIMARY KEY ("TRIAL_VISIT_NUM")
 USING INDEX
 TABLESPACE "TRANSMART"  ENABLE
  ) SEGMENT CREATION IMMEDIATE
NOCOMPRESS LOGGING
 TABLESPACE "TRANSMART" ;

--
-- Type: TRIGGER; Owner: I2B2DEMODATA; Name: TRG_TRIAL_VISIT_NUM
--
CREATE OR REPLACE TRIGGER "I2B2DEMODATA"."TRG_TRIAL_VISIT_NUM"
before insert on "I2B2DEMODATA"."TRIAL_VISIT_DIMENSION"
for each row
begin
 if inserting then
  if :NEW."STUDY_NUM" is null then
   select TRIAL_VISIT_NUM_SEQ.nextval into :NEW."TRIAL_VISIT_NUM" from dual;
  end if;
 end if;
end;

/
ALTER TRIGGER "I2B2DEMODATA"."TRG_TRIAL_VISIT_NUM" ENABLE;

--
-- Type: REF_CONSTRAINT; Owner: I2B2DEMODATA; Name: TRIAL_VISIT_DIMENSION_STUDY_FK
--
ALTER TABLE "I2B2DEMODATA"."TRIAL_VISIT_DIMENSION" ADD CONSTRAINT "TRIAL_VISIT_DIMENSION_STUDY_FK" FOREIGN KEY ("STUDY_NUM")
 REFERENCES "I2B2DEMODATA"."STUDY" ("STUDY_NUM") ENABLE;

--
-- add documentation
--
COMMENT ON TABLE i2b2demodata.trial_visit_dimension IS 'Table holds descriptions of trial visits, which represent relative time points in a study.';

COMMENT ON COLUMN trial_visit_dimension.trial_visit_num IS 'Primary key.';
COMMENT ON COLUMN trial_visit_dimension.study_num IS 'Foreign key to study_num in study.';
COMMENT ON COLUMN trial_visit_dimension.rel_time_unit_cd IS 'The unit in which rel_time_num is expressed. E.g., Week, Day, Visit.';
COMMENT ON COLUMN trial_visit_dimension.rel_time_num IS 'E.g., 1 (for Week 1).';
COMMENT ON COLUMN trial_visit_dimension.rel_time_label IS 'Descriptive name. E.g., Baseline, Week 1.';