\ir prelude.sql
\ir functions/bio_assay_analysis_uid.sql
\ir functions/bio_assay_platform_uid.sql
\ir functions/bio_asy_analysis_pltfm_uid.sql
\ir functions/bio_compound_uid.sql
\ir functions/bio_curation_dataset_uid.sql
\ir functions/bio_disease_uid.sql
\ir functions/bio_experiment_uid.sql
\ir functions/bio_jub_oncol_data_uid.sql
\ir functions/bio_jub_oncol_sum_data_uid.sql
\ir functions/biomarker_gene_uid.sql
\ir functions/biomarker_pathway_uid.sql
\ir functions/cum_normal_dist.sql
\ir functions/fract_error_dist.sql
\ir functions/refresh_bio_lit_int_model_mv.sql
\ir functions/refresh_bio_marker_correl_mv.sql
\ir functions/tea_npv_precompute.sql
\ir bio_analysis_attribute.sql
\ir bio_analysis_attribute_lineage.sql
\ir bio_analysis_cohort_xref.sql
\ir bio_assay_platform.sql
\ir bio_experiment.sql
\ir bio_assay.sql
\ir bio_asy_analysis_pltfm.sql
\ir bio_assay_analysis.sql
\ir bio_assay_feature_group.sql
\ir bio_assay_analysis_data.sql
\ir bio_assay_analysis_data_tea.sql
\ir bio_assay_cohort.sql
\ir bio_assay_dataset.sql
\ir bio_subject.sql
\ir bio_disease.sql
\ir bio_cell_line.sql
\ir bio_clinical_trial.sql
\ir bio_clinc_trial_pt_group.sql
\ir bio_patient.sql
\ir bio_clinc_trial_time_pt.sql
\ir bio_patient_event.sql
\ir bio_sample.sql
\ir bio_assay_data.sql
\ir bio_assay_data_annotation.sql
\ir bio_assay_data_stats.sql
\ir bio_assay_sample.sql
\ir bio_asy_analysis_dataset.sql
\ir bio_asy_data_stats_all.sql
\ir bio_cgdcp_data.sql
\ir bio_clinc_trial_attr.sql
\ir bio_clinical_trial_design.sql
\ir bio_cohort_exp_xref.sql
\ir bio_compound.sql
\ir bio_concept_code.sql
\ir bio_content_repository.sql
\ir bio_content.sql
\ir bio_content_reference.sql
\ir bio_curation_dataset.sql
\ir bio_curated_data.sql
\ir bio_data_attribute.sql
\ir bio_data_compound.sql
\ir bio_data_correl_descr.sql
\ir bio_data_correlation.sql
\ir bio_data_disease.sql
\ir bio_data_ext_code.sql
\ir bio_data_literature.sql
\ir bio_data_omic_marker.sql
\ir bio_taxonomy.sql
\ir bio_data_taxonomy.sql
\ir bio_data_uid.sql
\ir bio_lit_ref_data.sql
\ir bio_lit_alt_data.sql
\ir bio_lit_amd_data.sql
\ir bio_lit_inh_data.sql
\ir bio_lit_int_data.sql
\ir bio_lit_int_model_mv.sql
\ir bio_lit_model_data.sql
\ir bio_lit_pe_data.sql
\ir bio_lit_sum_data.sql
\ir bio_marker.sql
\ir bio_patient_event_attr.sql
\ir bio_stats_exp_marker.sql
\ir cta_results.sql
\ir ctd2_clin_inhib_effect.sql
\ir ctd2_disease.sql
\ir ctd2_inhib_details.sql
\ir ctd2_study.sql
\ir ctd2_trial_details.sql
\ir ctd_allowed_meds_treatment.sql
\ir ctd_full.sql
\ir ctd_biomarker.sql
\ir ctd_disease.sql
\ir ctd_drug_inhib.sql
\ir ctd_inclusion_criteria.sql
\ir ctd_primary_endpts.sql
\ir ctd_sec_endpts.sql
\ir ctd_study.sql
\ir heat_map_results.sql
\ir tmp_analysis_data_tea_rank.sql
\ir _misc.sql
