\i biomart/prelude.sql
\i biomart/functions/bio_assay_analysis_uid.sql
\i biomart/functions/bio_assay_platform_uid.sql
\i biomart/functions/bio_asy_analysis_pltfm_uid.sql
\i biomart/functions/bio_compound_uid.sql
\i biomart/functions/bio_curation_dataset_uid.sql
\i biomart/functions/bio_disease_uid.sql
\i biomart/functions/bio_experiment_uid.sql
\i biomart/functions/bio_jub_oncol_data_uid.sql
\i biomart/functions/bio_jub_oncol_sum_data_uid.sql
\i biomart/functions/biomarker_gene_uid.sql
\i biomart/functions/biomarker_pathway_uid.sql
\i biomart/functions/cum_normal_dist.sql
\i biomart/functions/fract_error_dist.sql
\i biomart/functions/refresh_bio_lit_int_model_mv.sql
\i biomart/functions/refresh_bio_marker_correl_mv.sql
\i biomart/functions/tea_npv_precompute.sql
\i biomart/bio_analysis_attribute.sql
\i biomart/bio_analysis_attribute_lineage.sql
\i biomart/bio_analysis_cohort_xref.sql
\i biomart/bio_assay_platform.sql
\i biomart/bio_experiment.sql
\i biomart/bio_assay.sql
\i biomart/bio_asy_analysis_pltfm.sql
\i biomart/bio_assay_analysis.sql
\i biomart/bio_assay_feature_group.sql
\i biomart/bio_assay_analysis_data.sql
\i biomart/bio_assay_analysis_data_tea.sql
\i biomart/bio_assay_cohort.sql
\i biomart/bio_assay_dataset.sql
\i biomart/bio_subject.sql
\i biomart/bio_disease.sql
\i biomart/bio_cell_line.sql
\i biomart/bio_clinical_trial.sql
\i biomart/bio_clinc_trial_pt_group.sql
\i biomart/bio_patient.sql
\i biomart/bio_clinc_trial_time_pt.sql
\i biomart/bio_patient_event.sql
\i biomart/bio_sample.sql
\i biomart/bio_assay_data.sql
\i biomart/bio_assay_data_annotation.sql
\i biomart/bio_assay_data_stats.sql
\i biomart/bio_assay_sample.sql
\i biomart/bio_asy_analysis_dataset.sql
\i biomart/bio_asy_data_stats_all.sql
\i biomart/bio_cgdcp_data.sql
\i biomart/bio_clinc_trial_attr.sql
\i biomart/bio_clinical_trial_design.sql
\i biomart/bio_cohort_exp_xref.sql
\i biomart/bio_compound.sql
\i biomart/bio_concept_code.sql
\i biomart/bio_content_repository.sql
\i biomart/bio_content.sql
\i biomart/bio_content_reference.sql
\i biomart/bio_curation_dataset.sql
\i biomart/bio_curated_data.sql
\i biomart/bio_data_attribute.sql
\i biomart/bio_data_compound.sql
\i biomart/bio_data_correl_descr.sql
\i biomart/bio_data_correlation.sql
\i biomart/bio_data_disease.sql
\i biomart/bio_data_ext_code.sql
\i biomart/bio_data_literature.sql
\i biomart/bio_data_omic_marker.sql
\i biomart/bio_taxonomy.sql
\i biomart/bio_data_taxonomy.sql
\i biomart/bio_data_uid.sql
\i biomart/bio_lit_ref_data.sql
\i biomart/bio_lit_alt_data.sql
\i biomart/bio_lit_amd_data.sql
\i biomart/bio_lit_inh_data.sql
\i biomart/bio_lit_int_data.sql
\i biomart/bio_lit_int_model_mv.sql
\i biomart/bio_lit_model_data.sql
\i biomart/bio_lit_pe_data.sql
\i biomart/bio_lit_sum_data.sql
\i biomart/bio_marker.sql
\i biomart/bio_patient_event_attr.sql
\i biomart/bio_stats_exp_marker.sql
\i biomart/cta_results.sql
\i biomart/ctd2_clin_inhib_effect.sql
\i biomart/ctd2_disease.sql
\i biomart/ctd2_inhib_details.sql
\i biomart/ctd2_study.sql
\i biomart/ctd2_trial_details.sql
\i biomart/ctd_allowed_meds_treatment.sql
\i biomart/ctd_full.sql
\i biomart/ctd_biomarker.sql
\i biomart/ctd_disease.sql
\i biomart/ctd_drug_inhib.sql
\i biomart/ctd_inclusion_criteria.sql
\i biomart/ctd_primary_endpts.sql
\i biomart/ctd_sec_endpts.sql
\i biomart/ctd_study.sql
\i biomart/heat_map_results.sql
\i biomart/_misc.sql
