--
-- Type: TYPE; Owner: BIOMART_USER; Name: CONCEPT_CD_TAB
--
  CREATE OR REPLACE TYPE "BIOMART_USER"."CONCEPT_CD_TAB" IS TABLE OF VARCHAR2(50)
/

--
-- Type: TYPE; Owner: BIOMART_USER; Name: PATIENTS_TAB
--
  CREATE OR REPLACE TYPE "BIOMART_USER"."PATIENTS_TAB" IS TABLE OF NUMBER(10,0)
/

