--
-- Type: TABLE; Owner: BIOMART_USER; Name: IOE_TEMP_OBJ_REG2
--
 CREATE TABLE "BIOMART_USER"."IOE_TEMP_OBJ_REG2" 
  (	"OBJECT_SCHEMA" VARCHAR2(32 BYTE), 
"OBJECT_NAME" VARCHAR2(32 BYTE), 
"OBJECT_TYPE" VARCHAR2(64 BYTE), 
"KDE_USERNAME" VARCHAR2(64 BYTE), 
"KDE_SESSION" VARCHAR2(255 BYTE), 
"OBJECT_CREATED_TIMESTAMP" TIMESTAMP (0)
  ) SEGMENT CREATION DEFERRED
 TABLESPACE "BIOMART" ;

