--
-- Type: TABLE; Owner: BIOMART_USER; Name: KDE_TEMP_OBJ_REG3
--
 CREATE TABLE "BIOMART_USER"."KDE_TEMP_OBJ_REG3" 
  (	"OBJECT_SCHEMA" VARCHAR2(32 BYTE), 
"OBJECT_NAME" VARCHAR2(32 BYTE), 
"OBJECT_TYPE" VARCHAR2(64 BYTE), 
"KDE_USERNAME" VARCHAR2(64 BYTE), 
"KDE_SESSION" VARCHAR2(255 BYTE), 
"OBJECT_CREATED_TIMESTAMP" CHAR(15 BYTE)
  ) SEGMENT CREATION DEFERRED
NOCOMPRESS LOGGING
 TABLESPACE "BIOMART" ;
