package org.transmartproject.db.storage

/**
 * Created by piotrzakrzewski on 02/12/2016.
 */
class LinkedFileCollection {

    String study // Id of the Study with which the collection is associated
    String uuid // uniformly unique identifier generated by the source system
    StorageSystem sourceSystem // origin of the collection
    String name  // name of the collection, or name the file for single file collection systems (e.g. MongoDB)

    static belongsTo = [
            sourceSystem:        StorageSystem,
    ]

    static mapping = {
        table          schema:   'I2B2DEMODATA'
        version false
    }

    static constraints = {
        sourceSystem nullable: false
    }
}
