--
-- permissions for galaxy schema
--

set search_path = galaxy, pg_catalog;

ALTER DEFAULT PRIVILEGES FOR USER postgres IN SCHEMA galaxy GRANT ALL ON TABLES TO biomart_user;
ALTER DEFAULT PRIVILEGES FOR USER postgres IN SCHEMA galaxy GRANT ALL ON SEQUENCES TO biomart_user;
ALTER DEFAULT PRIVILEGES FOR USER postgres IN SCHEMA galaxy GRANT ALL ON FUNCTIONS TO biomart_user;
ALTER DEFAULT PRIVILEGES FOR USER tm_cz IN SCHEMA galaxy GRANT ALL ON TABLES TO biomart_user;
ALTER DEFAULT PRIVILEGES FOR USER tm_cz IN SCHEMA galaxy GRANT ALL ON SEQUENCES TO biomart_user;
ALTER DEFAULT PRIVILEGES FOR USER tm_cz IN SCHEMA galaxy GRANT ALL ON FUNCTIONS TO biomart_user;

GRANT ALL ON ALL TABLES IN SCHEMA galaxy TO tm_cz;
GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA galaxy TO biomart_user;
GRANT ALL ON ALL SEQUENCES IN SCHEMA galaxy TO tm_cz;
GRANT ALL ON ALL SEQUENCES IN SCHEMA galaxy TO biomart_user;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA galaxy TO tm_cz;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA galaxy TO biomart_user;
