--
-- Type: TABLE; Owner: TM_CZ; Name: BIO_DATA_COMPOUND_RELEASE
--
 CREATE TABLE "TM_CZ"."BIO_DATA_COMPOUND_RELEASE" 
  (	"BIO_DATA_ID" NUMBER(18,0) NOT NULL ENABLE, 
"BIO_COMPOUND_ID" NUMBER(18,0) NOT NULL ENABLE, 
"ETL_SOURCE" VARCHAR2(100 BYTE), 
"RELEASE_STUDY" NVARCHAR2(100)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

