--
-- Type: TABLE; Owner: TM_CZ; Name: CZ_TEST_SEVERITY
--
 CREATE TABLE "TM_CZ"."CZ_TEST_SEVERITY" 
  (	"TEST_SEVERITY_CD" NVARCHAR2(10) NOT NULL ENABLE, 
"SEVERITY_NAME" NVARCHAR2(255), 
"SEVERITY_LEVEL" NUMBER(1,0)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

