--
-- Type: TABLE; Owner: TM_CZ; Name: I2B2_TAGS_RELEASE
--
 CREATE TABLE "TM_CZ"."I2B2_TAGS_RELEASE" 
  (	"TAG_ID" NUMBER(18,0) NOT NULL ENABLE, 
"PATH" NVARCHAR2(200), 
"TAG" NVARCHAR2(200), 
"TAG_TYPE" NVARCHAR2(200), 
"RELEASE_STUDY" NVARCHAR2(200)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

