--
-- Type: TABLE; Owner: TM_CZ; Name: UPDATEZSCORE_PROTEOMICS
--
 CREATE TABLE "TM_CZ"."UPDATEZSCORE_PROTEOMICS" 
  (	"TRIAL_NAME" VARCHAR2(50 BYTE), 
"PROTEIN_ANNOTATION_ID" NUMBER(38,0), 
"COMPONENT" VARCHAR2(100 BYTE), 
"PATIENT_ID" NUMBER(38,0), 
"GENE_SYMBOL" VARCHAR2(100 BYTE), 
"GENE_ID" VARCHAR2(200 BYTE), 
"ASSAY_ID" NUMBER, 
"SUBJECT_ID" VARCHAR2(100 BYTE), 
"INTENSITY" NUMBER, 
"ZSCORE" NUMBER, 
"LOG_INTENSITY" NUMBER, 
"MEAN_VALUE" NUMBER, 
"MEDIAN_VALUE" NUMBER, 
"STDDEV_VALUE" NUMBER, 
"TIMEPOINT" VARCHAR2(100 BYTE)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

