<?php

if (!isset($_ENV['ORACLE_TABLESPACES_DIR'])) {
	fprintf(STDERR, "%s", "\$ORACLE_TABLESPACES_DIR not set\n");
	exit(1);
}

echo <<<EOD
ALTER SYSTEM SET DB_CREATE_FILE_DEST = '$_ENV[ORACLE_TABLESPACES_DIR]';

CREATE TABLESPACE transmart;
CREATE TABLESPACE indx;
EOD;
