<?php

if (!isset($_ENV['ORACLE_TABLESPACES_DIR'])) {
	fprintf(STDERR, "%s", "\$ORACLE_TABLESPACES_DIR not set\n");
	exit(1);
}

echo <<<EOD
ALTER SYSTEM SET DB_CREATE_FILE_DEST = '$_ENV[ORACLE_TABLESPACES_DIR]';

CREATE TABLESPACE deapp;
CREATE TABLESPACE biomart;
CREATE TABLESPACE transmart;
CREATE TABLESPACE indx;
CREATE TABLESPACE search_app;
CREATE TABLESPACE i2b2_data;
CREATE TABLESPACE galaxy;
CREATE TABLESPACE users;
EOD;
